import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { generateKeyPair,exportJWK,createLocalJWKSet,SignJWT } from 'jose';
import {verifyAccess} from '../cloud/auth.mjs';
import {createWorker} from '../cloud/worker.mjs';
const keys=await generateKeyPair('RS256'),other=await generateKeyPair('RS256');
const jwk=await exportJWK(keys.publicKey);jwk.kid='test';const jwks=createLocalJWKSet({keys:[jwk]});
const env={CF_ACCESS_TEAM_DOMAIN:'https://personal.cloudflareaccess.com',CF_ACCESS_AUD:'learning-aud',ALLOWED_EMAILS:'owner@example.com',APP_ORIGIN:'https://learn.example.com'};
async function token(overrides={},key=keys.privateKey){return new SignJWT({email:'owner@example.com',...overrides}).setProtectedHeader({alg:'RS256',kid:'test'}).setIssuer(overrides.iss??env.CF_ACCESS_TEAM_DOMAIN).setAudience(overrides.aud??env.CF_ACCESS_AUD).setSubject(overrides.sub??'signed-owner').setIssuedAt().setExpirationTime(overrides.exp??'1h').sign(key);}
const good=await token(),auth=(request,e)=>verifyAccess(request,e,jwks);
const request=(path='/',{jwt=good,method='GET',body,origin=env.APP_ORIGIN,account='signed-owner',url=env.APP_ORIGIN}={})=>new Request(url+path,{method,headers:{...(jwt?{'cf-access-jwt-assertion':jwt}:{}),origin,'Content-Type':'application/json','X-Geotech-Client':'workspace-v1','X-Geotech-Account':account},...(body!==undefined?{body:JSON.stringify(body)}:{})});
function DB(){const sqlite=new DatabaseSync(':memory:');for(const filename of ['0001_workspace.sql','0002_workspace_chunks.sql'])sqlite.exec(readFileSync(new URL('../cloud/migrations/'+filename,import.meta.url),'utf8'));
 const adapter={sqlite,failBatch:false,prepare(sql){return {bind(...args){return {sql,args,async first(){return sqlite.prepare(sql).get(...args)??null;},async run(){return {meta:{changes:sqlite.prepare(sql).run(...args).changes}};}};}};},async batch(statements){sqlite.exec('BEGIN IMMEDIATE');try{const results=statements.map((item,index)=>{if(adapter.failBatch&&index===1)throw Error('injected database failure');const statement=sqlite.prepare(item.sql);return statement.columns().length?{results:statement.all(...item.args),meta:{changes:0}}:{results:[],meta:{changes:statement.run(...item.args).changes}};});sqlite.exec('COMMIT');return results;}catch(error){sqlite.exec('ROLLBACK');throw error;}}};return adapter;}

function fixture(){const db=DB(),assets={calls:0,async fetch(){this.calls++;return new Response('private app',{headers:{'Content-Type':'text/html'}});}};return {db,assets,env:{...env,DB:db,ASSETS:assets},worker:createWorker({authenticate:auth})};}
const records={experiment:null,library:null,worksheet:null};
test('signed issuer, audience, expiry, algorithm and allowed owner are required',async()=>{assert.equal((await auth(request(),env)).id,'signed-owner');for(const bad of [await token({aud:'drone-aud'}),await token({iss:'https://evil.cloudflareaccess.com'}),await token({email:'other@example.com'}),await token({exp:1}),await token({},other.privateKey),'not-a-jwt'])await assert.rejects(()=>auth(request('/',{jwt:bad}),env));});
test('missing config and JWT fail closed for BOTH static assets and API',async()=>{const f=fixture();for(const path of ['/','/index.html','/api/workspace']){assert.equal((await f.worker.fetch(request(path,{jwt:null}),f.env)).status,403);for(const key of ['CF_ACCESS_TEAM_DOMAIN','CF_ACCESS_AUD','ALLOWED_EMAILS','APP_ORIGIN'])assert.equal((await f.worker.fetch(request(path),{...f.env,[key]:''})).status,403);}assert.equal(f.assets.calls,0);});
test('preview or direct alternate host cannot bypass canonical origin',async()=>{const f=fixture();assert.equal((await f.worker.fetch(request('/',{url:'https://preview.workers.dev'}),f.env)).status,403);assert.equal(f.assets.calls,0);});
test('authenticated assets keep original content type and use private no-store',async()=>{const f=fixture(),r=await f.worker.fetch(request(),f.env);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'text/html');assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal(f.assets.calls,1);});
test('first create and subsequent updates are atomic revision compare-and-swap',async()=>{const f=fixture(),call=(revision)=>f.worker.fetch(request('/api/workspace',{method:'PUT',body:{revision,records}}),f.env);assert.equal((await call(0)).status,200);const competing=await Promise.all([call(1),call(1)]);assert.deepEqual(competing.map(r=>r.status).sort(),[200,409]);const state=await(await f.worker.fetch(request('/api/workspace'),f.env)).json();assert.equal(state.revision,2);assert.equal(state.user.id,'signed-owner');});
test('CSRF, account switch and client supplied user identifiers cannot change any row',async()=>{const f=fixture();for(const options of [{origin:'https://evil.example'},{account:'another-user'},{body:{revision:0,records,user_id:'another-user'}}]){const r=await f.worker.fetch(request('/api/workspace',{method:'PUT',body:{revision:0,records},...options}),f.env);assert.ok([400,403,409].includes(r.status));}assert.equal(f.db.sqlite.prepare('SELECT count(*) AS n FROM workspaces').get().n,0);});
test('payload size, malformed JSON schemas and prototype keys are rejected',async()=>{const f=fixture();for(const body of [{revision:-1,records},{revision:0,records:{extra:null,...records}},{revision:0,records:{...records,experiment:'{"version":1,"state":{"active":"soil","data":{},"baselines":{},"__proto__":{}}}'}}])assert.equal((await f.worker.fetch(request('/api/workspace',{method:'PUT',body}),f.env)).status,400);assert.equal((await f.worker.fetch(request('/api/workspace',{method:'PUT',body:{revision:0,records:{...records,library:'x'.repeat(7*1024*1024)}}}),f.env)).status,413);});
test('user isolation is based only on the verified subject',async()=>{const f=fixture();await f.worker.fetch(request('/api/workspace',{method:'PUT',body:{revision:0,records}}),f.env);const second=await token({sub:'new-device-account'}),r=await f.worker.fetch(request('/api/workspace',{jwt:second}),f.env);assert.equal((await r.json()).revision,0);});
test('large legacy libraries cross chunk boundaries losslessly and a losing CAS leaves no dangling chunks',async()=>{const f=fixture();const large={...records,library:JSON.stringify({version:1,examples:[{text:'가나다😀'.repeat(180000)}],progress:{},activeRoute:null})};const save=revision=>f.worker.fetch(request('/api/workspace',{method:'PUT',body:{revision,records:large}}),f.env);assert.equal((await save(0)).status,200);const before=f.db.sqlite.prepare('SELECT count(*) AS n, max(length(payload)) AS size FROM workspace_chunks').get();assert.ok(before.n>1);assert.ok(before.size<=512*1024);assert.equal((await save(0)).status,409);assert.equal(f.db.sqlite.prepare('SELECT count(*) AS n FROM workspace_chunks').get().n,before.n);const loaded=await(await f.worker.fetch(request('/api/workspace'),f.env)).json();assert.deepEqual(loaded.records,large);assert.equal((await save(1)).status,200);assert.equal(f.db.sqlite.prepare('SELECT count(DISTINCT version_id) AS n FROM workspace_chunks').get().n,1);});
test('database batch failure rolls back pointer and all partially written chunks',async()=>{const f=fixture();assert.equal((await f.worker.fetch(request('/api/workspace',{method:'PUT',body:{revision:0,records}}),f.env)).status,200);const before=f.db.sqlite.prepare('SELECT revision, version_id FROM workspaces').get();f.db.failBatch=true;assert.equal((await f.worker.fetch(request('/api/workspace',{method:'PUT',body:{revision:1,records}}),f.env)).status,503);assert.deepEqual(f.db.sqlite.prepare('SELECT revision, version_id FROM workspaces').get(),before);assert.equal(f.db.sqlite.prepare('SELECT count(DISTINCT version_id) AS n FROM workspace_chunks').get().n,1);});
test('inline workspaces remain readable after chunk migration',async()=>{const f=fixture();f.db.sqlite.prepare('INSERT INTO workspaces(user_id,revision,records,updated_at) VALUES (?,1,?,?)').run('signed-owner',JSON.stringify(records),'2026-09-22T00:00:00Z');const loaded=await(await f.worker.fetch(request('/api/workspace'),f.env)).json();assert.deepEqual(loaded.records,records);assert.equal(loaded.revision,1);});
test('a missing stored chunk fails closed instead of returning a partial workspace',async()=>{const f=fixture();await f.worker.fetch(request('/api/workspace',{method:'PUT',body:{revision:0,records}}),f.env);f.db.sqlite.exec('DELETE FROM workspace_chunks');assert.equal((await f.worker.fetch(request('/api/workspace'),f.env)).status,503);});
