import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import collectSources from '../source-manifest.cjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=f=>readFileSync(path.join(root,'src',f),'utf8'),manifest=collectSources(root);
const source=manifest.scriptFiles.filter(f=>f!=='app.js').map(f=>read(f).replace(/^export /gm,'')).join('\n');
const app=read('app.js'),core=app.slice(app.indexOf('const coreDefaults='),app.indexOf('\nconst defaults='));
const {service,catalog,snapshot,inspect}=vm.runInNewContext(source+'\n'+core+`\nconst defaults={...coreDefaults,...Object.fromEntries(ExtensionLabs.map(l=>[l.key,l.defaults]))},modules={...coreModules,...Object.fromEntries(ExtensionLabs.map(l=>[l.key,l.meta]))};
const catalog=makeLearningSessionCatalog({modules,defaults,labs:ExtensionLabs});
const service=createLearningSessionFiles({catalog,validate:(key,d,q)=>labRegistry[key]?labRegistry[key].compute(d,q):key==='foundation'?Mechanics.foundationForQuestion(d,q):key==='stress'?Mechanics.effectiveStress(d):q==='sedimentation'?Sedimentation.analyze(d):Soil.classify({points:d.mode==='raw'?d.points:d.mode==='mass'?SoilInputs.retainedToPassing(d.massRows).points:SoilInputs.generateCurve({fines:d.fines,gravelShare:d.gravelShare,gradation:d.gradation==='well'?'broad':d.gradation}),ll:d.ll,pl:d.pl,np:d.np,organic:d.organic})});
({service,catalog,snapshot:(module='foundation',question=modules[module].questions[0][0])=>({module,question,current:structuredClone(defaults[module]),baseline:structuredClone(defaults[module]),compare:false}),inspect:s=>service.inspect(s)})`,{structuredClone,performance,TextEncoder});
const copy=x=>JSON.parse(JSON.stringify(x));
const record=s=>({format:service.format,version:service.version,experiment:s});
const parse=r=>service.parse(JSON.stringify(r));
const rejected=(r,pattern)=>assert.throws(()=>parse(r),pattern);

test('every registered question default round-trips in its current catalog',()=>{for(const key of Object.keys(catalog))for(const[q]of catalog[key].questions){const s=snapshot(key,q),saved=service.serialize(s),restored=service.parse(saved.text);assert.deepEqual(copy(restored.snapshot),copy(s),`${key}/${q}`);assert.ok(restored.preview.name);assert.equal(restored.preview.rows.length,Object.keys(s.current).length);}});
test('the JSON contains only one experiment inputs, question and comparison',()=>{const r=JSON.parse(service.serialize(snapshot()).text);assert.deepEqual(Object.keys(r),['format','version','experiment']);assert.deepEqual(Object.keys(r.experiment),['module','question','current','baseline','compare']);assert.ok(!/results|history|baselineNames|timestamp/.test(service.serialize(snapshot()).text));});
test('current and baseline remain distinct and do not alias caller data',()=>{const s=snapshot();s.current.width=5;s.baseline.width=2;s.compare=true;const r=service.parse(service.serialize(s).text);assert.equal(r.snapshot.current.width,5);assert.equal(r.snapshot.baseline.width,2);s.current.width=3;assert.equal(r.snapshot.current.width,5);});
test('unknown root, experiment and input keys are rejected',()=>{for(const mutate of [r=>r.extra=1,r=>r.experiment.extra=1,r=>r.experiment.current.extra=1,r=>r.experiment.baseline.extra=1]){const r=record(snapshot());mutate(r);rejected(r,/알 수 없는/);}});
test('missing keys are rejected rather than silently repaired with defaults',()=>{const r=record(snapshot());delete r.experiment.baseline.width;rejected(r,/필요한 항목/);});
test('wrong format and version are rejected',()=>{for(const [key,value]of [['version',service.version+1],['version','1'],['format','other']]){const r=record(snapshot());r[key]=value;rejected(r,/버전/);}});
test('unknown module including inherited keys and cross-module question are rejected',()=>{for(const module of ['other','__proto__','constructor','toString']){const r=record(snapshot());r.experiment.module=module;rejected(r,/실험/);}const r=record(snapshot());r.experiment.question='downdrag';rejected(r,/질문/);});
test('invalid JSON, oversized Unicode JSON and excessive depth are rejected',()=>{assert.throws(()=>service.parse('{'),/JSON/);assert.throws(()=>service.parse('가'.repeat(service.maxBytes/2)),/256/);const r=record(snapshot());r.experiment.current.width={a:{a:{a:{a:{a:{a:{a:{a:{a:1}}}}}}}}};rejected(r,/깊/);});
test('BOM-prefixed JSON exported by other editors is accepted',()=>{assert.equal(service.parse('\uFEFF'+service.serialize(snapshot()).text).snapshot.module,'foundation');});
test('NaN and Infinity are rejected before JSON can silently replace them with null',()=>{for(const bad of [NaN,Infinity,-Infinity]){const s=snapshot();s.current.width=bad;assert.throws(()=>service.serialize(s),/NaN|무한대/);}assert.throws(()=>service.parse(service.serialize(snapshot()).text.replace('"width": 3','"width": 1e999')),/무한대/);});
test('numeric strings, malformed booleans and unknown enum choices are rejected',()=>{for(const [field,value]of [['width','3'],['loadMode','<img onerror=alert(1)>']]){const s=snapshot();s.current[field]=value;assert.throws(()=>inspect(s),/형식|선택값/);}const s=snapshot('soil');s.current.np='true';assert.throws(()=>inspect(s),/참\/거짓/);const r=record(snapshot());r.experiment.compare=1;rejected(r,/비교/);});
test('prototype pollution properties are never accepted at any depth',()=>{const json=service.serialize(snapshot()).text.replace('"width": 3','"__proto__": {"polluted":true}, "width": 3');assert.throws(()=>service.parse(json),/허용되지/);assert.equal({}.polluted,undefined);});
test('active-question physics blocks an invalid value but inactive numeric state is preserved',()=>{const s=snapshot('foundation','pressure');s.current.phi=null;assert.equal(inspect(s).snapshot.current.phi,null);s.question='bearing';assert.throws(()=>inspect(s),/현재 입력/);});
test('invalid baseline blocks enabled comparison and warns when comparison is off',()=>{const s=snapshot();s.baseline.width=0;s.compare=true;assert.throws(()=>inspect(s),/비교 기준/);s.compare=false;const r=inspect(s);assert.equal(r.warnings.length,1);assert.equal(r.snapshot.baseline.width,0);assert.equal(r.snapshot.compare,false);});
test('a thrown or missing model result is a safe validation failure',()=>{const unsafe=vm.runInNewContext(read('learning-session-files.js')+'\ncreateLearningSessionFiles',{TextEncoder})({catalog:copy(catalog),validate:()=>{throw Error('private stack')}});assert.throws(()=>unsafe.serialize(snapshot()),/입력을 확인하지/);});
test('hidden constants cannot be changed through an imported file',()=>{for(const [key,field]of [['stress','gammaW'],['consolidation','gammaW'],['pile-lateral','elements'],['foundation','embedment'],['foundation','poisson']]){const s=snapshot(key);s.current[field]=9999;assert.throws(()=>inspect(s),/고정값/);}});
test('raw soil and retained-mass rows use exact field schemas and size limits',()=>{const s=snapshot('soil');s.current.points=[{size:.075,passing:8},{size:4.75,passing:100}];s.current.massRows=[{size:4.75,mass:0},{size:.075,mass:920},{size:null,mass:80}];assert.equal(inspect(s).snapshot.current.massRows[2].size,null);s.current.points[0].secret=1;assert.throws(()=>inspect(s),/알 수 없는/);delete s.current.points[0].secret;s.current.points=Array.from({length:513},()=>({size:1,passing:50}));assert.throws(()=>inspect(s),/512/);});
test('inactive raw blank cells survive without injecting strings',()=>{const s=snapshot('soil');s.current.points=[{size:.075,passing:null}];s.current.massRows=[{size:null,mass:null}];assert.equal(inspect(s).snapshot.current.points[0].passing,null);s.current.points[0].passing='<script>';assert.throws(()=>inspect(s),/유한한 숫자/);});
test('preview uses local labels, names and units and includes both value columns',()=>{const r=inspect(snapshot());assert.equal(r.preview.name,'얕은기초');assert.equal(r.preview.rows.find(r=>r.key==='width').unit,'m');assert.equal(r.preview.rows.find(r=>r.key==='modulus').current,25000);assert.equal(r.preview.rows.find(r=>r.key==='modulus').unit,'kPa');});
test('human preview rounds display without changing saved precision or choice values',()=>{const s=snapshot(),r=inspect(s);assert.equal(r.preview.rows.find(r=>r.key==='loadMode').currentDisplay,'총하중 Q 고정');assert.equal(r.preview.rows.find(r=>r.key==='pressure').currentDisplay,'133.3333');assert.equal(JSON.parse(service.serialize(s).text).experiment.current.pressure,1200/9);});

test('published version 1 files preserve old question and both input sets after known additions',()=>{for(const key of ['earth-pressure','layered-settlement','pile-axial']){const text=readFileSync(new URL('./fixtures/session-v1-'+key+'.json',import.meta.url),'utf8'),old=JSON.parse(text),restored=service.parse(text);assert.equal(restored.snapshot.question,old.experiment.question);for(const side of ['current','baseline'])for(const [field,value]of Object.entries(old.experiment[side]))assert.deepEqual(copy(restored.snapshot[side][field]),value);for(const [field,value]of Object.entries(catalog[key].defaults))if(!(field in old.experiment.current))assert.deepEqual(copy(restored.snapshot.current[field]),copy(value));const saved=JSON.parse(service.serialize(restored.snapshot).text);assert.equal(saved.version,service.version);}});
test('legacy migration refuses missing old values and fields falsely claimed to be old',()=>{for(const key of ['earth-pressure','layered-settlement','pile-axial']){const fixture=JSON.parse(readFileSync(new URL('./fixtures/session-v1-'+key+'.json',import.meta.url),'utf8'));for(const kind of ['missing','unknown']){const r=copy(fixture);if(kind==='missing')delete r.experiment.current[Object.keys(r.experiment.current)[0]];else r.experiment.current.unrecognized=1;rejected(r,/필요한 항목|알 수 없는/);}}});
test('legacy records cannot select a question introduced after their schema',()=>{const r=JSON.parse(readFileSync(new URL('./fixtures/session-v1-earth-pressure.json',import.meta.url),'utf8'));r.experiment.question='cohesive';rejected(r,/이전 파일 버전/);});
test('unchanged modules version 1 still require every original field',()=>{const r=record(snapshot('foundation'));r.version=1;assert.equal(parse(r).snapshot.current.width,3);delete r.experiment.current.width;rejected(r,/필요한 항목/);});


test('published slope version 1 and 2 migrate only added circular fields and preserve both old states',()=>{for(const version of [1,2]){const text=readFileSync(new URL('./fixtures/session-v'+version+'-slope.json',import.meta.url),'utf8'),old=JSON.parse(text),r=service.parse(text);for(const side of ['current','baseline'])for(const[field,value]of Object.entries(old.experiment[side]))assert.deepEqual(copy(r.snapshot[side][field]),value);assert.equal(r.snapshot.question,'infinite');assert.equal(r.snapshot.compare,true);assert.equal(r.snapshot.current.circularHeight,catalog.slope.defaults.circularHeight);assert.match(r.warnings[0],/이전 버전/);assert.equal(JSON.parse(service.serialize(r.snapshot).text).version,service.version);}});
test('older slope schema refuses extra fields, omitted original inputs and new questions',()=>{for(const version of [1,2])for(const mutation of ['missing','extra','question']){const r=JSON.parse(readFileSync(new URL('./fixtures/session-v'+version+'-slope.json',import.meta.url),'utf8'));if(mutation==='missing')delete r.experiment.baseline.gamma;else if(mutation==='extra')r.experiment.current.circularHeight=8;else r.experiment.question='circular';rejected(r,/항목|이전 파일 버전/);}});
test('version 2 unchanged expanded modules stay strict and retain their later questions',()=>{for(const[key,q]of [['earth-pressure','cohesive'],['pile-axial','evidence'],['layered-settlement','footing']]){const r=record(snapshot(key,q));r.version=2;assert.equal(parse(r).snapshot.question,q);delete r.experiment.current[Object.keys(r.experiment.current)[0]];rejected(r,/항목/);}});
test('current circular files require complete inputs and preserve the chosen slice',()=>{const s=snapshot('slope','circular');s.current.circularSlicePercent=72;const r=service.parse(service.serialize(s).text);assert.equal(r.snapshot.current.circularSlicePercent,72);const f=record(s);delete f.experiment.current.circularHeight;rejected(f,/항목/);});

test('raw input files cannot bypass the supported less-than-75 mm fraction',()=>{const s=snapshot('soil','gradation');s.current.mode='raw';s.current.points=[{size:.075,passing:10},{size:4.75,passing:30},{size:63,passing:50},{size:150,passing:100}];assert.throws(()=>inspect(s),/75 mm/);});

const sedimentFields=['sedimentDepthCm','sedimentTimeMinutes','sedimentGs','sedimentTemperature'];
test('soil versions 1 through 3 migrate only new sedimentation fields',()=>{for(const version of [1,2,3]){const old=snapshot('soil','plasticity');old.current.ll=55;old.baseline.ll=32;old.compare=true;for(const side of ['current','baseline'])for(const f of sedimentFields)delete old[side][f];const r=parse({format:service.format,version,experiment:old});assert.equal(r.snapshot.question,'plasticity');assert.equal(r.snapshot.current.ll,55);assert.equal(r.snapshot.baseline.ll,32);assert.equal(r.snapshot.current.sedimentTimeMinutes,10);assert.match(r.warnings[0],/이전 버전/);assert.equal(JSON.parse(service.serialize(r.snapshot).text).version,service.version);}});
test('legacy soil files reject new questions and missing original data',()=>{for(const version of [1,2,3]){const old=snapshot('soil','sedimentation');for(const side of ['current','baseline'])for(const f of sedimentFields)delete old[side][f];rejected({format:service.format,version,experiment:old},/이전 파일 버전/);old.question='gradation';delete old.current.ll;rejected({format:service.format,version,experiment:old},/필요한 항목/);}});
test('sedimentation files preserve independent inactive classification inputs',()=>{const s=snapshot('soil','sedimentation');s.current.ll=-4;s.current.fines=null;assert.equal(inspect(s).snapshot.current.ll,-4);s.question='plasticity';assert.throws(()=>inspect(s),/현재 입력/);});
test('classification files preserve an inactive empty sedimentation value',()=>{const s=snapshot('soil');s.current.sedimentTimeMinutes=null;assert.equal(inspect(s).snapshot.current.sedimentTimeMinutes,null);s.question='sedimentation';assert.throws(()=>inspect(s),/현재 입력/);});
test('version 4 soil shape requires complete current and baseline inputs',()=>{const r=record(snapshot('soil'));delete r.experiment.current.sedimentGs;rejected(r,/필요한 항목/);});
test('published version 4 soil files preserve their complete sedimentation inputs',()=>{const s=snapshot('soil','sedimentation');s.current.sedimentTimeMinutes=30;s.baseline.sedimentTimeMinutes=5;const r=parse({format:service.format,version:4,experiment:s});assert.deepEqual(copy(r.snapshot),copy(s));assert.equal(r.warnings.length,0);});
