import test from 'node:test';
import {RectangularStress} from '../src/rectangular-stress.mjs';
import assert from 'node:assert/strict';
import {StrengthStress as S} from '../src/strength-stress.mjs';
const near=(a,b,t=1e-9)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b} (tol ${t})`);
const relative=(a,b,t=1e-6)=>near(a,b,t*Math.max(1,Math.abs(b)));
function diskReference({q,a,z,r}) { // Independent 2D midpoint integral about the load centre.
 let sum=0;const nr=240,nt=720,dr=a/nr,dt=2*Math.PI/nt;
 for(let i=0;i<nr;i++){const rho=(i+.5)*dr;for(let j=0;j<nt;j++){const theta=(j+.5)*dt,rr=Math.hypot(r-rho*Math.cos(theta),rho*Math.sin(theta));sum+=3*q*z**3/(2*Math.PI*(rr*rr+z*z)**2.5)*rho*dr*dt;}}
 return sum;
}
test('point-load hand calculation on axis and off axis',()=>{near(S.pointStress({load:100,z:2,r:0}).stress,300/(8*Math.PI));near(S.pointStress({load:100,z:2,r:2}).stress,300*8/(2*Math.PI*8**2.5));});
test('point load scales with load and inverse square length',()=>{const a=S.pointStress({load:100,z:2,r:3}),b=S.pointStress({load:200,z:2,r:3}),c=S.pointStress({load:100,z:4,r:6});near(b.stress,2*a.stress);near(c.stress,a.stress/4);near(c.influence,a.influence);});
test('point-load origin is singular, unloaded origin is zero and unloaded surface away is zero',()=>{assert.equal(S.pointStress({load:100,z:0,r:0}).valid,false);near(S.pointStress({load:0,z:0,r:0}).stress,0);near(S.pointStress({load:100,z:0,r:1}).stress,0);});
test('point load rejects negative lengths, coercion and infinities',()=>{for(const v of [{z:-1},{r:-1},{load:-1},{z:'2'},{load:Infinity},null])assert.equal(S.pointStress(v).valid,false);});
test('circular axial solution and geometric scale invariance',()=>{const a=S.circularStress({pressure:100,radius:2,z:2,r:0});near(a.stress,100*(1-1/2**1.5));near(S.circularStress({pressure:100,radius:4,z:4,r:0}).stress,a.stress);});
test('circular surface limits inside, on boundary and outside',()=>{near(S.circularStress({pressure:100,radius:2,z:0,r:1}).stress,100);near(S.circularStress({pressure:100,radius:2,z:0,r:2}).stress,50);near(S.circularStress({pressure:100,radius:2,z:0,r:3}).stress,0);});
test('circular off-axis integral agrees with independent area integration',()=>{for(const r of [.5,2,3]){const a=S.circularStress({pressure:100,radius:2,z:1.5,r});assert.equal(a.valid,true);relative(a.stress,diskReference({q:100,a:2,z:1.5,r}),2e-5);assert.equal(a.quadrature.converged,true);}});
test('circular off-axis dimensionless influence invariant and linear in pressure',()=>{const a=S.circularStress({pressure:80,radius:2,z:3,r:1}),b=S.circularStress({pressure:160,radius:4,z:6,r:2});assert.ok(a.valid&&b.valid);relative(b.influence,a.influence,1e-8);relative(b.stress,2*a.stress,1e-8);});
test('circular near surface tends to the proper limits',()=>{const inside=S.circularStress({pressure:100,radius:2,z:.0001,r:1}),edge=S.circularStress({pressure:100,radius:2,z:.0001,r:2}),outside=S.circularStress({pressure:100,radius:2,z:.0001,r:3});assert.ok(inside.valid&&edge.valid&&outside.valid);near(inside.stress,100,.001);near(edge.stress,50,.01);near(outside.stress,0,.001);});
test('far circular load converges to its equivalent point load',()=>{const q=100,a=2,z=100,r=20,c=S.circularStress({pressure:q,radius:a,z,r}),p=S.pointStress({load:q*Math.PI*a*a,z,r});relative(c.stress,p.stress,.001);});
test('circular stress rejects nonphysical area and pressure',()=>{for(const v of [{radius:0},{pressure:-1},{z:-1},{r:-1},{pressure:'100'},null])assert.equal(S.circularStress(v).valid,false);});
test('stress-field Q versus q modes change area relationships correctly',()=>{const f1=S.stressField({load:1000,radius:1,depth:3,offset:0,loadMode:'force'}),f2=S.stressField({load:1000,radius:2,depth:3,offset:0,loadMode:'force'}),p1=S.stressField({pressure:100,radius:1,depth:3,offset:0,loadMode:'pressure'}),p2=S.stressField({pressure:100,radius:2,depth:3,offset:0,loadMode:'pressure'});assert.ok(f1.valid&&f2.valid&&p1.valid&&p2.valid);near(f2.pressure,f1.pressure/4);near(f2.load,f1.load);assert.ok(f2.stress<f1.stress);near(p2.load,4*p1.load);near(p2.pressure,p1.pressure);assert.ok(p2.stress>p1.stress);});
test('stress-field computation omits singular sample but marks it and keeps real observations',()=>{const r=S.stressField({load:1000,depth:3,offset:0},'point');assert.equal(r.valid,true);assert.equal(r.profile[0].stress,null);assert.equal(r.profile[0].singular,true);assert.equal(r.cells.length,576);near(r.stress,S.pointStress({load:1000,z:3,r:0}).stress);});
test('irrelevant radius and inactive load do not invalidate selected stress experiment',()=>{assert.equal(S.stressField({load:1000,radius:NaN,depth:3,offset:1},'point').valid,true);assert.equal(S.stressField({load:NaN,pressure:100,radius:2,depth:3,offset:1,loadMode:'pressure'}).valid,true);});
test('Mohr circle hand example and plane stress transformation',()=>{const r=S.mohrCoulomb({cohesion:0,phi:30,sigma3:100,deviator:200,angle:60});assert.equal(r.valid,true);near(r.sigma1,300);near(r.center,200);near(r.radius,100);near(r.normal,150);near(r.shear,50*Math.sqrt(3));near(r.deviatorFailure,200);assert.equal(r.state,'tangent');});
test('failure circle is tangent to Mohr-Coulomb envelope with exact Euclidean geometry',()=>{for(const phi of [0,10,30,45,60]){const r=S.mohrCoulomb({cohesion:17,phi,sigma3:80,deviator:100});near(r.tangent.shear,17+r.tangent.normal*Math.tan(phi*Math.PI/180),1e-8);near(Math.hypot(r.tangent.normal-r.failureCenter,r.tangent.shear),r.failureRadius,1e-8);near((r.failureCenter*Math.sin(phi*Math.PI/180)+17*Math.cos(phi*Math.PI/180)),r.failureRadius,1e-8);}});
test('zero friction gives qf=2c independently of confinement',()=>{const a=S.mohrCoulomb({cohesion:30,phi:0,sigma3:10}),b=S.mohrCoulomb({cohesion:30,phi:0,sigma3:300});near(a.deviatorFailure,60);near(b.deviatorFailure,60);});
test('Mohr circle under and over the envelope are explicit states',()=>{assert.equal(S.mohrCoulomb({cohesion:0,phi:30,sigma3:100,deviator:100}).state,'inside');const r=S.mohrCoulomb({cohesion:0,phi:30,sigma3:100,deviator:300});assert.equal(r.state,'outside');assert.ok(r.warnings.length);});
test('plane rotation preserves circle radius and principal endpoint stresses',()=>{for(const a of [0,20,45,60,90]){const r=S.mohrCoulomb({angle:a});near((r.normal-r.center)**2+r.shear**2,r.radius**2,1e-8);}near(S.mohrCoulomb({angle:0}).normal,220);near(S.mohrCoulomb({angle:90}).normal,100);});
test('strength validation does not coerce or accept tensile confinement',()=>{for(const v of [{cohesion:-1},{phi:90},{sigma3:-1},{deviator:-1},{angle:100},{phi:'30'},null])assert.equal(S.mohrCoulomb(v).valid,false);});
test('specified secant point converts strain percent and separates stiffness from strength',()=>{near(S.secantPoint({deviator:120,axialStrain:.5}).secantModulus,24000);const a=S.strengthLab({axialStrain:.5},'stiffness'),b=S.strengthLab({axialStrain:1},'stiffness');near(b.secant.secantModulus,a.secant.secantModulus/2);near(b.deviatorFailure,a.deviatorFailure);assert.equal(S.secantPoint({axialStrain:0}).valid,false);});
test('unrelated question inputs do not block Mohr or stiffness results',()=>{assert.equal(S.strengthLab({axialStrain:NaN},'mohr').valid,true);assert.equal(S.strengthLab({angle:NaN,axialStrain:.5},'stiffness').valid,true);assert.equal(S.strengthLab({angle:null},'mohr').valid,false);});
test('CU pore-pressure transformation translates circles without changing radius or deviator',()=>{const r=S.triaxial({cell:200,deviator:180,pore:80},'CU');assert.equal(r.valid,true);near(r.sigma1,380);near(r.sigma3,200);near(r.sigma1Effective,300);near(r.sigma3Effective,120);near(r.center-r.centerEffective,80);near(r.radius,90);near(r.sigma1Effective-r.sigma3Effective,r.deviator);near(r.meanTotal,260);near(r.meanEffective,180);});
test('drained CD has zero excess pressure but nonzero imposed back pressure',()=>{const r=S.triaxial({cell:200,deviator:180,backPressure:50,pore:NaN},'CD');assert.equal(r.valid,true);near(r.u,50);near(r.excessPorePressure,0);near(r.sigma3Effective,150);});
test('UU does not invent effective stresses from unknown pore pressure',()=>{const r=S.triaxial({cell:200,deviator:180,pore:NaN,backPressure:NaN},'UU');assert.equal(r.valid,true);assert.equal(r.u,null);assert.equal(r.sigma1Effective,null);assert.equal(r.meanEffective,null);assert.equal(r.undrainedStrength,null);near(S.triaxial({cell:200,deviator:180,atFailure:true},'UU').undrainedStrength,90);});
test('CU supplied failure point gives conditional su but CD does not rename tauMax as su',()=>{near(S.triaxial({atFailure:true},'CU').undrainedStrength,90);assert.equal(S.triaxial({atFailure:true},'CD').undrainedStrength,null);});
test('inconsistent pore pressure and invalid measurement modes are rejected',()=>{assert.equal(S.triaxial({cell:50,pore:80},'CU').valid,false);assert.equal(S.triaxial({backPressure:NaN},'CD').valid,false);assert.equal(S.triaxial({pore:NaN},'CU').valid,false);assert.equal(S.triaxial({},'XX').valid,false);assert.equal(S.triaxial({atFailure:'yes'},'UU').valid,false);});

// Descriptor hooks and active-field validation are part of the learning-state contract.
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const uiContext={StrengthStress:S,RectangularStress,fmt:(v,d=1)=>Number(v).toFixed(d),esc:String,metric:()=>'<div>metric</div>',fieldControl:(key)=>`<input data-field="${key}">`,numericRow:(key)=>`<input data-field="${key}">`,svgWrap:(html)=>`<svg>${html}</svg>`};
const descriptors=vm.runInNewContext(readFileSync(new URL('../src/labs/strength-stress-labs.js',import.meta.url),'utf8')+'\nStrengthStressLabs;',uiContext);
test('all eight descriptor questions render finite charts and expose active fields',()=>{let count=0;for(const lab of descriptors){for(const [question]of lab.meta.questions){const d={...lab.defaults},r=lab.compute(d,question);assert.equal(r.valid,true,lab.key+'/'+question);const ui=lab.render({data:d,result:r,baseline:r,question});for(const k of ['title','chart','results','explanation','theory','method'])assert.ok(ui[k],lab.key+'/'+question+'/'+k);assert.equal(/NaN|undefined/.test(ui.chart),false);const controls=lab.controls(d,question);for(const f of lab.activeFields(d,question))assert.ok(controls.includes(`data-field="${f}"`),lab.key+'/'+question+'/'+f);count++;}}assert.equal(count,8);});
test('question-specific bound lists ignore invalid values not used by current question',()=>{for(const lab of descriptors){for(const [question]of lab.meta.questions){const d={...lab.defaults},active=lab.activeFields(d,question);for(const f of Object.keys(lab.bounds))if(!active.includes(f))d[f]=NaN;assert.equal(lab.compute(d,question).valid,true,lab.key+'/'+question);}}});
test('Q to q and back preserves physical load even outside initial slider maxima',()=>{const lab=descriptors.find(l=>l.key==='stress-spread');for(const radius of [.5,1,3]){const original={...lab.defaults,radius,load:3000},before=lab.compute(original,'circular'),toPressure={...original,loadMode:'pressure'};lab.onFieldChange(toPressure,'loadMode',original);const after=lab.compute(toPressure,'circular');assert.ok(after.valid);near(after.load,before.load,1e-8);near(after.pressure,before.pressure,1e-8);near(after.stress,before.stress,1e-8);const toForce={...toPressure,loadMode:'force'};lab.onFieldChange(toForce,'loadMode',toPressure);near(lab.compute(toForce,'circular').load,3000,1e-8);}});
test('CD failure-point wording does not imply missing failure designation or undrained strength',()=>{const lab=descriptors.find(l=>l.key==='triaxial-drainage'),d={...lab.defaults,atFailure:true},r=lab.compute(d,'CD'),ui=lab.render({data:d,result:r,baseline:null,question:'CD'});assert.match(ui.theory,/파괴 시점으로 지정해도/);assert.equal(r.undrainedStrength,null);});
