import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import collectSources from '../source-manifest.cjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=f=>readFileSync(path.join(root,'src',f),'utf8'),manifest=collectSources(root),app=read('app.js'),core=app.slice(app.indexOf('const coreDefaults='),app.indexOf('\nconst defaults='));
const source=manifest.scriptFiles.filter(f=>f!=='app.js').map(f=>read(f).replace(/^export /gm,'')).join('\n')+'\n'+core;
function fixture(){return vm.runInNewContext('const structuredClone=v=>JSON.parse(JSON.stringify(v));\n'+source+`
const defaults={...coreDefaults,...Object.fromEntries(ExtensionLabs.map(l=>[l.key,l.defaults]))},modules={...coreModules,...Object.fromEntries(ExtensionLabs.map(l=>[l.key,l.meta]))};
const keys=Object.keys(modules),each=fn=>Object.fromEntries(keys.map(k=>[k,fn(k)]));
let state={bearingViewed:false,active:'soil',data:structuredClone(defaults),baselines:structuredClone(defaults),question:each(k=>modules[k].questions[0][0]),compare:each(()=>false),baselineNames:each(()=>'기본 예제')};
const catalog=makeLearningSessionCatalog({modules,defaults,labs:ExtensionLabs}),service=createLearningSessionFiles({catalog,validate:()=>({valid:true})});
const rows=new Map(),localStorage={getItem:k=>rows.get(k)??null,setItem:(k,v)=>rows.set(k,v),removeItem:k=>rows.delete(k)};
const store=createLearningLibraryStore({service,storage:localStorage}),library={store,refresh:()=>store.load()};let worksheetInput=FoundationWorksheet.example();const worksheet={getInput:()=>structuredClone(worksheetInput),setInput:input=>{worksheetInput=structuredClone(input);}};
const adapter=createWholeWorkspaceAdapter({getState:()=>structuredClone(state),setState:s=>{state=structuredClone(s);},library,worksheet,catalog});
({adapter,store,worksheet,updateExperiment:()=>{state.active='foundation';state.data.foundation.width=4;state.baselines.foundation.width=2;state.compare.foundation=true;state.baselineNames.foundation='개인 기준';state.data.foundation.phi=null;},snapshot:()=>({module:'foundation',question:'pressure',current:structuredClone(defaults.foundation),baseline:structuredClone(defaults.foundation),compare:false}),get:()=>({state,worksheetInput,library:store.load()}),exportFile:()=>WorkspaceFiles.serialize(adapter.capture()),importFile:text=>adapter.apply(WorkspaceFiles.parse(text))})`,{structuredClone,performance,TextEncoder});}
const plain=x=>JSON.parse(JSON.stringify(x));
test('all registered experiment inputs, library examples/progress and worksheet draft restore together',()=>{const a=fixture();a.updateExperiment();a.store.save('독립 기초 예제',a.snapshot());a.store.openRoute('water',1);a.store.mark('water',1,true);const input=a.worksheet.getInput();input.meta.project='개인 프로젝트';input.geometry.width=null;a.worksheet.setInput(input);const backup=a.exportFile(),b=fixture();b.importFile(backup);assert.deepEqual(plain(b.get()),plain(a.get()));assert.equal(b.get().state.data.foundation.phi,null);assert.equal(b.get().state.baselines.foundation.width,2);assert.equal(b.get().worksheetInput.geometry.width,null);assert.equal(b.get().library.examples.length,1);});
test('malformed module data is rejected before any of three current states changes',()=>{const a=fixture(),before=plain(a.get()),records=plain(a.adapter.capture()),experiment=JSON.parse(records.experiment);experiment.state.data.foundation.width='not numeric';records.experiment=JSON.stringify(experiment);assert.throws(()=>a.adapter.apply(records));assert.deepEqual(plain(a.get()),before);});
test('invalid learning progress and worksheet metadata cannot partially apply a valid experiment',()=>{for(const target of ['library','worksheet']){const a=fixture(),before=plain(a.get()),records=plain(a.adapter.capture());const value=JSON.parse(records[target]);if(target==='library')value.progress.unknown={index:0,checked:[]};else value.input.meta.date=123;records[target]=JSON.stringify(value);assert.throws(()=>a.adapter.apply(records));assert.deepEqual(plain(a.get()),before);}});
test('current full workspace validates all forty module schemas including blank drafts',()=>{const a=fixture();a.updateExperiment();assert.doesNotThrow(()=>a.adapter.validate(a.adapter.capture()));assert.equal(Object.keys(a.get().state.data).length,40);});
test('whole workspace restore retains legacy excavation, old library JSON and worksheet independently',()=>{
 const sessionText=readFileSync(new URL('./fixtures/session-v4-excavation.json',import.meta.url),'utf8'),old=JSON.parse(sessionText).experiment,a=fixture(),records=plain(a.adapter.capture()),record=JSON.parse(records.experiment);
 record.state.active='excavation';record.state.data.excavation=old.current;record.state.baselines.excavation=old.baseline;record.state.question.excavation=old.question;record.state.compare.excavation=old.compare;record.state.baselineNames.excavation='기존 앵커 예제';records.experiment=JSON.stringify(record);
 records.library=JSON.stringify({version:1,examples:[{id:'old-excavation',name:'기존 앵커',createdAt:'2026-09-22T10:00:00Z',sessionText}],progress:{retaining:{index:1,checked:[0]}},activeRoute:'retaining'});
 const worksheet=JSON.parse(records.worksheet);worksheet.input.meta.project='기존 별도 계산서';records.worksheet=JSON.stringify(worksheet);
 a.adapter.apply(records);const restored=plain(a.get());assert.deepEqual(restored.state,record.state);assert.equal('modelVersion' in restored.state.data.excavation,false);assert.equal(restored.library.examples[0].sessionText,sessionText);assert.deepEqual(restored.library.progress,{retaining:{index:1,checked:[0]}});assert.equal(restored.worksheetInput.meta.project,'기존 별도 계산서');
 const b=fixture();b.importFile(a.exportFile());assert.deepEqual(plain(b.get()),restored);
});
test('workspace restoration preserves new excavation drafts and nested comparison without running physics',()=>{
 const a=fixture(),records=plain(a.adapter.capture()),record=JSON.parse(records.experiment),d=record.state.data.excavation,b=record.state.baselines.excavation;
 assert.equal(d.modelVersion,2);d.soil.kh=null;d.supports[0].z=null;d.observation={phase:'backfill',depth:4,eventSide:'before',mode:'history',wallId:'B',position:.25,resultMode:'increment'};d.plan.corners=[1,3];b.plan.lx=24;b.observation.resultMode='envelope';record.state.active='excavation';record.state.compare.excavation=false;records.experiment=JSON.stringify(record);
 a.adapter.apply(records);assert.deepEqual(plain(a.get().state),record.state);
 const restored=fixture();restored.importFile(a.exportFile());assert.deepEqual(plain(restored.get().state),record.state);
});
