/* Compression history and consolidation share conventions, not independent copies of the same model. */
const ConsolidationLabs = (() => {
 const fhwa='<a href="https://www.fhwa.dot.gov/engineering/geotech/pubs/nhi06088.pdf" target="_blank" rel="noopener">FHWA NHI-06-088 · 5·7장</a>';
 const seriesSource='<a href="https://www.soest.hawaii.edu/martel/Courses/GG454/Lec_41_2018.pptx.pdf" target="_blank" rel="noopener">University of Hawaiʻi GG454 · 압밀 해와 배수경계</a>';
 const linkMv='<a href="https://rosap.ntl.bts.gov/view/dot/29538/dot_29538_DS1.pdf" target="_blank" rel="noopener">FHWA/IN/JTRP-2015/11 · A.4.3.5, k–mv–cv</a>';
 const path=(points,x,y)=>points.map((p,i)=>`${i?'L':'M'}${x(p).toFixed(2)} ${y(p).toFixed(2)}`).join(' ');
 const historyDiagram=(r,b)=>{
  const records=[...r.reference,...r.path,...(b?[...b.reference,...b.path]:[])];
  const xmin=Math.min(...records.map(p=>p.stress)),xmax=Math.max(...records.map(p=>p.stress));
  const values=records.map(p=>p.e),margin=Math.max(.03,(Math.max(...values)-Math.min(...values))*.13),emin=Math.max(0,Math.min(...values)-margin),emax=Math.max(...values)+margin;
  const xx=p=>67+540*(Math.log10(p.stress)-Math.log10(xmin))/(Math.log10(xmax)-Math.log10(xmin)),yy=p=>270-210*(p.e-emin)/(emax-emin);
  let a='<text x="67" y="25" style="font-size:15px;fill:var(--color-text-primary)">간극비 e · 위로 갈수록 더 큰 부피</text>';
  for(let i=0;i<=4;i++){const e=emin+(emax-emin)*i/4,y=yy({e});a+=`<line class="grid" x1="67" x2="607" y1="${y}" y2="${y}"/><text x="57" y="${y+4}" text-anchor="end">${fmt(e,3)}</text>`;}
  const stressTicks=[...new Set([r.sigmaUnload,r.sigma0,r.preconsolidation,r.sigmaFinal])].sort((a,b)=>a-b);
  let last=-100;
  for(const v of stressTicks){const x=xx({stress:v});a+=`<line class="grid" x1="${x}" x2="${x}" y1="60" y2="270"/>`;if(x-last>42){a+=`<text x="${x}" y="289" text-anchor="middle">${fmt(v,0)}</text>`;last=x;}}
  a+=`<path d="${path(r.reference,xx,yy)}" fill="none" stroke="var(--color-border-strong)" stroke-width="2"/><line x1="${xx({stress:r.preconsolidation})}" x2="${xx({stress:r.preconsolidation})}" y1="48" y2="270" stroke="var(--color-accent-purple)" stroke-dasharray="5 4"/><text x="${Math.min(550,Math.max(118,xx({stress:r.preconsolidation})))}" y="43" text-anchor="middle">초기 σ′p ${fmt(r.preconsolidation,0)} kPa</text>`;
  if(b)a+=`<path d="${path(b.activePath,xx,yy)}" fill="none" stroke="var(--color-text-muted)" stroke-width="2" stroke-dasharray="5 4"/><circle cx="${xx(b.selected)}" cy="${yy(b.selected)}" r="6" fill="white" stroke="var(--color-text-muted)" stroke-width="2"/>`;
  a+=`<path d="${path(r.activePath,xx,yy)}" fill="none" stroke="var(--color-action-primary)" stroke-width="3"/>`;
  const pointGroups=new Map();r.stages.forEach((p,i)=>{const key=`${p.stress}|${p.e}`;if(!pointGroups.has(key))pointGroups.set(key,[]);pointGroups.get(key).push({...p,index:i});});
  for(const group of pointGroups.values()){const p=group[0],active=group.some(v=>v.key===r.stage),label=group.length===1?`${p.index} ${p.label}`:`${group.map(v=>v.index).join('·')} 동일점`;a+=`<circle cx="${xx(p)}" cy="${yy(p)}" r="${active?7:4}" fill="${active?'var(--color-action-primary)':'white'}" stroke="var(--color-action-primary)" stroke-width="2"/><text x="${Math.max(89,Math.min(585,xx(p)))}" y="${yy(p)+(p.index===0?-15:20)}" text-anchor="middle" style="fill:var(--color-text-primary)">${label}</text>`;}
  a+='<text x="607" y="318" text-anchor="end">유효응력 σ′ (kPa) · 로그 눈금</text>';
  return svgWrap(a,`초기, 제하, 재재하 e 로그 유효응력 경로. 현재 ${r.selected.label}, 간극비 ${fmt(r.selected.e,3)}, OCR ${fmt(r.selected.ocr,2)}`)+'<div class="chart-caption">0 초기 → 1 제하 → 2 재재하. 회색선은 이선형 관계, 파란선은 선택 단계까지의 경로입니다. 겹치는 제하·재재하는 같은 Cr 기울기를 사용합니다.</div>';
 };
 const primaryDiagram=(r,b)=>{
  const maxDepth=Math.max(r.thickness,b?.thickness||0),maxPressure=Math.max(1,r.deltaStress,b?.deltaStress||0),maxDays=Math.max(r.curveEndDays,b?.curveEndDays||0),maxSettlement=Math.max(1,r.finalSettlementMm,b?.finalSettlementMm||0)*1.1;
  const px=p=>62+190*p.excess/maxPressure,py=p=>70+190*p.depth/maxDepth,tx=p=>342+265*p.days/maxDays,ty=p=>70+190*p.settlementMm/maxSettlement;
  let a='<text x="62" y="28" style="font-size:14px;fill:var(--color-text-primary)">過잉수압 uₑ</text><text x="342" y="28" style="font-size:14px;fill:var(--color-text-primary)">1차압밀침하 S(t)</text>'.replace('過잉','과잉');
  a+=`<rect x="62" y="70" width="190" height="${190*r.thickness/maxDepth}" fill="var(--color-bg-surface-alt-1)"/><line x1="58" x2="256" y1="70" y2="70" stroke="var(--color-accent-skyblue)" stroke-width="4"/><text x="155" y="56" text-anchor="middle">상면 배수 · uₑ=0</text>`;
  const bottom=py({depth:r.thickness});a+=`<line x1="58" x2="256" y1="${bottom}" y2="${bottom}" stroke="${r.drainage==='double'?'var(--color-accent-skyblue)':'var(--color-text-primary)'}" stroke-width="4"/><text x="157" y="${bottom+22}" text-anchor="middle">${r.drainage==='double'?'하면 배수 · uₑ=0':'하면 불투수 · ∂uₑ/∂z=0'}</text>`;
  for(let i=0;i<=4;i++){const z=maxDepth*i/4,y=py({depth:z});a+=`<text x="52" y="${y+4}" text-anchor="end">${fmt(z,1)}</text><line class="grid" x1="62" x2="252" y1="${y}" y2="${y}"/>`;const days=maxDays*i/4,x=tx({days});a+=`<line class="grid" x1="${x}" x2="${x}" y1="70" y2="260"/><text x="${x}" y="284" text-anchor="middle">${fmt(days,0)}</text>`;}
  for(let i=0;i<=3;i++){const s=maxSettlement*i/3,y=ty({settlementMm:s});a+=`<line class="grid" x1="342" x2="607" y1="${y}" y2="${y}"/><text x="332" y="${y+4}" text-anchor="end">${fmt(s,0)}</text>`;}
  for(const v of [0,maxPressure/2,maxPressure])a+=`<text x="${px({excess:v})}" y="304" text-anchor="middle">${fmt(v,0)}</text>`;
  if(b)a+=`<path d="${path(b.profile,px,py)}" fill="none" stroke="var(--color-text-muted)" stroke-width="2" stroke-dasharray="5 4"/><path d="${path(b.timeCurve,tx,ty)}" fill="none" stroke="var(--color-text-muted)" stroke-width="2" stroke-dasharray="5 4"/>`;
  a+=`<path d="${path(r.profile,px,py)}" fill="none" stroke="var(--color-action-primary)" stroke-width="3"/><path d="${path(r.timeCurve,tx,ty)}" fill="none" stroke="var(--color-action-primary)" stroke-width="2.5"/><line x1="342" x2="607" y1="${ty({settlementMm:r.finalSettlementMm})}" y2="${ty({settlementMm:r.finalSettlementMm})}" stroke="var(--color-accent-purple)" stroke-dasharray="4 4"/><circle cx="${tx({days:r.timeDays})}" cy="${ty(r)}" r="5" fill="var(--color-action-primary)" stroke="white" stroke-width="1.5"/><text x="348" y="${ty({settlementMm:r.finalSettlementMm})-8}" text-anchor="start" style="fill:var(--color-accent-purple)">최종 ${fmt(r.finalSettlementMm,0)} mm</text>`;
  a+='<text x="62" y="326">깊이 z(m) ↓ · uₑ(kPa) →</text><text x="607" y="326" text-anchor="end">경과시간 t(일) → · 침하(mm) ↓</text>';
  return svgWrap(a,`층두께 ${fmt(r.thickness)} m의 깊이별 과잉수압과 시간침하곡선. ${r.timeDays}일, 현재 침하 ${fmt(r.settlementMm)} mm`)+`<div class="chart-caption">과잉수압은 정수압에 추가된 값입니다. 현재 t=${fmt(r.timeDays)}일 · 최대 배수거리 Hdr=${fmt(r.hdr)}m. 두 그래프는 서로 다른 가로축을 사용합니다.</div>`;
 };
 const secondaryDiagram=(r,b)=>{
  const minDay=Math.min(r.startDays,b?.startDays||r.startDays),maxDay=Math.max(r.endDays,b?.endDays||0,minDay*1.01),ymax=Math.max(1,r.settlementMm,b?.settlementMm||0)*1.15;
  const xx=p=>65+540*(Math.log10(p.days)-Math.log10(minDay))/(Math.log10(maxDay)-Math.log10(minDay)),yy=p=>65+205*p.settlementMm/ymax;
  let a='<text x="65" y="28" style="font-size:15px;fill:var(--color-text-primary)">기준시점 이후 추가 2차압축량 (mm)</text>';
  for(let i=0;i<=4;i++){const s=ymax*i/4,y=yy({settlementMm:s});a+=`<line class="grid" x1="65" x2="605" y1="${y}" y2="${y}"/><text x="55" y="${y+4}" text-anchor="end">${fmt(s,1)}</text>`;const days=10**(Math.log10(minDay)+(Math.log10(maxDay)-Math.log10(minDay))*i/4),x=xx({days});a+=`<line class="grid" x1="${x}" x2="${x}" y1="65" y2="270"/><text x="${x}" y="292" text-anchor="middle">${fmt(days,0)}</text>`;}
  if(b)a+=`<path d="${path(b.curve,xx,yy)}" fill="none" stroke="var(--color-text-muted)" stroke-width="2" stroke-dasharray="5 4"/>`;
  a+=`<path d="${path(r.curve,xx,yy)}" fill="none" stroke="var(--color-action-primary)" stroke-width="3"/><circle cx="${xx({days:r.startDays})}" cy="65" r="5" fill="white" stroke="var(--color-action-primary)" stroke-width="2"/><circle cx="${xx({days:r.endDays})}" cy="${yy(r)}" r="6" fill="var(--color-action-primary)"/><text x="605" y="320" text-anchor="end">재하 시작 이후 시간 t(일) · 로그 눈금</text>`;
  return svgWrap(a,`2차압축은 시간 로그에 비례. ${fmt(r.startDays)}일 이후 ${fmt(r.endDays)}일까지 추가 ${fmt(r.settlementMm)} mm`)+`<div class="chart-caption">곡선은 t₁ 이후 구간만 표시합니다. t₁ 이전의 1차압밀 곡선을 이어 붙이거나 이중 합산하지 않습니다.</div>`;
 };
 return [
  {key:'compression',meta:{name:'압축성과 응력이력',sub:'제하·재재하·선행압밀',group:'변형과 강도 / 압축성',navGroup:'mechanics',words:'압축성 압축지수 재압축 팽창 제하 굴착 재재하 응력이력 OCR 선행압밀 정규압밀 과압밀 e log 구속탄성계수 mv 압밀시험 시험점 정수 읽기 Cc Cr',questions:[['history','응력이력'],['reading','시험점에서 정수 읽기']]},
   defaults:{readingSource:'example',evidenceBranch:'loading',evidenceFirst:2,evidenceLast:5,testBranch:'loading',testFirst:3,testLast:5,sigma0:100,preconsolidation:200,sigmaUnload:50,sigmaFinal:300,e0:.8,cc:.3,cr:.05,thickness:6,stage:'reload'},
   bounds:{sigma0:[1,1000,'초기 유효응력','kPa'],preconsolidation:[1,2000,'선행압밀응력','kPa'],sigmaUnload:[1,1000,'제하 후 유효응력','kPa'],sigmaFinal:[1,2000,'재재하 후 유효응력','kPa'],e0:[.05,3,'초기 간극비',''],cc:[.01,1,'압축지수 Cc',''],cr:[0,.3,'재압축·팽창지수 Cr',''],thickness:[.5,30,'초기 층두께','m']},
   labels:{readingSource:['시험 자료',''],evidenceBranch:['실제 기록 경로',''],evidenceFirst:['실제 첫 점',''],evidenceLast:['실제 끝 점',''],testBranch:['시험 경로',''],testFirst:['첫 점 번호',''],testLast:['끝 점 번호',''],sigma0:['초기 σ′₀','kPa'],preconsolidation:['선행압밀 σ′p','kPa'],sigmaUnload:['제하 σ′u','kPa'],sigmaFinal:['재재하 σ′f','kPa'],e0:['초기 e₀',''],cc:['압축지수 Cc',''],cr:['재압축·팽창지수 Cr',''],thickness:['초기 H₀','m'],stage:['현재 단계','']},
   activeFields:(d,q)=>q==='reading'?['readingSource',...(d.readingSource==='usgs'?['evidenceBranch','evidenceFirst','evidenceLast']:['testBranch','testFirst','testLast'])]:['sigma0','preconsolidation','sigmaUnload','sigmaFinal','e0','cc','cr','thickness','stage'],
   onFieldChange:(d,f)=>OedometerEvidenceView.onFieldChange(d,f),
   compute:(d,q)=>q==='reading'?(d.readingSource==='usgs'?OedometerEvidence.read(d):d.readingSource==='example'?OedometerReading.read(d):{valid:false,errors:['시험 자료를 선택하세요.']}):Consolidation.stressHistory(d),
   controls:(d,q)=>q==='reading'?compressionReadingControls(d):`<div class="select-row"><label for="compression-stage">관찰 단계</label><select id="compression-stage" data-field="stage"><option value="initial" ${d.stage==='initial'?'selected':''}>0 · 초기</option><option value="unload" ${d.stage==='unload'?'selected':''}>1 · 굴착에 해당하는 제하</option><option value="reload" ${d.stage==='reload'?'selected':''}>2 · 재재하</option></select></div><p class="parameter-note">세 단계 모두 충분히 배수된 상태입니다. 응력을 직접 입력하며 실제 굴착 깊이로 자동 환산하지 않습니다.</p><div class="parameter-grid">${fieldControl('sigma0','초기 유효응력 σ′₀',d.sigma0,1,1000,1,'kPa')}${fieldControl('preconsolidation','초기 선행압밀응력 σ′p',d.preconsolidation,1,2000,1,'kPa','과거 최대 응력 · σ′₀ 이상')}${fieldControl('sigmaUnload','제하 후 유효응력 σ′u',d.sigmaUnload,1,1000,1,'kPa','초기보다 낮은 값 · 0 응력은 로그식에서 제외')}${fieldControl('sigmaFinal','재재하 후 유효응력 σ′f',d.sigmaFinal,1,2000,1,'kPa','선행압밀응력을 넘으면 Cc 구간으로 진입')}${fieldControl('cc','압축지수 Cc',d.cc,.01,1,.01,'','처녀압축 e–logσ′ 기울기의 크기')}${fieldControl('cr','재압축·팽창지수 Cr',d.cr,0,.3,.005,'','제하와 재재하에 같은 Cr 사용')}</div><details class="setting"><summary>시료와 층두께</summary>${fieldControl('e0','초기 간극비 e₀',d.e0,.05,3,.05,'')}${fieldControl('thickness','초기 층두께 H₀',d.thickness,.5,30,.5,'m')}</details>`,
   render:({data:d,result:r,baseline:b,baselineData:bd,question:q})=>q==='reading'?compressionReadingRender(d,r,b,bd):({title:'흙을 파냈다가 다시 누르면, 처음 누를 때와 같을까요?',conditions:['단계별 배수 완료','1D · 횡변형 없음','제하·재재하에 같은 Cr','(+): 침하 / (−): 팽창'],plotTitle:'e–logσ′ 경로와 현재 단계',comparisonPlot:true,chart:historyDiagram(r,b),
    results:metric('현재 간극비 e',r.selected.e,'',b?.selected.e??null,false,3)+metric('현재 OCR',r.selected.ocr,'',b?.selected.ocr??null,false,2)+metric('초기 대비 변위',r.settlementMm,'mm',b?.settlementMm??null,true)+metric('직전 단계 대비',r.stepSettlementMm,'mm',b?.stepSettlementMm??null),
    explanation:`<strong>${r.stage==='initial'?'초기 응력보다 큰 과거 최대 응력이 이력을 결정합니다.':r.stage==='unload'?'하중을 덜면 Cr 기울기를 따라 간극비가 커집니다.':d.sigmaFinal>d.preconsolidation?'과거 최대 응력을 넘은 구간은 Cc로 압축됩니다.':'과거 최대 응력 이내에서는 Cr로 재압축됩니다.'}</strong><br>현재 ${r.selected.label} 단계의 σ′=${fmt(r.selected.stress)} kPa, σ′p=${fmt(r.selected.preconsolidation)} kPa입니다. ${r.stage==='reload'&&d.sigmaFinal>d.preconsolidation?'새 최대 응력이 선행압밀응력이 되어 OCR=1입니다.':''}<span class="hint">팽창량은 과거 처녀압축 침하의 단순 음수가 아닙니다. 실제 제하·재재하 곡선의 곡률과 이력손실은 이선형 근사에서 생략합니다.</span>`,
    theory:`<div class="theory-grid"><div><div class="theory-formula">OCR = σ′p / σ′<br>Δe = −C · log₁₀(σ′₂/σ′₁)<br>S = H₀(e₀ − e)/(1 + e₀)</div><p>S = ${fmt(d.thickness)} × (${fmt(d.e0,3)} − ${fmt(r.selected.e,3)}) / ${fmt(1+d.e0,3)}<br>= ${fmt(r.settlementMm)} mm</p></div><div class="theory-meta"><strong>기울기와 강성의 연결</strong><p>현재점에서 추가 재하할 때<br>mv = C / [ln(10)(1+e)σ′]<br>M = 1/mv = ${r.constrainedModulus===null?'∞ (Cr=0 이상화)':fmt(r.constrainedModulus/1000,2)+' MPa'}</p><p>M은 횡변형을 구속한 1D 계수입니다. Young의 E와 같지 않습니다.</p></div></div>`,
    method:`<h3>경로별 계산</h3><p>제하: eᵤ=e₀−Cr log₁₀(σ′u/σ′₀). 재재하 응력이 초기 σ′p 이하이면 e𝒻=e₀−Cr log₁₀(σ′f/σ′₀). 이를 넘으면 e𝒻=e₀−Cr log₁₀(σ′p/σ′₀)−Cc log₁₀(σ′f/σ′p)입니다.</p><p>같은 흙입자 부피와 단면적을 유지하므로 H/(1+e)=H₀/(1+e₀)를 보존합니다. 각 단계 변위도 이 공통 초기 기준으로 계산합니다. 원래 응력까지 재재하하면 이 이상화에서는 원래 간극비로 돌아옵니다.</p><h3>해석 범위와 출처</h3><p>평균 유효응력 하나로 대표하는 균질 층입니다. 파낸 흙의 중량·기초 순하중·깊이별 응력은 별도 하중 모형에서 정해야 합니다. 시간효과·과잉수압·2차압축을 여기서 계산하지 않습니다. Cc·Cr·σ′p는 교육용 입력값이며 이 도구가 시험곡선에서 자동 추정한 값이 아닙니다.</p><p>${fhwa} · §7.5.1, §7.5.2 및 식 7-2·7-4, 표 7-3.</p>`}),
  },
  {key:'consolidation',meta:{name:'압밀과 시간',sub:'물 빠짐·침하·2차압축',group:'변형과 강도 / 압밀',navGroup:'mechanics',words:'압밀 일차압밀 1차압밀 2차압축 이차압밀 크리프 배수거리 일면 양면 투수계수 체적압축계수 mv cv 압밀도 과잉간극수압 침하 시간 t90',questions:[['primary','1차압밀'],['secondary','2차압축']]},
   defaults:{k:1e-9,mv:.0003,thickness:6,deltaStress:100,timeDays:100,drainage:'double',gammaW:9.81,cAlpha:.01,eAtStart:.8,thicknessAtStart:6,startDays:365,endDays:3650},bounds:{cAlpha:[0,.1,'2차압축지수 Cα',''],eAtStart:[0,3,'기준시점 간극비 e₁',''],thicknessAtStart:[.1,30,'기준시점 층두께 H₁','m']},
   activeFields:(d,q)=>q==='secondary'?['cAlpha','eAtStart','thicknessAtStart','startDays','endDays']:['k','mv','thickness','deltaStress','timeDays','drainage','gammaW'],
   labels:{k:['투수계수 k','m/s'],mv:['체적압축계수 mv','1/kPa'],thickness:['층두께 H','m'],deltaStress:['재하 증가량 Δσ','kPa'],timeDays:['경과시간','일'],drainage:['배수조건',''],cAlpha:['2차압축지수 Cα',''],eAtStart:['기준시점 e₁',''],thicknessAtStart:['기준시점 H₁','m'],startDays:['기준시점 t₁','일'],endDays:['관찰시점 t₂','일']},
   compute:(d,q)=>q==='secondary'?Consolidation.secondary(d):Consolidation.primary(d),
   controls:(d,q)=>q==='secondary'?`<p class="parameter-note">1차압밀 후 시험에서 정한 기준시점의 H₁·e₁와 Cα를 사용합니다. 옆 탭의 t90을 t₁로 자동 대입하지 않습니다.</p><div class="parameter-grid">${fieldControl('cAlpha','2차압축지수 Cα',d.cAlpha,0,.1,.001,'','e–log₁₀t 기울기의 크기')}${fieldControl('startDays','기준시점 t₁',d.startDays,1,3650,1,'일','재하 시작 후 1차압밀이 사실상 끝난 기준시점',1,true)}${fieldControl('endDays','관찰시점 t₂',d.endDays,1,36500,1,'일','t₂ ≥ t₁ · 같은 기준에서 잰 시간',1,true)}${fieldControl('thicknessAtStart','기준시점 층두께 H₁',d.thicknessAtStart,.1,30,.1,'m')}${fieldControl('eAtStart','기준시점 간극비 e₁',d.eAtStart,0,3,.05,'')}</div>`:
    `<p class="parameter-note">k와 mv를 바꾸면 cv가 함께 계산됩니다. 실제 같은 흙의 물성을 마음대로 분리하는 시험이 아닌, 일정 물성 모형의 매개변수 비교입니다.</p><div class="parameter-grid">${fieldControl('k','투수계수 k',d.k,0,10,.01,'×10⁻⁹ m/s','숫자 1 = 1×10⁻⁹ m/s',1e-9,true)}${fieldControl('mv','체적압축계수 mv',d.mv,0,20,.1,'×10⁻⁴ /kPa','숫자 3 = 0.0003 /kPa · cv의 종속관계',1e-4,true)}${fieldControl('thickness','실제 층두께 H',d.thickness,.1,30,.1,'m','양면배수여도 침하 계산에는 실제 H를 사용',1,true)}${fieldControl('deltaStress','일시 재하 증가량 Δσ',d.deltaStress,0,300,5,'kPa','깊이 전체에 균일 · 소변형 범위 mvΔσ ≤ 0.10',1,true)}${fieldControl('timeDays','재하 후 경과시간 t',d.timeDays,0,1000,1,'일','같은 압밀도에 이르는 시간을 비교하세요.',1,true)}</div><div class="select-row"><label for="drainage-condition">배수조건</label><select id="drainage-condition" data-field="drainage"><option value="double" ${d.drainage==='double'?'selected':''}>양면 배수 · Hdr=H/2</option><option value="single" ${d.drainage==='single'?'selected':''}>상면만 배수 · Hdr=H</option></select></div>`,
   render:({data:d,result:r,baseline:b,question:q})=>q==='secondary'?{
    title:'과잉수압이 거의 사라진 뒤에도 침하는 이어질까요?',conditions:['1차압밀 후 별도 지수모형','일정 유효응력','Cα·H₁·e₁를 독립 입력'],plotTitle:'시간 로그에 따른 추가 2차압축',comparisonPlot:true,chart:secondaryDiagram(r,b),results:metric('추가 2차압축량',r.settlementMm,'mm',b?.settlementMm??null,true)+metric('최종 간극비 e₂',r.endE,'',b?.endE??null,false,3)+metric('시간의 로그 간격',r.logCycles,'',b?.logCycles??null,false,2),
    explanation:'<strong>같은 시간 배수마다 같은 양의 추가 압축이 생기는 단순 지수모형입니다.</strong><br>예를 들어 t₁→10t₁과 10t₁→100t₁은 각각 한 로그 구간입니다. Cα는 과잉수압 소산속도 cv와 다른 정수입니다.<span class="hint">실제 1차·2차 변형은 겹칠 수 있습니다. 여기서는 끝부분 기울기의 의미를 분리해 보며, 1차압밀침하에 자동으로 합산하지 않습니다.</span>',
    theory:`<div class="theory-grid"><div><div class="theory-formula">Δe = Cα log₁₀(t₂/t₁)<br>Sα = H₁ Cα / (1+e₁) × log₁₀(t₂/t₁)</div><p>Sα = ${fmt(d.thicknessAtStart)} × ${fmt(d.cAlpha,3)} / ${fmt(1+d.eAtStart,3)} × ${fmt(r.logCycles,3)}<br>= ${fmt(r.settlementMm)} mm</p></div><div class="theory-meta"><strong>기준시점을 일치시키기</strong><p>H₁과 e₁은 모두 t₁ 때의 값입니다.<br>Cαε = Cα/(1+e₁) = ${fmt(r.modifiedIndex,5)}</p><p>이 모형은 t₁ 자체를 찾아내지 않습니다. 시험의 장기 구간과 적용 응력 범위가 필요합니다.</p></div></div>`,
    method:`<h3>별도 2차압축 모형</h3><p>Cα는 간극비 감소량을 log₁₀ 시간 차로 나눈 무차원 지수입니다. H₁·e₁은 같은 기준시점의 값이므로 H₁/(1+e₁)를 보존한 식을 사용합니다. t₂=t₁이면 추가량 0, t₂&lt;t₁ 또는 e₂&lt;0이면 입력 오류입니다.</p><p>교재·설계 절차마다 t₁을 1차압밀 종료 또는 t90 부근으로 근사하는 방식이 다릅니다. 본 실험에서는 사용자가 정한 1차압밀 후 기준시점으로 정의하며, 이론상 점근적인 U=100%의 유한 도달시간을 만들어 쓰지 않습니다.</p><p>${fhwa} · §7.5.4, 식 7-9·7-10; H/(1+e)의 공통 기준을 명시하여 표기했습니다.</p>`
   }:{
    title:'더 잘 빠지는 물과 더 잘 눌리는 흙은 침하에 어떻게 다르게 작용할까요?',conditions:['포화·균질·1D','일시 균일 재하','k·mv 일정 / H 고정',`γw=${fmt(r.gammaW,2)} kN/m³`],plotTitle:'과잉수압 소산과 시간–침하',comparisonPlot:true,chart:primaryDiagram(r,b),
    results:metric('평균 압밀도 U',r.degree===null?'무재하':r.degree*100,r.degree===null?'':'%',b?.degree==null?null:b.degree*100,true)+metric('현재 침하 S(t)',r.settlementMm,'mm',b?.settlementMm??null)+metric('최종 1차압밀침하',r.finalSettlementMm,'mm',b?.finalSettlementMm??null)+metric('90% 압밀 시간',r.deltaStress===0?'무재하':r.t90Days,r.deltaStress===0?'':'일',b&&b.deltaStress>0?b.t90Days:null),
    explanation:`<strong>k는 물 빠짐의 속도, mv는 눌리는 양과 속도에 함께 관여합니다.</strong><br>k만 2배 → 최종침하는 같고 같은 U까지 시간은 1/2. mv만 2배 → 최종침하와 같은 U까지 시간이 모두 2배입니다.<span class="hint">양면배수는 Hdr을 절반으로 하므로 같은 U까지 시간이 1/4입니다. 최종침하 계산에 쓰는 H까지 절반으로 줄이지 않습니다.</span>${r.deltaStress===0?'<span class="notice">Δσ=0이므로 추가 과잉수압과 침하는 0입니다. 실제 압밀도와 도달시간을 표시하지 않습니다.</span>':''}`,
    theory:`<div class="theory-grid"><div><div class="theory-formula">cv = k / (mv γw)<br>Tv = cv t / Hdr²<br>S∞ = mv Δσ H · S(t)=U(Tv)S∞</div><p>cv = ${d.k.toExponential(2)} / (${d.mv.toExponential(2)} × ${fmt(r.gammaW,2)})<br>= ${r.cv.toExponential(3)} m²/s = ${fmt(r.cvDays,5)} m²/일<br>Tv = ${fmt(r.tv,4)}</p></div><div class="theory-meta"><strong>변수의 연결</strong><p>S∞ = ${d.mv.toExponential(2)} × ${fmt(d.deltaStress)} × ${fmt(d.thickness)}<br>= ${fmt(r.finalSettlementMm)} mm</p><p>t90 ≈ 0.848 Hdr²/cv<br>${r.deltaStress>0?`= ${fmt(r.t90Days)}일`:'무재하 상태에서는 도달시간 해석 제외'}</p></div></div>`,
    method:`<h3>Terzaghi 1D 해</h3><p>∂uₑ/∂t=cv∂²uₑ/∂z². 재하 직후 내부 uₑ=Δσ, 배수면 uₑ=0입니다. 상면만 배수할 때 아래쪽은 ∂uₑ/∂z=0, 양면일 때 양쪽 uₑ=0입니다.</p><div class="formula">uₑ/Δσ = Σ [4/(nπ)] sin(nπz/2Hdr) exp(−n²π²Tv/4), n=1,3,5,…<br>U = 1 − Σ [8/(n²π²)] exp(−n²π²Tv/4)</div><p>초기 짧은 시간은 동일 확산해의 경계층 표현을 사용하여 진동과 긴 급수를 피합니다. 평균 U는 깊이별 과잉수압 평균의 소산비이자 이 일정 mv 모형의 침하비입니다. uₑ는 정수압을 제외한 추가 수압입니다.</p><h3>물성과 단위</h3><p>k:m/s, mv:1/kPa=m²/kN, γw:kN/m³이므로 cv:m²/s입니다. 1일=86400초로 변환합니다. UI에서 k의 숫자 1은 10⁻⁹m/s, mv의 숫자 3은 3×10⁻⁴/kPa입니다. 실제 흙에서 k와 mv는 응력·간극비에 따라 함께 변할 수 있습니다.</p><h3>적용 범위</h3><p>고정 H, 일정 물성, 소변형, 순간 재하, 균일한 초기 과잉수압을 가정합니다. 도구의 비교 범위는 mvΔσ≤10%로 제한합니다. 이 10%는 보편적인 설계 허용치가 아닌 구현 범위입니다. 다층·방사형 배수·점진 재하·2차압축·배수저항·대변형을 이 결과에 포함하지 않습니다.</p><p>${fhwa} · §7.5.3, 식 7-8 및 표 7-4.<br>${seriesSource}<br>${linkMv}</p>`
   },
  },
 ];
})();
