const ImprovementLabs = (() => {
  const source = '<a href="https://www.fhwa.dot.gov/engineering/geotech/pubs/nhi16027.pdf" target="_blank" rel="noopener">FHWA NHI-16-027 · 제2장</a>';
  const smearSource = '<a href="https://doi.org/10.1016/j.geotexmem.2011.10.007" target="_blank" rel="noopener">Abuel-Naga 등 (2012) · Hansbo 기본식</a>';
  const combinedSource = '<a href="https://www.issmge.org/uploads/publications/1/22/STAL9781614996569-1231.pdf" target="_blank" rel="noopener">ISSMGE · Oshima 등 (2005), 식 2</a>';
  const stressSource = '<a href="https://www.fhwa.dot.gov/engineering/geotech/pubs/nhi06088.pdf" target="_blank" rel="noopener">FHWA NHI-06-088 · §7.5</a>';
  const timeSource = '<a href="https://onlinepubs.trb.org/Onlinepubs/hrbproceedings/37/37-039.pdf" target="_blank" rel="noopener">Schiffman (1958) · 시간 변화 재하와 압밀</a>';
  const mvSource = '<a href="https://rosap.ntl.bts.gov/view/dot/29538/dot_29538_DS1.pdf" target="_blank" rel="noopener">FHWA/IN/JTRP-2015/11 · A.4.3.5</a>';
  const path = (points, x, y) => points.map((p, i) => `${i ? 'L' : 'M'}${x(p).toFixed(2)} ${y(p).toFixed(2)}`).join(' ');
  const select = (field, label, value, options) => `<div class="select-row"><label for="improve-${field}">${label}</label><select id="improve-${field}" data-field="${field}">${options.map(([k, name]) => `<option value="${k}" ${value === k ? 'selected' : ''}>${name}</option>`).join('')}</select></div>`;
  const drainage = d => select('drainage', '층 경계의 수직 배수', d.drainage, [['double', '상·하면 배수 · Hdr=H/2'], ['single', '상면 배수 · Hdr=H']]);
  const material = d => `${fieldControl('logKv','수직 투수계수 log₁₀ kv',d.logKv,-11,-7,.1,'','현재 kv='+ (10**d.logKv).toExponential(2)+' m/s')}${fieldControl('mv','체적압축계수 mv',d.mv,.5,10,.1,'×10⁻⁴ /kPa','숫자 3 = 0.0003 /kPa',1e-4)}${fieldControl('thickness','층두께 H',d.thickness,1,20,.5,'m')}${drainage(d)}`;
  const drainsChart = (r, b) => {
    const end = Math.max(r.curveEndDays, b?.curveEndDays || 0), xx = p => 345 + 267 * p.days / end, yy = u => 75 + 185 * u;
    let s = '<text x="34" y="28" style="font-size:14px;fill:var(--color-text-primary)">드레인 평면 배열</text><text x="345" y="28" style="font-size:14px;fill:var(--color-text-primary)">평균 압밀도 U (%)</text>';
    const scale = 48, cx = 145, cy = 170, radius = r.influenceDiameter * scale / 2, spacing = r.spacing * scale;
    s += '<rect x="29" y="48" width="231" height="233" fill="var(--color-bg-surface-alt-1)" rx="4"/>';
    const vertices = r.pattern === 'square' ? [[-r.spacing/2,-r.spacing/2],[r.spacing/2,-r.spacing/2],[r.spacing/2,r.spacing/2],[-r.spacing/2,r.spacing/2]] : Array.from({length:6},(_,i)=>{const a=(30+i*60)*Math.PI/180;return [r.spacing/Math.sqrt(3)*Math.cos(a),r.spacing/Math.sqrt(3)*Math.sin(a)];});
    s += `<polygon points="${vertices.map(([x,y])=>`${cx+x*scale},${cy+y*scale}`).join(' ')}" fill="var(--color-primary-soft)" stroke="var(--color-action-primary)" stroke-width="1.5"/><circle cx="${cx}" cy="${cy}" r="${radius}" fill="none" stroke="var(--color-accent-purple)" stroke-width="1.5" stroke-dasharray="5 4"/>`;
    for(let row=-8;row<=8;row++)for(let col=-8;col<=8;col++){
      const x=cx+spacing*(col+(r.pattern==='triangle' && Math.abs(row)%2 ? .5 : 0)),y=cy+spacing*row*(r.pattern==='triangle'?Math.sqrt(3)/2:1);
      if(x>33&&x<256&&y>52&&y<277)s+=`<circle cx="${x}" cy="${y}" r="${r.drainDiameter*scale/2}" fill="var(--color-action-primary)"/>`;
    }
    if(r.smear==='on')s+=`<circle cx="${cx}" cy="${cy}" r="${r.drainDiameter*r.smearDiameterRatio*scale/2}" fill="var(--color-accent-orange)" fill-opacity=".3" stroke="var(--color-accent-orange)" stroke-width="1.2"/><circle cx="${cx}" cy="${cy}" r="${r.drainDiameter*scale/2}" fill="var(--color-action-primary)"/>`;
    s += `<line x1="35" x2="83" y1="267" y2="267" stroke="var(--color-text-primary)" stroke-width="2"/><text x="60" y="258" text-anchor="middle">1 m</text><text x="145" y="303" text-anchor="middle">s=${fmt(r.spacing,2)} m · de=${fmt(r.influenceDiameter,2)} m</text>`;
    for(let i=0;i<=4;i++){
      const u=i/4,y=yy(u),days=end*i/4,x=xx({days});
      s+=`<line class="grid" x1="345" x2="612" y1="${y}" y2="${y}"/><text x="334" y="${y+4}" text-anchor="end">${100*u}</text><line class="grid" x1="${x}" x2="${x}" y1="75" y2="260"/><text x="${x}" y="284" text-anchor="middle">${fmt(days,0)}</text>`;
    }
    for(const [key,color,dash] of [['vertical','var(--color-text-muted)','5 4'],['radial','var(--color-accent-purple)',''],['combined','var(--color-action-primary)','']])s+=`<path d="${path(r.curve,xx,p=>yy(p[key]))}" fill="none" stroke="${color}" stroke-width="${key==='combined'?3:2}" ${dash?`stroke-dasharray="${dash}"`:''}/>`;
    if(b)s+=`<path d="${path(b.curve,xx,p=>yy(p.combined))}" fill="none" stroke="var(--color-accent-orange)" stroke-width="2" stroke-dasharray="4 4"/>`;
    s+=`<circle cx="${xx(r)}" cy="${yy(r.combined)}" r="5" fill="var(--color-action-primary)" stroke="white" stroke-width="1.5"/><text x="612" y="312" text-anchor="end">경과시간 (일) →</text>`;
    return svgWrap(s,`드레인 간격 ${fmt(r.spacing)} m. 수직 ${fmt(100*r.vertical)}%, 방사형 ${fmt(100*r.radial)}%, 결합 압밀도 ${fmt(100*r.combined)}%.`)+`<div class="chart-caption">왼쪽은 같은 x/y 축척의 실제 간격입니다. 실선 다각형은 배분 면적, 보라 점선 원은 같은 면적의 축대칭 환산 셀입니다. 드레인 길이는 층 전체 H=${fmt(r.thickness)} m로 고정합니다.</div><div class="legend"><span class="legend-item"><i style="border-color:var(--color-action-primary)"></i>결합</span><span class="legend-item"><i style="border-color:var(--color-accent-purple)"></i>방사형만</span><span class="legend-item"><i style="border-color:var(--color-text-muted)"></i>수직만</span>${b?'<span class="legend-item"><i style="border-color:var(--color-accent-orange)"></i>저장한 조건의 결합</span>':''}</div>`;
  };
  const stagedChart = (r,b) => {
    const end=Math.max(r.curveEndDays,b?.curveEndDays||0),x=p=>63+545*p.days/end;
    const pressureRows=[...r.curve,...(b?.curve||[])],pmin=Math.min(0,...pressureRows.map(p=>p.averageExcess)),pmax=Math.max(1,...pressureRows.map(p=>p.load),...pressureRows.map(p=>p.averageExcess));
    const py=v=>57+92*(pmax-v)/(pmax-pmin),smax=Math.max(1,r.finalSettlementMm,b?.finalSettlementMm||0,...pressureRows.map(p=>p.settlementMm))*1.1,sy=v=>203+78*v/smax;
    let s='<text x="63" y="26" style="font-size:14px;fill:var(--color-text-primary)">단계 하중 q · 평균 과잉수압 ūₑ (kPa)</text><text x="63" y="184" style="font-size:14px;fill:var(--color-text-primary)">침하 S (mm) ↓</text>';
    for(let i=0;i<=4;i++){const day=end*i/4,xx=x({days:day});s+=`<line class="grid" x1="${xx}" x2="${xx}" y1="48" y2="149"/><line class="grid" x1="${xx}" x2="${xx}" y1="203" y2="281"/><text x="${xx}" y="302" text-anchor="middle">${fmt(day,0)}</text>`;}
    for(const v of [...new Set([pmin,0,pmax])])s+=`<line class="grid" x1="63" x2="608" y1="${py(v)}" y2="${py(v)}"/><text x="53" y="${py(v)+4}" text-anchor="end">${fmt(v,0)}</text>`;
    for(const v of [0,smax])s+=`<text x="53" y="${sy(v)+4}" text-anchor="end">${fmt(v,0)}</text>`;
    s+=`<path d="${path(r.curve,x,p=>py(p.load))}" fill="none" stroke="var(--color-accent-purple)" stroke-width="2.5"/><path d="${path(r.curve,x,p=>py(p.averageExcess))}" fill="none" stroke="var(--color-accent-orange)" stroke-width="2"/><path d="${path(r.curve,x,p=>sy(p.withoutSurchargeMm))}" fill="none" stroke="var(--color-text-muted)" stroke-width="2" stroke-dasharray="5 4"/><path d="${path(r.curve,x,p=>sy(p.settlementMm))}" fill="none" stroke="var(--color-action-primary)" stroke-width="2.8"/>`;
    if(b)s+=`<path d="${path(b.curve,x,p=>sy(p.settlementMm))}" fill="none" stroke="var(--color-accent-purple)" stroke-width="2" stroke-dasharray="3 4"/>`;
    s+=`<line x1="${x(r)}" x2="${x(r)}" y1="43" y2="281" stroke="var(--color-text-muted)" stroke-dasharray="2 4"/><circle cx="${x(r)}" cy="${sy(r.settlementMm)}" r="5" fill="var(--color-action-primary)" stroke="white" stroke-width="1.5"/><text x="608" y="327" text-anchor="end">시작 후 시간 (일) →</text>`;
    return svgWrap(s,'추가 성토와 제거에 따른 계단 하중, 평균 과잉수압, 연속적인 침하 곡선')+'<div class="chart-caption">보라: 총 추가하중 · 주황: 평균 과잉수압 · 파랑: 단계재하 침하 · 회색 점선: 영구하중만 재하. 하중이 바뀌는 순간 수압은 점프하지만 침하는 연속입니다.'+(b?' 보라 점선 침하곡선은 저장한 조건입니다.':'')+'</div>';
  };
  const preloadChart = (r,b) => {
    const rows=[...r.path,...(b?.path||[]),{stress:r.serviceStress,e:r.withoutE}],minStress=Math.min(...rows.map(p=>p.stress)),maxStress=Math.max(minStress*1.1,...rows.map(p=>p.stress)),emin=Math.min(...rows.map(p=>p.e))-.025,emax=Math.max(...rows.map(p=>p.e))+.025;
    const xx=p=>62+310*Math.log10(p.stress/minStress)/Math.log10(maxStress/minStress), yy=p=>264-195*(p.e-emin)/(emax-emin);
    let s='<text x="62" y="28" style="font-size:14px;fill:var(--color-text-primary)">완전 배수 후 e–logσ′ 경로</text><text x="441" y="28" style="font-size:14px;fill:var(--color-text-primary)">사용하중에 의한</text><text x="441" y="49" style="font-size:14px;fill:var(--color-text-primary)">공사 후 침하</text>';
    for(let i=0;i<=3;i++){const e=emin+(emax-emin)*i/3,y=yy({e});s+=`<line class="grid" x1="62" x2="372" y1="${y}" y2="${y}"/><text x="52" y="${y+4}" text-anchor="end">${fmt(e,2)}</text>`;}
    const reference=[{stress:r.sigma0,e:r.e0},{stress:r.serviceStress,e:r.withoutE}];
    s+=`<path d="${path(reference,xx,yy)}" fill="none" stroke="var(--color-text-muted)" stroke-width="2" stroke-dasharray="5 4"/>`;
    if(b)s+=`<path d="${path(b.path,xx,yy)}" fill="none" stroke="var(--color-accent-orange)" stroke-width="1.8" stroke-dasharray="4 4"/>`;
    s+=`<path d="${path(r.path,xx,yy)}" fill="none" stroke="var(--color-action-primary)" stroke-width="2.8"/>`;
    const grouped=new Map();for(const p of r.path.filter(p=>p.stage!==null)){const key=p.stress+'|'+p.e;if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(p);}
    for(const group of grouped.values()){const p=group[0],y=yy(p),position=p.stage===0||p.stage===1?-12:18;s+=`<circle cx="${xx(p)}" cy="${y}" r="5" fill="white" stroke="var(--color-action-primary)" stroke-width="2"/><text x="${Math.max(72,Math.min(355,xx(p)))}" y="${y+position}" text-anchor="middle">${group.map(v=>v.stage).join('·')}</text>`;}
    const tick=[...new Set([minStress,maxStress])];for(const stress of tick)s+=`<text x="${xx({stress})}" y="288" text-anchor="middle">${fmt(stress,0)}</text>`;
    const maxS=Math.max(1,r.withoutPreloadSettlementMm,r.postServiceSettlementMm),barY=v=>86+168*v/maxS;
    for(const [i,label,v,color] of [[0,'미시행',r.withoutPreloadSettlementMm,'var(--color-text-muted)'],[1,'선행재하',r.postServiceSettlementMm,'var(--color-action-primary)']]){
      const x=448+90*i;s+=`<rect x="${x}" y="86" width="48" height="${168*v/maxS}" rx="3" fill="${color}"/><text x="${x+24}" y="${v/maxS>.25?barY(v)-10:barY(v)+20}" text-anchor="middle" style="fill:${v/maxS>.25?'white':'var(--color-text-muted)'}">${fmt(v,1)}</text><text x="${x+24}" y="284" text-anchor="middle">${label}</text>`;
    }
    s+='<text x="372" y="322" text-anchor="end">σ′ (kPa) · 로그 눈금</text><text x="598" y="322" text-anchor="end">침하 (mm) ↓</text>';
    return svgWrap(s,`초기, 선행재하, 완전 제하, 사용하중의 유효응력 경로. 선행재하 후 공사 후 침하 ${fmt(r.postServiceSettlementMm)} mm.`)+'<div class="chart-caption">0 초기 → 1 선행재하 완료 → 2 선행재하 전량 제거·팽창 완료 → 3 사용하중 재하 완료. 회색 점선은 선행재하 없이 바로 사용하중을 가한 경로입니다. 시간곡선이 아닙니다.'+(b?' 주황 점선은 저장한 조건입니다.':'')+'</div>';
  };
  const commonBounds={logKv:[-11,-7,'log₁₀ kv',''],mv:[.00005,.001,'체적압축계수','1/kPa'],thickness:[1,20,'층두께','m']};
  const commonLabels={logKv:['log₁₀ kv',''],mv:['체적압축계수 mv','1/kPa'],thickness:['층두께','m'],drainage:['수직 배수경계','']};
  return [
    {key:'vertical-drains',meta:{name:'연직드레인',sub:'간격·방사형 배수·교란',group:'지반개량 / 배수 촉진',navGroup:'practice',words:'지반개량 연직드레인 PVD 방사형 Barron Hansbo Carrillo 스미어 smear 교란 배수 간격 선행재하 압밀',questions:[['drains','간격과 압밀 속도']]},
      defaults:{spacing:1.5,timeDays:30,logKv:-9,mv:.0003,thickness:8,drainage:'double',khKv:2,deltaStress:100,pattern:'triangle',drainDiameter:.066,smear:'off',smearDiameterRatio:3,smearPermeabilityRatio:3},
      bounds:{...commonBounds,spacing:[.6,4,'드레인 간격','m'],timeDays:[0,1000,'경과시간','일'],khKv:[.5,10,'투수 이방성 kh/kv',''],deltaStress:[0,200,'재하 증가량','kPa'],drainDiameter:[.03,.12,'환산 드레인 지름','m'],smearDiameterRatio:[1,5,'교란 지름비 ds/dw',''],smearPermeabilityRatio:[1,10,'투수 저하비 kh/ks','']},
      activeFields:d=>['spacing','timeDays','logKv','mv','thickness','khKv','deltaStress','drainDiameter',...(d.smear==='on'?['smearDiameterRatio','smearPermeabilityRatio']:[])],
      labels:{...commonLabels,spacing:['드레인 간격','m'],timeDays:['경과시간','일'],khKv:['kh/kv',''],deltaStress:['재하 증가량','kPa'],pattern:['배열',''],drainDiameter:['환산 지름 dw','m'],smear:['교란',''],smearDiameterRatio:['ds/dw',''],smearPermeabilityRatio:['kh/ks','']},
      compute:d=>Improvement.drains({...d,kv:10**d.logKv}),
      controls:d=>`<p class="parameter-note">드레인은 물이 빠질 길을 추가합니다. 현재 모형에서는 최종 침하량을 줄이지 않으며, 같은 침하에 이르는 시간을 줄입니다.</p><div class="parameter-grid">${fieldControl('spacing','드레인 중심 간격 s',d.spacing,.6,4,.1,'m')}${fieldControl('timeDays','경과시간 t',d.timeDays,0,1000,1,'일')}${fieldControl('logKv','수직 투수계수 log₁₀ kv',d.logKv,-11,-7,.1,'','현재 '+(10**d.logKv).toExponential(2)+' m/s')}${fieldControl('khKv','수평/수직 투수비 kh/kv',d.khKv,.5,10,.1,'','같은 mv를 쓰므로 ch/cv와 같음')}</div>${select('pattern','드레인 배열',d.pattern,[['triangle','정삼각형'],['square','정사각형']])}<details class="setting"><summary>층·하중·드레인 지름</summary>${fieldControl('mv','체적압축계수 mv',d.mv,.5,10,.1,'×10⁻⁴ /kPa','cv=kv/(mvγw)',1e-4)}${fieldControl('thickness','층두께 H · 관통 드레인',d.thickness,1,20,.5,'m')}${fieldControl('deltaStress','순간 재하 Δσ',d.deltaStress,0,200,5,'kPa','mvΔσ ≤ 0.10 범위')}${fieldControl('drainDiameter','환산 원형 지름 dw',d.drainDiameter,.03,.12,.001,'m','판형 드레인의 실제 폭과 다름')}${drainage(d)}</details><details class="setting"><summary>설치 교란 · smear</summary>${select('smear','드레인 주변 투수 저하',d.smear,[['off','없음 · 이상 드레인'],['on','균일한 교란 원환대']])}${d.smear==='on'?`${fieldControl('smearDiameterRatio','교란 지름비 ds/dw',d.smearDiameterRatio,1,5,.1,'','ds < de')}${fieldControl('smearPermeabilityRatio','투수 저하비 kh/ks',d.smearPermeabilityRatio,1,10,.2,'','1이면 투수성 저하 없음')}`:'<p class="note">교란을 켜면 같은 간격에서도 배수가 느려지는 효과를 봅니다.</p>'}</details>`,
      render:({result:r,baseline:b})=>({title:'드레인을 촘촘히 넣으면 침하량이 줄어들까요, 빨리 끝날까요?',conditions:['균질 포화층 · 순간 균일 재하','전층 관통 드레인','등변형률 방사형 근사 · n>5','배수저항 0 · mv·k 일정'],plotTitle:'영향 면적과 세 가지 배수 경로',comparisonPlot:true,chart:drainsChart(r,b),
        results:metric('현재 결합 압밀도',r.degree===null?'무재하':100*r.combined,r.degree===null?'':'%',b?.degree==null?null:100*b.combined,true)+metric('현재 침하',r.settlementMm,'mm',b?.settlementMm??null)+metric('최종 1차압밀침하',r.finalSettlementMm,'mm',b?.finalSettlementMm??null)+metric('결합 t90',r.degree===null?'무재하':r.t90CombinedDays,r.degree===null?'':'일',b?.degree==null?null:b.t90CombinedDays),
        explanation:`<strong>간격은 배수 시간을, mv·하중·층두께는 최종 침하량을 결정합니다.</strong><br>${r.degree===null?'단위 재하 응답비:':'현재 압밀도:'} 수직만 ${fmt(r.vertical*100)}%, 방사형만 ${fmt(r.radial*100)}%, 결합 ${fmt(r.combined*100)}%입니다. 두 압밀도를 단순히 더하지 않습니다.<span class="hint">같은 mv에서 kh를 키우면 ch가 커집니다. 층두께 H를 늘려도 방사형 시간척도는 그대로지만 수직 배수와 최종 침하량은 달라집니다.${r.smear==='on'?` 교란 저항 Fs=${fmt(r.fs,2)}가 방사형 배수를 늦춥니다.`:''}</span>${r.degree===null?'<span class="notice">Δσ=0: 침하와 과잉수압은 0입니다. 그래프는 단위 재하에 대한 모형 응답비이며 실제 압밀도는 정의하지 않습니다.</span>':''}`,
        theory:`<div class="theory-grid"><div><div class="theory-formula">cv = kv/(mvγw) · ch = kh/(mvγw)<br>Uh = 1 − exp[−8ch t/(de²F)]<br>U = 1 − (1−Uv)(1−Uh)</div><p>cv=${r.cv.toExponential(2)} m²/s<br>ch=${r.ch.toExponential(2)} m²/s<br>Hdr=${fmt(r.hdr)} m · de=${fmt(r.influenceDiameter,3)} m</p></div><div class="theory-meta"><strong>속도와 최종량을 구별</strong><p>F = ln(de/dw) − 0.75 + Fs = ${fmt(r.f,3)}<br>S∞=mvΔσH=${fmt(r.finalSettlementMm)} mm<br>ūₑ=Δσ(1−U)=${fmt(r.averageExcess)} kPa</p><p>${r.degree===null?'단위 재하 응답의 90% 도달 시간<br>':''}수직만 t90=${fmt(r.t90VerticalDays)}일<br>방사형만 t90=${fmt(r.t90RadialDays)}일</p></div></div>`,
        method:`<h3>경계와 환산</h3><p>드레인 표면의 과잉수압은 0, 원형 영향 셀 외곽은 방사형 불투수입니다. 전층 관통·이상 배출구를 가정하고 셀 내 수직 변형률이 같은 평균 모형을 씁니다. 국부 수두장이나 실제 3D 유선은 계산하지 않습니다.</p><p>정사각형 배분 면적은 s², 정삼각형은 √3s²/2이고, de=2√(면적/π)로 환산합니다. 이는 FHWA의 1.13s와 1.05s를 면적에서 계산한 값입니다. 입력 dw는 환산 원형 지름이며 특정 판형 제품의 지름을 자동 선정하지 않습니다.</p><h3>해와 제한</h3><p>FHWA 식 2-1·2-2의 간소화 방사형 해에서 Fr=0을 씁니다. n=de/dw>5를 검사합니다. 교란을 켜면 Hansbo 근사 Fs=(kh/ks−1)ln(ds/dw)를 더합니다. 1≤ds/dw&lt;n, kh/ks≥1입니다. 교란 밖 천이영역·드레인 통수저항·부분 관입·막힘은 제외합니다.</p><p>수직 Uv는 균일 초기 수압에 대한 Terzaghi 1D 급수입니다. 수직·방사형 결합은 Carrillo 식이며 별도의 두 침하량을 합산하지 않습니다. k,mv가 일정하므로 cv와 ch는 같은 mv로 계산합니다. t는 초로 바꿔 사용합니다.</p><p>${source} · 인쇄 p.2-32–33, 식 2-1·2-2.<br>${smearSource}<br>${combinedSource}<br>${mvSource}</p>`}),
    },
    {key:'preloading',meta:{name:'선행재하와 단계재하',sub:'하중 이력·배수 시간·잔류 침하',group:'지반개량 / 재하와 응력이력',navGroup:'practice',words:'지반개량 선행재하 단계재하 preload surcharge 성토 제하 제거 반발 압밀 침하 공사 후 잔류 Cc Cr 선행압밀 응력이력',questions:[['staged','단계별 시간 응답'],['preload','배수 완료 후 효과']]},
      defaults:{permanentLoad:80,surcharge:40,addDays:30,removeDays:180,timeDays:200,logKv:-9,mv:.0003,thickness:8,drainage:'double',sigma0:80,preloadLoad:120,serviceLoad:100,e0:1,cc:.3,cr:.05},
      bounds:{...commonBounds,permanentLoad:[0,200,'영구하중','kPa'],surcharge:[0,200,'추가 성토하중','kPa'],addDays:[0,365,'추가 시점','일'],removeDays:[1,1000,'제거 시점','일'],timeDays:[0,2000,'관찰 시점','일'],sigma0:[10,500,'초기 유효응력','kPa'],preloadLoad:[0,300,'선행재하 하중','kPa'],serviceLoad:[0,200,'사용하중','kPa'],e0:[.3,2,'초기 간극비',''],cc:[.01,.8,'압축지수 Cc',''],cr:[0,.2,'재압축지수 Cr','']},
      activeFields:(d,q)=>q==='preload'?['preloadLoad','serviceLoad','cc','cr','sigma0','e0','thickness']:['surcharge','addDays','removeDays','timeDays','permanentLoad','logKv','mv','thickness'],
      labels:{...commonLabels,permanentLoad:['영구하중','kPa'],surcharge:['추가 성토','kPa'],addDays:['추가 시점','일'],removeDays:['제거 시점','일'],timeDays:['관찰 시점','일'],sigma0:['초기 σ′₀','kPa'],preloadLoad:['선행재하 하중','kPa'],serviceLoad:['사용하중','kPa'],e0:['초기 간극비',''],cc:['Cc',''],cr:['Cr','']},
      compute:(d,q)=>q==='preload'?Improvement.preload(d):Improvement.staged({...d,kv:10**d.logKv}),
      controls:(d,q)=>q==='preload'?`<p class="parameter-note">선행재하를 충분히 배수시킨 후 전량 제거하고, 그다음 사용하중을 가합니다. 옆 질문의 경과시간을 이 결과에 대입하지 않습니다.</p><div class="parameter-grid">${fieldControl('preloadLoad','선행재하 증가량 Δqpre',d.preloadLoad,0,300,5,'kPa','제거하는 임시 하중의 전량')}${fieldControl('serviceLoad','공사 후 사용하중 Δqservice',d.serviceLoad,0,200,5,'kPa')}${fieldControl('cc','압축지수 Cc',d.cc,.01,.8,.01,'')}${fieldControl('cr','재압축·팽창지수 Cr',d.cr,0,.2,.005,'','0 ≤ Cr ≤ Cc')}</div><details class="setting"><summary>초기 정규압밀 층</summary>${fieldControl('sigma0','초기 평균 유효응력 σ′₀',d.sigma0,10,500,5,'kPa')}${fieldControl('e0','초기 간극비 e₀',d.e0,.3,2,.05,'')}${fieldControl('thickness','초기 층두께 H₀',d.thickness,1,20,.5,'m')}</details>`:
        `<p class="parameter-note">시작 때 영구하중을 가하고, 임시 성토를 나중에 추가한 뒤 제거합니다. 이 질문은 일정 mv의 가역 선형 모형이며, 선행압밀 이력의 영구 효과는 다음 질문에서 다룹니다.</p><div class="parameter-grid">${fieldControl('surcharge','추가 성토하중',d.surcharge,0,200,5,'kPa')}${fieldControl('addDays','성토 추가 시점',d.addDays,0,365,1,'일')}${fieldControl('removeDays','추가 성토 제거 시점',d.removeDays,1,1000,1,'일','추가 시점보다 뒤여야 함')}${fieldControl('timeDays','현재 관찰 시점',d.timeDays,0,2000,1,'일')}</div><details class="setting"><summary>처음 가하는 하중과 층 물성</summary>${fieldControl('permanentLoad','t=0 영구하중',d.permanentLoad,0,200,5,'kPa')}${material(d)}<p class="note">이 시간 모형은 수직 배수만 적용합니다. 드레인에 따른 가속은 연직드레인 실험에서 별도로 비교합니다.</p></details>`,
      render:({result:r,baseline:b,question:q})=>q==='preload'?{
        title:'먼저 눌러 놓으면 공사 후에 남는 침하는 얼마나 달라질까요?',conditions:['초기 정규압밀·균질 대표 층','모든 단계 배수 완료','Cc·Cr 일정 · 동일 Cr로 제하·재재하','시간·2차압축 제외'],plotTitle:'미리 일어난 침하와 나중에 일어날 침하',comparisonPlot:true,chart:preloadChart(r,b),
        results:metric('선행재하 중 침하',r.preSettlementMm,'mm',b?.preSettlementMm??null)+metric('제거 후 반발량',r.reboundMm,'mm',b?.reboundMm??null)+metric('공사 후 추가 침하',r.postServiceSettlementMm,'mm',b?.postServiceSettlementMm??null,true)+metric('미시행 대비 감소량',r.reductionMm,'mm',b?.reductionMm??null),
        explanation:`<strong>선행재하는 침하의 일부를 공사 전으로 옮기고, 이후 하중을 재압축 경로로 받게 합니다.</strong><br>제거 후에도 남는 선행 침하는 ${fmt(r.retainedSettlementMm)} mm이며, 그때 σ′p=${fmt(r.preconsolidationAfterRemoval)} kPa입니다. ${r.serviceStress>r.peak?'사용하중이 이 응력을 넘으므로 초과 구간은 다시 Cc로 압축됩니다.':'사용하중이 과거 최대 응력 이내이므로 Cr로 재압축됩니다.'}<span class="hint">일정 Cr 모형에서는 선행재하가 사용하중 이상이면, 더 큰 선행재하가 공사 후 추가 침하를 계속 낮추지는 않습니다. 강도 증가량이나 허용 성토높이는 계산하지 않습니다.</span>`,
        theory:`<div class="theory-grid"><div><div class="theory-formula">σ′p = σ′₀ + Δqpre<br>Δepre = Cc log₁₀(σ′p/σ′₀)<br>Δerebound = Cr log₁₀(σ′p/σ′₀)</div><p>선행 압축 후 e=${fmt(r.preloadE,3)}<br>전량 제거 후 e=${fmt(r.unloadedE,3)}<br>사용하중 후 e=${fmt(r.serviceE,3)}</p></div><div class="theory-meta"><strong>공사 후 침하만 분리</strong><p>Spost = H₀ Δepost/(1+e₀)<br>Δepost = Cr log₁₀[min(σ′s,σ′p)/σ′₀]<br>+ Cc max[0, log₁₀(σ′s/σ′p)]</p><p>선행재하 미시행: ${fmt(r.withoutPreloadSettlementMm)} mm<br>최종 OCR=${fmt(r.finalOCR,2)}</p></div></div>`,
        method:`<h3>시간 모형과 다른 계산</h3><p>초기 σ′p=σ′₀인 층에 선행재하 하중을 가해 완전히 배수시키고, 전량 제거하여 팽창도 완료한 다음 사용하중을 가합니다. 일시적인 과잉수압으로 선행압밀응력을 정하지 않습니다. 유한 시간에 정확히 U=100%가 된다는 뜻이 아니라, 배수 완료의 극한 상태들을 비교합니다.</p><p>간극비는 Cc·Cr 이선형 e–logσ′ 관계이며 모든 변위는 H₀/(1+e₀)라는 같은 흙입자 높이를 기준으로 환산합니다. 선행재하 중 침하, 제거 때 반발, 공사 후 추가 침하를 나누어 표시합니다. 공사 후 침하는 미시행 조건과 동일한 사용하중으로 비교합니다.</p><p>균질 층의 대표 평균 응력 모형이며 응력의 깊이별 분포, 초기 과압밀, 불완전 배수, 비선형 k·mv, 2차압축, 측방변형, 성토 안정은 포함하지 않습니다.</p><p>${stressSource} · 식 7-2·7-4의 응력 구간별 압축을 위 하중 경로에 적용했습니다.<br>${source} · 선행재하·추가 성토의 적용 목적과 시공 순서.</p>`
      }:{
        title:'같은 하중도 언제 더하고 빼느냐에 따라 수압과 침하가 달라질까요?',conditions:['포화·1D 수직 배수','순간 하중 3개 중첩','k·mv·H 일정 · 재하·제하 동일 mv','초기 추가 수압 0'],plotTitle:'재하 일정과 압밀 응답',comparisonPlot:true,chart:stagedChart(r,b),
        results:metric('현재 총 추가하중',r.load,'kPa',b?.load??null)+metric('평균 과잉수압 ūₑ',r.averageExcess,'kPa',b?.averageExcess??null)+metric('현재 침하',r.settlementMm,'mm',b?.settlementMm??null,true)+metric('영구하중만의 현재 침하',r.withoutSurchargeMm,'mm',b?.withoutSurchargeMm??null),
        explanation:`<strong>${r.phase==='removed'?'성토를 제거해도 지반 변형은 순간적으로 원상복구되지 않습니다.':r.phase==='surcharge'?'추가 성토의 압밀 시계는 성토를 더한 날부터 새로 시작합니다.':'먼저 가한 영구하중은 추가 성토 전에 이미 압밀을 시작합니다.'}</strong><br>현재 평균 유효응력 증가량은 q−ūₑ=${fmt(r.effectiveIncrement)} kPa입니다. ${r.averageExcess<0?'제하로 생긴 음의 과잉수압은 정수압보다 낮다는 뜻이며, 절대 수압이나 불포화 흡입력을 의미하지 않습니다.':'남은 평균 과잉수압만큼 하중이 아직 흙 골격으로 전달되지 않았습니다.'}<span class="hint">이 가역 모형의 장기 침하는 영구하중에 해당하는 ${fmt(r.finalSettlementMm)} mm로 돌아갑니다. 실제 선행재하의 영구적인 응력이력 효과는 ‘배수 완료 후 효과’에서 따로 확인합니다.</span>`,
        theory:`<div class="theory-grid"><div><div class="theory-formula">S(t) = mv H Σ[Δqⱼ U(t−tⱼ)]<br>ūₑ(t) = Σ[Δqⱼ (1−U(t−tⱼ))]</div><p>시작: +${fmt(r.permanentLoad)} kPa<br>${fmt(r.addDays,0)}일: +${fmt(r.surcharge)} kPa<br>${fmt(r.removeDays,0)}일: −${fmt(r.surcharge)} kPa</p></div><div class="theory-meta"><strong>각 단계의 시간 원점</strong><p>t&lt;tⱼ인 항은 아직 작용하지 않습니다.<br>cv=${r.cv.toExponential(2)} m²/s<br>Hdr=${fmt(r.hdr)} m · 단일 단계 t90=${fmt(r.t90Days)}일</p><p>q=Δσ′평균+ūₑ<br>최종 영구하중 침하=${fmt(r.finalSettlementMm)} mm</p></div></div>`,
        method:`<h3>명시적 선형 중첩</h3><p>Terzaghi 일정 계수 확산식의 계단 응답 U(t)에 각 하중 증가량을 곱해 합합니다. 제거는 음의 하중 증가량입니다. 재하·제하에서 같은 mv·cv와 동일 경계를 사용하므로 선형 중첩이 가능하며, Cc/Cr 소성 이력을 이 시간곡선에 섞지 않습니다.</p><p>처음 추가 수압 0에서 t=0에 영구하중을 가합니다. 각 재하 직후 추가 하중만큼 과잉수압이 증가하고, 제하 직후 그만큼 감소합니다. U(0)=0이므로 순간 침하 점프는 없습니다. 곡선에는 변화 시점의 직전·직후를 모두 넣어 계단 하중을 표시합니다.</p><p>입력 시점은 하중 이력이며 현재 관찰시간보다 뒤인 단계도 미래 계획으로 그립니다. mv(q영구+q추가)≤0.10은 구현의 소변형 범위이지 설계 허용값이 아닙니다. 음의 과잉수압의 절대 수압·공동화 여부는 이 평균 모형으로 판단하지 않습니다. 단계별 허용 성토, 강도 증가, 사면 안정 또는 현장 시공 승인을 제공하지 않습니다.</p><p>${timeSource} · 일정 물성의 선형 시간 재하 모형.<br>${stressSource} · Terzaghi 1D 압밀.<br>${mvSource}</p>`
      },
    },
  ];
})();
