const InvestigationLabs = (() => {
 const sptSource='https://highways.fhwa.dot.gov/sites/fhwa.dot.gov/files/FHWA-IF-02-034.pdf';
 const cnSource='https://www.fhwa.dot.gov/engineering/geotech/pubs/nhi06088.pdf';
 const cptSource='https://www.cpt-robertson.com/PublicationsPDF/CPT-Guide-7th-Final-SMALL.pdf';
 const link=(url,name)=>`<a href="${url}" target="_blank" rel="noopener">${name}</a>`;
 const colors=['#A6ADB8','#00A4C2','#0F6FFF','#7543C5'];
 function basisSelect(id,d,options){return `<div class="select-row"><label for="${id}-basis">입력값 종류</label><select id="${id}-basis" data-field="basis">${options.map(([v,n])=>`<option value="${v}" ${d.basis===v?'selected':''}>${n}</option>`).join('')}</select></div>`;}
 function stageChart(r,b){
  const max=Math.max(...r.stages.map(p=>p.value),...(b?b.stages.map(p=>p.value):[]),1)*1.18,x=v=>173+v/max*370;
  let svg='<text x="173" y="24" style="font-size:18px">입력값 → 시험 보정 → 상재 정규화</text>';
  for(let i=0;i<=4;i++){const v=max*i/4;svg+=`<line class="grid" x1="${x(v)}" x2="${x(v)}" y1="45" y2="288"/><text x="${x(v)}" y="311" text-anchor="middle" style="font-size:16px">${fmt(v,0)}</text>`;}
  r.stages.forEach((p,i)=>{const y=58+i*54;svg+=`<text x="162" y="${y+20}" text-anchor="end" style="font-size:18px">${p.label}</text><rect x="173" y="${y}" width="${p.value/max*370}" height="30" rx="3" fill="${colors[r.basis==='raw'?i:i+2]}"/><text x="${x(p.value)+7}" y="${y+21}" style="font-size:18px">${fmt(p.value,2)}</text>`;
   const prior=b?.stages.find(v=>v.label===p.label);if(prior)svg+=`<rect x="173" y="${y-3}" width="${prior.value/max*370}" height="36" fill="none" stroke="#737373" stroke-dasharray="5 4" stroke-width="2"/>`;
  });
  return svgWrap(svg,'SPT 측정·에너지 보정·시험조건 보정·상재 정규화 단계의 계산값')+`<p class="chart-caption">${r.basis==='raw'?`에너지 ${fmt(r.energyFactor,2)}배 · 시험조건 ${fmt(r.proceduralFactor,3)}배 · 상재 CN ${fmt(r.cn,3)}배`:'입력 N60에 시험 보정은 다시 적용하지 않습니다.'}${b?' · 회색 점선은 저장한 기준의 같은 단계입니다.':''}</p>`;
 }
 function cptChart(r,b){
  if(!r.suApplicable)return `<div class="notice"><strong>강도 환산 범위 밖</strong><p>qt ${fmt(r.qt,1)} − σv0 ${fmt(r.totalOverburden,1)} = qnet ${fmt(r.qnet,1)} kPa</p><p>${r.interpretation} 값을 0으로 바꾸거나 음의 강도로 표시하지 않습니다.</p></div>`;
  const points=[r.nkt,r.nktMin,r.nktMax,...(b?.suApplicable?[b.nkt,b.nktMin,b.nktMax]:[])];
  const xmin=Math.min(5,...points)*.9,xmax=Math.max(25,...points)*1.08,ymax=Math.max(r.qnet,...(b?.suApplicable?[b.qnet]:[]))/xmin*1.05;
  const x=v=>68+(v-xmin)/(xmax-xmin)*520,y=v=>278-v/ymax*224;
  const curve=qnet=>Array.from({length:91},(_,i)=>{const n=xmin+(xmax-xmin)*i/90;return `${i?'L':'M'}${x(n)} ${y(qnet/n)}`;}).join('');
  let svg=`<text x="68" y="23" style="font-size:18px">환산 비배수강도 su (kPa)</text><rect x="${x(r.nktMin)}" y="54" width="${x(r.nktMax)-x(r.nktMin)}" height="224" fill="#E5EFFD"/>`;
  for(let i=0;i<=4;i++){const v=ymax*i/4;svg+=`<line class="grid" x1="68" x2="588" y1="${y(v)}" y2="${y(v)}"/><text x="59" y="${y(v)+5}" text-anchor="end" style="font-size:16px">${fmt(v,0)}</text>`;}
  for(let i=0;i<=5;i++){const n=xmin+(xmax-xmin)*i/5;svg+=`<text x="${x(n)}" y="303" text-anchor="middle" style="font-size:16px">${fmt(n,1)}</text>`;}
  svg+=`<path d="${curve(r.qnet)}" fill="none" stroke="#0F6FFF" stroke-width="3"/>`;
  if(b?.suApplicable)svg+=`<path d="${curve(b.qnet)}" fill="none" stroke="#737373" stroke-width="2" stroke-dasharray="5 4"/><circle cx="${x(b.nkt)}" cy="${y(b.su)}" r="6" fill="white" stroke="#737373" stroke-width="2"/>`;
  [r.nktMin,r.nktMax].forEach(n=>{svg+=`<circle cx="${x(n)}" cy="${y(r.qnet/n)}" r="4" fill="#0F6FFF"/>`;});
  svg+=`<line x1="${x(r.nkt)}" x2="${x(r.nkt)}" y1="${y(r.su)}" y2="278" stroke="#7543C5" stroke-dasharray="4 3"/><circle cx="${x(r.nkt)}" cy="${y(r.su)}" r="6" fill="#7543C5"/><text x="588" y="329" text-anchor="end" style="font-size:18px">지정 상관계수 Nkt</text>`;
  return svgWrap(svg,'순저항을 고정한 Nkt와 환산 비배수강도의 반비례 곡선 및 사용자가 지정한 계수 범위')+`<p class="chart-caption">파란 띠: Nkt ${fmt(r.nktMin,1)}~${fmt(r.nktMax,1)} → su ${fmt(r.suMin,1)}~${fmt(r.suMax,1)} kPa. 확률·신뢰구간이 아닌 지정 계수의 비교 범위입니다.${b?.suApplicable?' 회색 점선·빈 점: 저장한 기준의 곡선·Nkt.':''}</p>`;
 }
 const sptDefaults={basis:'raw',reading:20,energyRatio:75,effectiveOverburden:100,boreholeFactor:1,rodFactor:.9,samplerFactor:1};
 const sptBounds={reading:[0,200,'입력 N 또는 N60',''],energyRatio:[5,100,'실측 에너지비 ER','%'],effectiveOverburden:[5,1000,'유효상재응력 σ′v0','kPa'],boreholeFactor:[.5,1.5,'공경 보정 CB',''],rodFactor:[.5,1.5,'롯드 보정 CR',''],samplerFactor:[.5,1.5,'샘플러 보정 CS','']};
 const cptDefaults={basis:'qc',tipResistanceMPa:1,u2:200,areaRatio:.8,totalOverburden:200,nkt:14,nktMin:10,nktMax:18};
 const cptBounds={tipResistanceMPa:[0,10,'선단저항','MPa'],u2:[-100,2000,'측정 간극수압 u2','kPa'],areaRatio:[.1,1,'교정 면적비 a',''],totalOverburden:[0,2000,'총상재응력 σv0','kPa'],nkt:[1,40,'현재 상관계수 Nkt',''],nktMin:[1,40,'비교 Nkt 하한',''],nktMax:[1,40,'비교 Nkt 상한','']};
 return [{key:'spt-corrections',meta:{name:'SPT 보정의 단계',sub:'N · N60 · (N1)60',group:'현장과 판단 / 조사와 정수',navGroup:'practice',words:'조사 표준관입 SPT N N60 N160 에너지 보정 시험조건 상재 정규화',questions:[['correction','측정값에서 정규화까지']]},defaults:sptDefaults,bounds:sptBounds,
  labels:{basis:['입력값 종류',''],...Object.fromEntries(Object.entries(sptBounds).map(([k,v])=>[k,[v[2],v[3]]]))},
  activeFields:d=>['reading','effectiveOverburden',...(d.basis==='raw'?['energyRatio','boreholeFactor','rodFactor','samplerFactor']:[])],
  compute:d=>Investigation.spt(d),
  controls(d){return basisSelect('spt',d,[['raw','측정 N · 시험 보정 전'],['n60','이미 시험 보정한 N60']])+fieldControl('reading',d.basis==='raw'?'측정 N · 마지막 300 mm':'입력 N60',d.reading,0,200,d.basis==='raw'?1:.1,'',d.basis==='raw'?'150 mm 예비 관입 후, 두 구간 150+150 mm의 타격수 합입니다.':'ER·CB·CR·CS 보정이 끝난 값. 이미 상재 정규화한 (N1)60을 넣지 않습니다.')+(d.basis==='raw'?fieldControl('energyRatio','실측 에너지비 ER',d.energyRatio,5,100,1,'%','현재 N을 고정하여 60% 기준으로 환산합니다. 해머 이름으로 자동 추정하지 않습니다.'):'')+fieldControl('effectiveOverburden','유효상재응력 σ′v0',d.effectiveOverburden,5,1000,5,'kPa','총응력에서 정수압 등을 반영한 유효응력. N60에는 영향을 주지 않고 CN만 바꿉니다.')+(d.basis==='raw'?`<details class="setting"><summary>시험조건 계수 · CB ${fmt(d.boreholeFactor,2)} / CR ${fmt(d.rodFactor,2)} / CS ${fmt(d.samplerFactor,2)}</summary>${fieldControl('boreholeFactor','공경 보정 CB',d.boreholeFactor,.5,1.5,.05,'','선택한 보정 체계의 수동 계수입니다.')}${fieldControl('rodFactor','롯드 보정 CR',d.rodFactor,.5,1.5,.05,'','이미 반영한 효과를 다시 곱하지 않습니다.')}${fieldControl('samplerFactor','샘플러 보정 CS',d.samplerFactor,.5,1.5,.05,'','샘플러 형식만으로 값을 자동 결정하지 않습니다.')}<p class="parameter-note">초깃값은 계산 관계를 보기 위한 예시입니다. 1은 이 단계에서 추가 보정이 없다는 뜻이며, 현장 조건이 표준임을 확인한 값은 아닙니다.</p></details>`:'<p class="parameter-note">이미 반영된 에너지·시험조건 보정은 건너뜁니다. 입력 종류를 바꾸면 같은 숫자의 의미가 바뀌므로 원기록의 값과 표기를 함께 확인하세요.</p>');},
  render({result:r,baseline:b}){return {title:'N60과 (N1)60은 무엇을 각각 보정한 값일까요?',conditions:['측정 N 고정 비교','시험계수 수동 지정','Peck 상재 정규화'],plotTitle:'보정 단계별 값',comparisonPlot:true,chart:stageChart(r,b),
   results:metric('시험 보정 N60',r.n60,'',b?.n60??null,true,2)+metric('상재계수 CN',r.cn,'',b?.cn??null,false,3)+metric('정규화 (N1)60',r.n160,'',b?.n160??null,false,2),
   explanation:`<strong>시험 보정은 측정 조건을, 상재 정규화는 유효응력 수준을 맞춥니다.</strong><br>σ′v0만 바꾸면 N60은 ${fmt(r.n60,2)}로 유지되고 CN·(N1)60이 바뀝니다. 정규화 여부는 연결할 경험식이 요구하는 N의 정의를 따라야 합니다.<span class="hint">ER을 높였을 때 환산 N60이 커지는 것은 동일한 측정 N을 고정한 비교입니다. 같은 지반을 더 큰 에너지로 실제 시험하면 기록 N 자체도 달라질 수 있습니다.</span>${r.cnCapped?'<p class="notice">낮은 상재응력에서 출처의 CN 상한 2.0이 적용되었습니다. 입력 유효응력을 바꾼 것이 아닙니다.</p>':''}`,
   theory:`<h3>측정에서 시험 보정까지</h3><div class="theory-formula">${r.basis==='raw'?`CE = ER/60 = ${fmt(r.energyFactor,3)}<br>N60 = N × CE × CB × CR × CS<br>= ${r.reading} × ${fmt(r.energyFactor,3)} × ${fmt(r.boreholeFactor,2)} × ${fmt(r.rodFactor,2)} × ${fmt(r.samplerFactor,2)} = ${fmt(r.n60,2)}`:`이미 시험 보정한 N60 = ${fmt(r.n60,2)}<br>CE·CB·CR·CS를 다시 곱하지 않습니다.`}</div><h3>상재 정규화 · 별도의 단계</h3><div class="theory-formula">p0 = σ′v0 / 95.7605 = ${fmt(r.stressTsf,4)} tsf<br>CN = min[2.0, 0.77 log10(20/p0)] = ${fmt(r.cn,3)}<br>(N1)60 = CN × N60 = ${fmt(r.cn,3)} × ${fmt(r.n60,2)} = ${fmt(r.n160,2)}</div><p class="theory-meta">이 경험식의 p0 단위는 tsf입니다. kPa를 그대로 넣으면 다른 결과가 됩니다. 1 tsf는 약 95.76 kPa이며, 식의 반올림 상수 때문에 p0=1 tsf에서도 CN은 정확히 1이 아닙니다.</p>`,
   method:`<p>${link(sptSource,'FHWA-IF-02-034 (2002), §4.4.2~4.4.3, 식 3')}의 시험조건 곱을 사용합니다. 공식 보관 문헌이며 현행 기준 적합 판정을 뜻하지 않습니다. ER과 각 계수는 사용자가 선택한 보정 절차·기록을 반영하는 수동 입력입니다.</p><p>${link(cnSource,'FHWA NHI-06-088 (2006), §3.7.1~3.7.2, 식 3-2~3-3')}에 수록된 Peck 상재 정규화만 구현했습니다. 다른 CN식·액상화용 세립분 보정과 섞지 않습니다. 시멘트화된 지반 등에는 이 정규화가 적합하지 않을 수 있습니다.</p><p>완전한 300 mm 관입의 N을 전제로 합니다. 관입거부의 “50회/100 mm”를 50이나 150으로 바꾸어 넣지 않습니다. 자중 관입 WOH/WOR는 별도 시험 상태이며, N=0 경계 계산만으로 그 상태를 대신하지 않습니다. 자갈·실트·민감 점토에서 측정과 해석의 한계가 큽니다. 이 실험은 N으로 φ′·su·E·지반 종류를 자동 결정하지 않습니다.</p>`};}
 },{key:'cpt-interpretation',meta:{name:'CPT와 강도 범위',sub:'qc → qt → qnet → su',group:'현장과 판단 / 조사와 정수',navGroup:'practice',words:'조사 CPT CPTu 콘 qc qt qnet u2 Nkt 비배수강도 상관계수 불확실성',questions:[['interpretation','측정 저항과 강도 환산']]},defaults:cptDefaults,bounds:cptBounds,
  labels:{basis:['입력값 종류',''],...Object.fromEntries(Object.entries(cptBounds).map(([k,v])=>[k,[v[2],v[3]]]))},
  activeFields:d=>['tipResistanceMPa','totalOverburden','nkt','nktMin','nktMax',...(d.basis==='qc'?['u2','areaRatio']:[])],compute:d=>Investigation.cpt(d),
  controls(d){return basisSelect('cpt',d,[['qc','측정 qc · 수압 보정 전'],['qt','이미 수압 보정한 qt']])+fieldControl('tipResistanceMPa',d.basis==='qc'?'측정 선단저항 qc':'보정 선단저항 qt',d.tipResistanceMPa,0,10,.05,'MPa','1 MPa = 1000 kPa. qnet·Qt와 구별합니다.')+(d.basis==='qc'?fieldControl('u2','콘 어깨의 측정 수압 u2',d.u2,-100,2000,10,'kPa','u2 전체 측정값입니다. 초과수압 Δu = u2−u0 또는 정수압 u0를 대신 넣지 않습니다.')+fieldControl('areaRatio','교정 면적비 a',d.areaRatio,.1,1,.01,'','기기의 실내 교정값. (1−a)u2만큼 qc를 보정합니다.'):'<p class="parameter-note">qt에는 수압 보정이 포함되어 있습니다. u2·면적비 a를 다시 적용하지 않습니다.</p>')+fieldControl('totalOverburden','원지반 총상재응력 σv0',d.totalOverburden,0,2000,10,'kPa','qnet 계산은 총응력을 차감합니다. 유효응력 σ′v0가 아닙니다.')+fieldControl('nkt','현재 상관계수 Nkt',d.nkt,1,40,1,'','비배수 관입이 성립하는 세립토의 지정 계수입니다. 자동 추천값이 아닙니다.')+`<details class="setting"><summary>계수 비교 범위 · Nkt ${fmt(d.nktMin,1)}~${fmt(d.nktMax,1)}</summary>${numericRow('nktMin','비교 Nkt 하한',d.nktMin,'',1,40,.5)}${numericRow('nktMax','비교 Nkt 상한',d.nktMax,'',1,40,.5)}<p class="parameter-note">초깃값 10~18은 출처에 소개된 전형적 범위의 학습 예시입니다. 특정 현장의 추천 범위·신뢰구간이 아닙니다. 현재 Nkt는 이 비교 범위 밖에서도 따로 선택할 수 있습니다.</p></details>`;},
  render({result:r,baseline:b}){return {title:'같은 콘 저항에서 왜 하나의 강도만 정해지지 않을까요?',conditions:['비배수 세립토 상관식','총응력 차감','Nkt 수동 지정'],plotTitle:'지정 Nkt에 따른 비배수강도',comparisonPlot:r.suApplicable&&!!b?.suApplicable,chart:`<div class="relation-strip">qt ${fmt(r.qt,1)} − σv0 ${fmt(r.totalOverburden,1)} = qnet ${fmt(r.qnet,1)} kPa</div>`+cptChart(r,b),
   results:metric('보정 저항 qt',r.qt,'kPa',b?.qt??null)+metric('순저항 qnet',r.qnet,'kPa',b?.qnet??null)+metric('환산 비배수강도 su',r.suApplicable?r.su:'적용 밖',r.suApplicable?'kPa':'',b?.su??null,true),
   explanation:`<strong>수압·기기 형상 보정과 지반 강도의 경험적 환산은 서로 다른 단계입니다.</strong><br>${r.suApplicable?`같은 qnet에서 Nkt를 2배로 지정하면 su는 절반이 됩니다. 지정 범위의 결과는 ${fmt(r.suMin,1)}~${fmt(r.suMax,1)} kPa이며, 이는 한 가지 “확정 강도”가 아닙니다.`:r.interpretation}<span class="hint">su는 하중 방향·속도·응력이력·이방성에 따라 달라질 수 있습니다. 배수성 모래나 부분 배수 관입에 이 식을 자동 적용하지 않습니다.</span>`,
   theory:`<h3>압력 단위와 보정 순서</h3><div class="theory-formula">${r.basis==='qc'?`qc = ${fmt(r.tipResistanceMPa,3)} MPa = ${fmt(r.inputKPa,1)} kPa<br>qt = qc + (1−a)u2<br>= ${fmt(r.inputKPa,1)} + (1−${fmt(r.areaRatio,2)}) × ${fmt(r.u2,1)} = ${fmt(r.qt,1)} kPa`:`이미 수압 보정한 qt = ${fmt(r.tipResistanceMPa,3)} MPa = ${fmt(r.qt,1)} kPa<br>(1−a)u2를 다시 더하지 않습니다.`}<br>qnet = qt − σv0 = ${fmt(r.qt,1)} − ${fmt(r.totalOverburden,1)} = ${fmt(r.qnet,1)} kPa</div><div class="theory-formula">${r.suApplicable?`su = qnet / Nkt = ${fmt(r.qnet,1)} / ${fmt(r.nkt,1)} = ${fmt(r.su,2)} kPa<br>범위 하한 = qnet / Nkt,max = ${fmt(r.suMin,2)} kPa<br>범위 상한 = qnet / Nkt,min = ${fmt(r.suMax,2)} kPa`:'qnet ≤ 0: 이 상관식의 강도 환산을 표시하지 않습니다.'}</div><p class="theory-meta">qnet는 kPa 단위의 순저항입니다. Qt=(qt−σv0)/σ′v0로 정의하는 무차원 정규화 콘 저항과 다릅니다. 이 화면에서는 Qt·토질 자동 분류·SPT 환산을 계산하지 않습니다.</p>`,
   method:`<p>${link(cptSource,'Robertson & Cabal, Guide to Cone Penetration Testing, 7th ed. (2022)')} p.23의 면적 보정, p.41~42의 비배수강도 관계를 따릅니다. 면적비 a는 콘의 교정값이고 u2는 콘 어깨의 측정 수압입니다. 음의 u2를 임의로 0에 맞추지 않습니다.</p><p>Nkt는 재료·민감도·선택한 강도 정의에 따라 달라지는 경험계수입니다. 현장과 관련된 양질의 실내·현장 시험에 의한 보정 없이 결과를 추천 설계정수로 제시하지 않습니다. 지정 Nkt의 폭은 상관계수 선택에 의한 차이만 표현하며, 측정오차·층상 변화·공간 변동을 모두 포함한 불확실성 평가가 아닙니다.</p>`};}
 }];
})();
