const PileLabs=(()=>{
 const manual='https://www.fhwa.dot.gov/engineering/geotech/pubs/gec12/nhi16009_v1.pdf',groupSource='https://www.fhwa.dot.gov/engineering/geotech/pubs/nhi06089.pdf',dragSource='https://www.fhwa.dot.gov/publications/research/infrastructure/structures/bridge/17060/index.cfm',nchrp='https://www.nationalacademies.org/read/27863/chapter/2';
 const link=(url,label)=>`<a href="${url}" target="_blank" rel="noopener">${label}</a>`,nice=v=>{if(v<=0)return 1;const s=10**Math.floor(Math.log10(v));return Math.ceil(v/s)*s;},path=(rows,x,y)=>rows.map((p,i)=>`${i?'L':'M'}${x(p).toFixed(2)} ${y(p).toFixed(2)}`).join(' ');
 const fields={length:['길이 L',5,40,1,'m','지표에서 선단까지 길이'],diameter:['직경 D',.3,1.2,.05,'m','원형 중실 말뚝 단면'],layerDepth:['위층 두께 H1',0,35,.5,'m','0이면 전체가 아래층, L보다 크면 전체가 위층'],tau1:['위층 단위 주면저항 τu,1',0,150,5,'kPa','지정한 극한저항 · 공법·시험에 맞춰 채택할 값'],tau2:['아래층 단위 주면저항 τu,2',0,200,5,'kPa','실제 관입한 아래층 길이에만 적용'],toeStress:['선단 단위저항 qb,u',0,6000,100,'kPa','현재 선단 지층에 대해 별도로 지정'],headLoad:['두부 압축하중 Q',0,3000,50,'kN','자중을 제외한 말뚝 두부 작용하중'],modulus:['말뚝 탄성계수 Ep',5,80,1,'GPa','흙의 E와 다른 말뚝 재료 강성'],shaft50:['주면 50% 동원변위 t50',.5,20,.5,'mm','같은 극한저항에서 작을수록 초기 전달강성이 큽니다.'],toe50:['선단 50% 동원변위 b50',2,100,1,'mm','선단저항 절반을 동원하는 상대침하'],groundSettlement:['지표의 지반침하 s0',0,150,5,'mm','직접 지정한 침하 · 압밀해석 결과를 자동 생성하지 않습니다.'],settlementDepth:['침하가 0이 되는 깊이 Hs',1,35,1,'m','지반침하가 깊이에 따라 선형 감소하는 예제']};
 const ctl=(d,k)=>{const [l,min,max,step,u,h]=fields[k];return fieldControl(k,l,d[k],min,max,step,u,h);};
 const caps=d=>['length','diameter','layerDepth',...(d.layerDepth>0?['tau1']:[]),...(d.length>d.layerDepth?['tau2']:[]),'toeStress'];
 function controls(d,q){const primary=q==='capacity'?['length','diameter','layerDepth','tau1','tau2','toeStress']:q==='transfer'?['headLoad','modulus','shaft50','toe50']:['groundSettlement','settlementDepth','headLoad','length','modulus'];const extra=q==='capacity'?[]:['layerDepth','tau1','tau2','toeStress',...(q==='downdrag'?['toe50','diameter','shaft50']:['length','diameter'])];return `<div class="parameter-grid">${primary.map(k=>ctl(d,k)).join('')}</div>${extra.length?`<details class="setting"><summary>지층 저항과 추가 전달조건</summary>${extra.map(k=>ctl(d,k)).join('')}</details>`:''}<p class="parameter-note">입력 저항·동원변위는 가상 예제값입니다. 공법이나 흙 이름만으로 자동 산정한 설계정수가 아닙니다.</p>`;}
 function capacityChart(r,b){const y=z=>52+238*z/40,w=r.diameter*50,max=nice(Math.max(r.shaftUpper,r.shaftLower,r.toeUltimate,b?.shaftUpper||0,b?.shaftLower||0,b?.toeUltimate||0,1)),x=v=>340+260*v/max;let s='<text x="50" y="26">관입한 길이 · 깊이(m)</text><text x="340" y="26">극한저항 기여 (kN)</text>';
  s+=`<rect x="62" y="52" width="198" height="238" fill="var(--color-bg-surface-alt-1)"/><rect x="62" y="${y(Math.min(r.layerDepth,40))}" width="198" height="${290-y(Math.min(r.layerDepth,40))}" fill="var(--color-action-primary)" opacity=".07"/>`;
  for(let z=0;z<=40;z+=10)s+=`<text x="50" y="${y(z)+4}" text-anchor="end">${z}</text><line class="grid" x1="62" x2="260" y1="${y(z)}" y2="${y(z)}"/>`;
  if(b)s+=`<rect x="${160-b.diameter*25}" y="52" width="${b.diameter*50}" height="${y(b.length)-52}" fill="none" stroke="var(--color-text-muted)" stroke-dasharray="4 4"/>`;
  s+=`<rect x="${160-w/2}" y="52" width="${w}" height="${y(r.length)-52}" fill="var(--color-action-primary)" opacity=".8"/><line x1="${160-w/2}" x2="${160+w/2}" y1="${y(r.length)}" y2="${y(r.length)}" stroke="var(--color-accent-purple)" stroke-width="4"/><text x="${160+w/2+10}" y="${y(r.length)-4}">L=${fmt(r.length)} m</text>`;
  for(const [key,label,cy,color]of [['shaftUpper','위층 주면',85,'var(--color-action-primary)'],['shaftLower','아래층 주면',165,'var(--color-action-primary)'],['toeUltimate','선단',245,'var(--color-accent-purple)']]){s+=`<text x="340" y="${cy-14}">${label} · ${fmt(r[key])}</text><rect x="340" y="${cy}" width="${x(r[key])-340}" height="18" rx="3" fill="${color}"/>`;if(b)s+=`<rect x="340" y="${cy+22}" width="${x(b[key])-340}" height="5" fill="none" stroke="var(--color-text-muted)" stroke-dasharray="3 3"/>`;}
  s+=`<text x="160" y="317" text-anchor="middle">D=${fmt(r.diameter,2)} m · 폭 확대</text><text x="600" y="317" text-anchor="end">막대 최대 ${fmt(max,0)} kN</text>`;return svgWrap(s,'두 층 관입길이와 주면 및 선단 극한저항 기여')+'<div class="chart-caption">깊이 축 0–40 m · 말뚝 폭은 확대 표시 · 보라: 선단저항</div>';
 }
 function transferChart(r,b){const depthMax=Math.max(r.length,b?.length||0),forceMax=nice(Math.max(r.maxForce,b?.maxForce||0,1)),xN=v=>55+245*v/forceMax,yZ=z=>55+235*z/depthMax,curve=r.curve||[],maxS=nice(Math.max(...curve.map(p=>p.settlement*1000),...(b?.curve||[]).map(p=>p.settlement*1000),r.headSettlement*1000,1)),maxQ=nice(Math.max(...curve.map(p=>p.load),...(b?.curve||[]).map(p=>p.load),r.headLoad,1)),xS=v=>390+220*v/maxS,yQ=v=>290-235*v/maxQ;let s='<text x="55" y="27">축력 N (kN) · 깊이 z(m)</text><text x="390" y="27">Q–두부침하 모형 곡선</text>';
  for(let i=0;i<=2;i++){const N=forceMax*i/2,mm=maxS*i/2;s+=`<line class="grid" x1="${xN(N)}" x2="${xN(N)}" y1="55" y2="290"/><text x="${xN(N)}" y="315" text-anchor="middle">${fmt(N,0)}</text><line class="grid" x1="${xS(mm)}" x2="${xS(mm)}" y1="55" y2="290"/><text x="${xS(mm)}" y="315" text-anchor="middle">${fmt(mm,0)}</text>`;}
  for(let i=0;i<=3;i++){const z=depthMax*i/3,Q=maxQ*i/3;s+=`<line class="grid" x1="55" x2="300" y1="${yZ(z)}" y2="${yZ(z)}"/><text x="45" y="${yZ(z)+4}" text-anchor="end">${fmt(z,0)}</text><line class="grid" x1="390" x2="610" y1="${yQ(Q)}" y2="${yQ(Q)}"/><text x="380" y="${yQ(Q)+4}" text-anchor="end">${fmt(Q,0)}</text>`;}
  if(b)s+=`<path class="baseline" d="${path(b.profile,p=>xN(p.force),p=>yZ(p.z))}"/>${b.curve?`<path class="baseline" d="${path(b.curve,p=>xS(p.settlement*1000),p=>yQ(p.load))}"/>`:''}`;
  s+=`<path class="curve" d="${path(r.profile,p=>xN(p.force),p=>yZ(p.z))}"/><path class="curve" d="${path(curve,p=>xS(p.settlement*1000),p=>yQ(p.load))}"/><circle cx="${xS(r.headSettlement*1000)}" cy="${yQ(r.headLoad)}" r="5" fill="var(--color-action-primary)" stroke="white" stroke-width="1.5"/><text x="610" y="334" text-anchor="end">가로: 침하(mm) · 세로: Q(kN)</text>`;
  return svgWrap(s,'말뚝 깊이에 따른 축력과 하중-두부침하 계산 곡선')+'<div class="chart-caption">주면 전달만큼 N이 감소하고 선단에서 Qb가 남습니다. 우측은 지정 t–z/q–z 모형의 평형 곡선입니다.</div>';
 }
 function dragChart(r,b){const maxDepth=Math.max(r.length,b?.length||0),maxS=nice(Math.max(r.groundSettlement,r.headSettlement*1000,b?.groundSettlement||0,(b?.headSettlement||0)*1000,1)),maxN=nice(Math.max(r.maxForce,b?.maxForce||0,1)),xS=s=>55+245*s/maxS,xN=N=>390+220*N/maxN,y=z=>55+235*z/maxDepth;let s='<text x="55" y="27">침하(mm) · 깊이 z(m)</text><text x="390" y="27">말뚝 축력 N(kN)</text>';
  for(let i=0;i<=2;i++){const v=maxS*i/2,N=maxN*i/2;s+=`<line class="grid" x1="${xS(v)}" x2="${xS(v)}" y1="55" y2="290"/><text x="${xS(v)}" y="313" text-anchor="middle">${fmt(v,0)}</text><line class="grid" x1="${xN(N)}" x2="${xN(N)}" y1="55" y2="290"/><text x="${xN(N)}" y="313" text-anchor="middle">${fmt(N,0)}</text>`;}
  for(let i=0;i<=4;i++){const z=maxDepth*i/4;s+=`<line class="grid" x1="55" x2="610" y1="${y(z)}" y2="${y(z)}"/><text x="45" y="${y(z)+4}" text-anchor="end">${fmt(z,0)}</text>`;}
  if(b)s+=`<path class="baseline" d="${path(b.profile,p=>xS(p.pile*1000),p=>y(p.z))}"/><path class="baseline" d="${path(b.profile,p=>xN(p.force),p=>y(p.z))}"/>`;
  s+=`<path d="${path(r.profile,p=>xS(p.soil*1000),p=>y(p.z))}" fill="none" stroke="var(--color-text-primary)" stroke-width="2"/><path class="curve" d="${path(r.profile,p=>xS(p.pile*1000),p=>y(p.z))}"/><path class="curve" d="${path(r.profile,p=>xN(p.force),p=>y(p.z))}"/>`;
  for(let i=1;i<=6;i++){const p=r.profile[Math.round((r.profile.length-1)*i/7)],sign=p.relative<0?1:-1,limit=p.z<r.layerDepth?r.tau1:r.tau2;if(Math.abs(p.relative)>1e-10&&limit>0)s+=`<path d="M330 ${y(p.z)-sign*7}v${sign*14}m-4 ${-sign*4}l4 ${sign*4} 4 ${-sign*4}" fill="none" stroke="${sign===1?'var(--color-accent-purple)':'var(--color-action-primary)'}" stroke-width="1.8"/>`;}
  for(const np of r.neutralPoints)s+=`<line x1="55" x2="610" y1="${y(np.z)}" y2="${y(np.z)}" stroke="var(--color-accent-purple)" stroke-dasharray="4 4"/><circle cx="${xN(np.force)}" cy="${y(np.z)}" r="4" fill="var(--color-accent-purple)"/><text x="600" y="${y(np.z)-7}" text-anchor="end" style="fill:var(--color-accent-purple)">중립점 ${fmt(np.z)} m</text>`;
  return svgWrap(s,'말뚝과 지반의 상대침하로 계산한 마찰 방향, 중립점 및 축력')+'<div class="chart-caption">검정: 현재 지반 · 파랑: 말뚝 · 보라 ↓: 아래로 끄는 주면마찰 · 파랑 ↑: 위로 받치는 저항</div>';
 }
 const resistanceFormula=r=>`Qs,u=πD(τu,1L1+τu,2L2)<br>= ${fmt(r.shaftUpper)}+${fmt(r.shaftLower)} = ${fmt(r.shaftUltimate)} kN<br>Qb,u=qb,u·πD²/4=${fmt(r.toeUltimate)} kN<br>Qu=Qs,u+Qb,u=${fmt(r.ultimate)} kN`;
 const method=r=>`<div><h3>모형·입력의 출처</h3><p>${link(manual,'FHWA GEC 12, NHI-16-009')}의 주면·선단 저항 분리와 하중전달 접근을 바탕으로 합니다. 입력 τu와 qb,u는 예제 단위저항이며 α·β·CPT·공법별 경험식으로 자동 추정하지 않습니다. 중실 원형 말뚝의 일정 EA, 축방향 작은 변형, 자중 제외 조건입니다.</p><p>쌍곡식의 t50와 b50도 명시한 예제값입니다. t50에서 주면저항의 50%, b50에서 선단저항의 50%가 동원됩니다. 실측 재하시험이나 표준의 보편값으로 표시하지 않습니다. 시간 의존·하역 이력·반복재하·파괴 후 연화는 포함하지 않습니다.</p></div><div><h3>부주면마찰과 평형 검증</h3><p>${link(dragSource,'FHWA-HRT-17-060')}의 상대침하·중립면 원리, ${link(nchrp,'NCHRP Design of Piles for Downdrag')}의 변위 적합에 따른 동원저항 구분을 참고합니다. 지반침하는 s(z)=s0·max(1−z/Hs,0)의 지정 프로파일입니다.</p><p>1D 탄성봉을 ${r.segments||80}개로 나누고 층 경계·침하 꺾임에 절점을 추가합니다. 분포 스프링을 Gauss 적분하고 감쇠 Newton 반복으로 평형을 풉니다. 마찰 부호가 바뀌는 적분구간을 나누어 정·부마찰을 합산합니다. ${r.balance===undefined?'기여도 질문은 극한저항의 합계만 계산합니다.':`현재 평형 잔차 Q+Qdrag−Qs,+−Qb=${r.balance.toExponential(2)} kN.`}</p><p>중립점은 wp=ws인 위치입니다. 없는 경우 억지로 생성하지 않습니다. 단위 주면저항이 0인 층에서는 상대변위가 있어도 마찰을 그리지 않으며 축력이 평탄할 수 있습니다. 부마찰은 사용상태의 축력·침하 문제이며 같은 양을 극한지지력에서 일괄 공제하지 않습니다.</p></div>`;
 function groupChart(r,b){const scale=220/Math.max(r.width,b?.width||0),originX=62,originY=64,maxQ=nice(Math.max(r.sum,r.block,b?.sum||0,b?.block||0,1)),x=v=>355+245*v/maxQ;let s='<text x="62" y="27">정방형 군말뚝 평면 · 같은 척도</text><text x="355" y="27">저항 기구 비교 (kN)</text>';
  if(b)s+=`<rect x="62" y="64" width="${b.width*scale}" height="${b.width*scale}" fill="none" stroke="var(--color-text-muted)" stroke-dasharray="4 4"/>`;
  s+=`<rect x="62" y="64" width="${r.width*scale}" height="${r.width*scale}" fill="var(--color-action-primary)" fill-opacity=".05" stroke="var(--color-accent-purple)" stroke-dasharray="5 4"/>`;
  for(let i=0;i<r.countSide;i++)for(let j=0;j<r.countSide;j++)s+=`<circle cx="${originX+(r.diameter/2+i*r.spacing)*scale}" cy="${originY+(r.diameter/2+j*r.spacing)*scale}" r="${r.diameter*scale/2}" fill="var(--color-action-primary)" opacity=".7"/>`;
  for(const [key,label,y,color]of [['sum','개별 말뚝 저항의 합계',100,'var(--color-action-primary)'],['block','블록 기구',215,'var(--color-accent-purple)']]){s+=`<text x="355" y="${y-24}">${label}</text><rect x="355" y="${y}" width="${x(r[key])-355}" height="24" fill="${color}" rx="3"/><text x="355" y="${y+47}">${fmt(r[key],0)} kN</text>`;if(b)s+=`<rect x="355" y="${y+28}" width="${x(b[key])-355}" height="5" fill="none" stroke="var(--color-text-muted)" stroke-dasharray="3 3"/>`;}
  s+=`<text x="62" y="313">B=${fmt(r.width,2)} m · s=${fmt(r.spacing,2)} m</text>`;return svgWrap(s,'군말뚝 평면 배치와 개별합계 및 블록 파괴 저항 비교')+'<div class="chart-caption">보라 점선은 흙을 함께 포함한 블록 경계입니다. 결과 요약 1 MN=1,000 kN · 저항 비교만으로 군 침하는 정해지지 않습니다.</div>';
 }
 const groupResistanceKeys=['countSide','spacingRatio','length','diameter','su','alpha'];
 const groupSettlementKeys=['countSide','spacingRatio','length','diameter','groupLoad','layerTop','layerThickness','layerModulus'];
 function groupSettlementControls(d){return `<div class="parameter-grid">${fieldControl('countSide','한 변의 말뚝 수 n',d.countSide,2,8,1,'개','n×n 배열 · 총군하중 Q는 그대로 유지합니다.')}${fieldControl('spacingRatio','중심간격 s/D',d.spacingRatio,1.5,6,.25,'','군폭 B가 달라집니다. 시공 권장간격 판정은 아닙니다.')}${fieldControl('groupLoad','총군 추가 사용하중 Q',d.groupLoad,0,20000,250,'kN','전체 군에 작용하는 하중 증가량 · 극한저항이 아닙니다.')}${fieldControl('layerModulus','압축층 구속계수 M',d.layerModulus,1,50,.5,'MPa','1D Δσ′/ε · Young 탄성계수 E와 구별합니다.',1000)}${fieldControl('layerThickness','지정 압축층 두께 H',d.layerThickness,0,30,.5,'m','등가기초 아래 지정층의 압축만 합산합니다.')}</div><details class="setting"><summary>말뚝 치수 · 압축층 위치</summary>${fieldControl('length','말뚝 길이 L',d.length,5,40,1,'m','등가기초 깊이=2L/3. 지층 위치는 지표 기준으로 고정됩니다.')}${fieldControl('diameter','말뚝 직경 D',d.diameter,.3,1.2,.05,'m','외곽 폭 B=(n−1)(s/D)D+D')}${numericRow('layerTop','압축층 상면 깊이 Zt',d.layerTop,'m',0,80,.5)}<p class="note">Zt≥2L/3이 필요합니다. 이 층 밖의 압축과 말뚝·캡 자체 압축은 계산에 포함하지 않습니다.</p></details><p class="parameter-note">마찰말뚝군의 등가기초 + 명시적 1H:2V 확산 + 일정 M의 제한된 관계입니다. 저항 비교의 su·α는 이 침하식의 입력이 아닙니다.</p>`;}
 function groupSettlementChart(r,b){
  const bottom=Math.max(r.layerBottom,r.length,b?.layerBottom||0,b?.length||0),extent=Math.max(r.spreadBottom,r.width,b?.spreadBottom||0,b?.width||0),scale=Math.min(248/extent,225/bottom),cx=165,y=z=>54+z*scale;
  const depthRange=Math.max(r.layerThickness,b?.layerThickness||0,1),stressMax=nice(Math.max(r.stressTop,b?.stressTop||0,1)),xs=p=>390+212*p/stressMax,ys=h=>54+225*h/depthRange;
  let s='<text x="42" y="25">등가기초와 지정층 · 실제 길이비</text><text x="390" y="25">지정층 Δσ′ (kPa)</text>';
  s+=`<rect x="40" y="${y(r.layerTop)}" width="266" height="${r.layerThickness*scale}" fill="var(--color-action-primary)" opacity=".09"/><line x1="40" x2="306" y1="54" y2="54" stroke="var(--color-text-muted)"/><line x1="40" x2="306" y1="${y(r.layerTop)}" y2="${y(r.layerTop)}" stroke="var(--color-border-strong)"/><line x1="40" x2="306" y1="${y(r.layerBottom)}" y2="${y(r.layerBottom)}" stroke="var(--color-border-strong)"/>`;
  for(let i=0;i<r.countSide;i++){const xx=cx+(-r.width/2+i*r.spacing)*scale;s+=`<rect x="${xx}" y="54" width="${r.diameter*scale}" height="${r.length*scale}" fill="var(--color-action-primary)" opacity=".55"/>`;}
  s+=`<rect x="${cx-r.width*scale/2}" y="49" width="${r.width*scale}" height="5" fill="var(--color-action-secondary)"/>`;
  const outline=a=>`M${cx-a.width*scale/2} ${y(a.equivalentDepth)}L${cx-a.spreadBottom*scale/2} ${y(a.layerBottom)}M${cx+a.width*scale/2} ${y(a.equivalentDepth)}L${cx+a.spreadBottom*scale/2} ${y(a.layerBottom)}`;
  if(b)s+=`<path class="baseline" d="${outline(b)}"/><line class="baseline" x1="${cx-b.width*scale/2}" x2="${cx+b.width*scale/2}" y1="${y(b.equivalentDepth)}" y2="${y(b.equivalentDepth)}"/>`;
  s+=`<path d="${outline(r)}" fill="none" stroke="var(--color-accent-purple)" stroke-dasharray="5 3" stroke-width="2"/><line x1="${cx-r.width*scale/2}" x2="${cx+r.width*scale/2}" y1="${y(r.equivalentDepth)}" y2="${y(r.equivalentDepth)}" stroke="var(--color-accent-purple)" stroke-width="4"/>`;
  s+=`<text x="40" y="${y(r.equivalentDepth)-6}" style="fill:var(--color-accent-purple)">2L/3=${fmt(r.equivalentDepth,1)} m</text><text x="306" y="${y(r.layerTop)-6}" text-anchor="end">Zt=${fmt(r.layerTop,1)} m</text><text x="306" y="${y(r.layerBottom)+16}" text-anchor="end">Zt+H=${fmt(r.layerBottom,1)} m</text><text x="40" y="316">B=${fmt(r.width,2)} m · ${r.countSide}×${r.countSide}개</text>`;
  for(let i=0;i<=2;i++){const stress=stressMax*i/2,h=depthRange*i/2;s+=`<line class="grid" x1="${xs(stress)}" x2="${xs(stress)}" y1="54" y2="279"/><text x="${xs(stress)}" y="300" text-anchor="middle">${fmt(stress,0)}</text><line class="grid" x1="390" x2="602" y1="${ys(h)}" y2="${ys(h)}"/><text x="378" y="${ys(h)+4}" text-anchor="end">${fmt(h,1)}</text>`;}
  if(b)s+=`<path class="baseline" d="${path(b.profile,p=>xs(p.stress),p=>ys(p.withinLayer))}"/>`;
  const first=r.profile[0],last=r.profile.at(-1);s+=`<path d="M390 ${ys(0)}L${xs(first.stress)} ${ys(0)}${r.profile.map(p=>`L${xs(p.stress)} ${ys(p.withinLayer)}`).join('')}L390 ${ys(last.withinLayer)}Z" fill="var(--color-action-primary)" opacity=".13"/><path class="curve" d="${path(r.profile,p=>xs(p.stress),p=>ys(p.withinLayer))}"/><circle cx="${xs(first.stress)}" cy="${ys(0)}" r="3.5" fill="var(--color-action-primary)"/><text x="602" y="325" text-anchor="end">세로: 층 상면 아래 거리 h(m)</text>`;
  return svgWrap(s,'정방형 마찰말뚝군의 2L/3 등가기초, 1H 대 2V 응력 확산 경계와 지정 압축층 내 실제 계산 응력분포')+'<div class="chart-caption">왼쪽 폭·깊이는 같은 척도이며 한 줄 단면입니다. 보라 점선은 2:1 응력확산 가정입니다. 오른쪽 음영 면적을 M으로 나누면 이 층의 침하입니다.</div>';
 }
 function groupSettlementRender(r,b){b=b?.model===r.model?b:null;return {title:'같은 총하중에서 군폭과 하부층 강성은 침하를 어떻게 바꿀까요?',conditions:['마찰말뚝군 · 정방형 배열','등가기초 2L/3 · 1H:2V','지정층 일정 M · 배수 완료'],plotTitle:'응력 확산과 지정 압축층의 침하 기여',legend:'<span class="legend-item"><i></i>지정층 응력</span><span class="legend-item"><i style="border-color:var(--color-accent-purple)"></i>등가기초·확산</span>',comparisonPlot:!!b,chart:groupSettlementChart(r,b),results:metric('지정층 침하 기여',r.settlementMm,'mm',b?.settlementMm??null,true,2)+metric('층 평균 Δσ′',r.averageStress,'kPa',b?.averageStress??null,false,2)+metric('군 외곽 폭 B',r.width,'m',b?.width??null,false,2),explanation:`총군하중 ${fmt(r.groupLoad,0)} kN을 폭 ${fmt(r.width,2)} m의 등가기초에서 전달하면, 지정층의 응력 증가는 상면 <strong>${fmt(r.stressTop,2)} kPa</strong>에서 하면 <strong>${fmt(r.stressBottom,2)} kPa</strong>로 줄어듭니다.<span class="hint">같은 Q에서 군폭이 넓어지면 이 층의 응력·침하 기여가 작아집니다. M만 2배로 하면 응력은 같고 침하는 절반입니다. 말뚝 수를 늘려도 Q는 자동으로 늘지 않습니다.</span>`,theory:`<h3>기초 위치·응력 확산·압축을 나눠 계산합니다</h3><div class="theory-formula">B=(n−1)(s/D)D+D=${fmt(r.width,2)} m<br>ze=2L/3=${fmt(r.equivalentDepth,3)} m<br>a=Zt−ze=${fmt(r.offset,3)} m<br>Δσ′(z)=Q/(B+z)², z는 등가기초 아래 깊이<br>Δσ′top=${fmt(r.groupLoad,0)}/(${fmt(r.width,2)}+${fmt(r.offset,3)})²=${fmt(r.stressTop,2)} kPa</div><div class="theory-formula">S층=∫[a→a+H] Δσ′(z)/M dz<br>=QH/[M(B+a)(B+a+H)]<br>=${fmt(r.groupLoad,0)}×${fmt(r.layerThickness,2)}/[${fmt(r.layerModulus,0)}×${fmt(r.spreadTop,3)}×${fmt(r.spreadBottom,3)}]<br>=${fmt(r.settlement,5)} m=${fmt(r.settlementMm,2)} mm</div><p>1H:2V는 깊이 z만큼 내려갈 때 양쪽으로 각각 z/2씩 넓어져 한 변이 B+z가 된다는 뜻입니다. 위 식은 일정 M인 지정층 전체의 정확한 적분이며, 중간 깊이 응력 하나로 층 전체를 대신하지 않습니다. M=${fmt(r.layerModulus/1000,2)} MPa=${fmt(r.layerModulus,0)} kPa입니다.</p><p class="theory-meta">이 결과는 지정층의 압축 기여입니다. 말뚝 자체·캡 압축, 다른 층의 압축, 개별 말뚝과 군의 정밀 상호작용을 합한 총두부침하가 아닙니다. 극한저항 합계와도 별개입니다. 층 위치를 고정하고 L만 늘리면 등가기초가 층에 가까워져 이 계산의 응력이 커질 수 있으며, 이를 ‘말뚝이 길수록 일반적으로 더 침하한다’는 결론으로 해석하지 않습니다.</p>`,method:`<div><h3>직접 확인한 공식 근거</h3><p>${link(PileGroupSettlement.source.url,'FHWA GEC 8 (2007) §5.5.3.3, 인쇄 pp.99–101, Figs.5.19–5.20')}: 군 외곽 면적의 등가기초, 선단 위 L/3인 대표 위치와 그 아래 1H:2V 응력확산, 하부층별 침하 합산을 설명합니다. 실제 등가기초 위치는 지층·하중전달 기구에 따라 조정해야 한다는 한계도 함께 제시합니다.</p><p>화면은 수직 마찰말뚝의 정방형 군, 비교적 강체인 캡의 대칭 연직하중이라는 제한 예제에서 깊이를 2L/3로 고정합니다. 선단지지·경사말뚝·편심하중·층 경계를 관통하는 다양한 전달기구에 이 위치를 일률 적용하지 않습니다. 기존 저항 화면의 NHI-06-089 본문 30° 표현과 이번 1H:2V를 같은 확산각으로 혼용하지 않습니다.</p></div><div><h3>이 화면에서 추가한 압축 단순화</h3><p>FHWA의 일반 층별 e–logσ′ 해석 전체를 구현한 것이 아닙니다. 여기서는 구속계수 M=Δσ′/εz를 지정 응력 구간에서 일정하게 놓고 dS=(Δσ′/M)dz를 해석적으로 적분합니다. 초기 응력·선행압밀응력·Cc·Cr·시간·배수거리를 입력받지 않으므로 응력이력·압밀속도·2차압축은 계산하지 않습니다.</p><p>Q는 해당 상태에서 추가 전달되는 군 전체 사용하중입니다. 극한저항이나 허용저항을 자동 대입하지 않으며, 말뚝·캡 자중도 자동 가산하지 않습니다. 지정층 밖의 침하를 0으로 판정한 것이 아니라 합산 대상에서 제외한 것입니다. Zt는 지표 기준의 고정 깊이로 두므로 L 변화 때 층도 따라 움직이지 않습니다.</p><p>이 일정 M·작은 변형 모형의 제공 범위는 지정층의 최대 Δσ′/M≤10%입니다. 10%는 설계 허용치·정확도 보장선이 아닙니다. 강성의 응력 의존, 군효율, 시공 효과, 하중분배·캡 접촉, 상세 3D 해석은 별도 검토가 필요합니다.</p></div>`};}
 return [{
  key:'pile-axial',meta:{name:'말뚝과 하중전달',sub:'저항·침하·부주면마찰',group:'기초와 말뚝 / 축방향 하중전달',navGroup:'foundations',words:'말뚝 길이 직경 지지력 주면 선단 저항 t-z q-z 하중전달 침하 부주면마찰 중립점 중립면 축력 실제 재하시험 실측 제하 재재하 Amaliahaven',questions:[['capacity','주면과 선단'],['transfer','하중과 침하'],['downdrag','주변 흙이 내려가면'],['evidence','실제 재하시험']]},defaults:{...PileModels.defaults,pileEvidencePoint:12},
  bounds:{...Object.fromEntries(Object.entries(fields).map(([k,[l,min,max,,u]])=>[k,[min,max,l,u]])),pileEvidencePoint:[1,23,'시험 기록 순서','번']},labels:{...Object.fromEntries(Object.entries(fields).map(([k,[l,,,,u]])=>[k,[l,u]])),pileEvidencePoint:['시험 기록 순서','번']},
  activeFields:(d,q)=>q==='evidence'?['pileEvidencePoint']:q==='capacity'?caps(d):[...caps(d),'modulus','shaft50','toe50','headLoad',...(q==='downdrag'?['groundSettlement','settlementDepth']:[])],compute:(d,q)=>q==='evidence'?PileEvidence.read(d):PileModels.experiment(d,q),controls:(d,q)=>q==='evidence'?PileEvidenceView.controls(d):controls(d,q),
  render({result:r,baseline:b,question:q}){if(q==='evidence')return PileEvidenceView.render({result:r,baseline:b});if(q==='capacity')return {title:'길이와 직경을 바꾸면 주면과 선단은 각각 얼마나 늘까요?',conditions:['두 층 단위저항 지정','중실 원형 말뚝','무계수 극한저항'],plotTitle:'관입길이와 저항 기여도',comparisonPlot:!!b,chart:capacityChart(r,b),results:metric('주면 Qs,u',r.shaftUltimate,'kN',b?.shaftUltimate??null,true)+metric('선단 Qb,u',r.toeUltimate,'kN',b?.toeUltimate??null)+metric('합계 Qu',r.ultimate,'kN',b?.ultimate??null),explanation:`위층 ${fmt(r.upperLength)} m와 아래층 ${fmt(r.lowerLength)} m가 실제로 말뚝과 접합니다. <strong>주면은 둘레×길이, 선단은 단면적</strong>에 비례합니다.<span class="hint">같은 단위저항에서 D를 2배로 하면 주면은 2배, 선단은 4배입니다. 실제 길이를 바꾸면 새 선단 지층의 저항도 다시 채택해야 합니다.</span>`,theory:`<h3>저항의 크기와 동원에 필요한 침하는 다릅니다</h3><div class="theory-formula">${resistanceFormula(r)}</div><p>이 값은 지정 단위저항을 합한 극한값입니다. 어느 침하에서 얼마나 동원되는지는 ‘하중과 침하’의 전달식으로 확인하세요.</p>`,method:method(r)};
   const drag=q==='downdrag';return {title:drag?'주변 흙이 더 내려가면 말뚝의 어느 부분을 끌어내릴까요?':'같은 극한저항인데 왜 말뚝의 침하는 달라질까요?',conditions:['1D 탄성 말뚝','예제 쌍곡 t–z/q–z',drag?'지반침하 프로파일 지정':'주변 지반침하 0',`L=${fmt(r.length)} m · D=${fmt(r.diameter,2)} m`],plotTitle:drag?'상대침하 · 마찰방향 · 중립점':'축력 전달과 Q–침하 관계',comparisonPlot:!!b,chart:drag?dragChart(r,b):transferChart(r,b),results:metric('두부침하',r.headSettlement*1000,'mm',b?b.headSettlement*1000:null,true)+(drag?metric('최대 축력',r.maxForce,'kN',b?.maxForce??null)+metric('중립점 깊이',r.neutralPoints.length?fmt(r.neutralPoints[0].z,2):'없음',r.neutralPoints.length?'m':''):metric('말뚝 자체 압축',r.pileShortening*1000,'mm',b?b.pileShortening*1000:null)+metric('선단 동원 Qb',r.toeForce,'kN',b?.toeForce??null)),explanation:drag?`말뚝보다 흙이 더 내려가는 곳은 아래로 끄는 마찰이 생깁니다. <strong>현재 아래 방향 주면마찰 합계는 ${fmt(r.dragLoad)} kN</strong>입니다.<span class="hint">${r.neutralPoints.length?`상대침하가 0인 ${fmt(r.neutralPoints[0].z)} m 부근에서 축력이 최대입니다.`:'현재 프로파일에는 내부 중립점이 없습니다. 주변 흙이 침하해도 말뚝이 더 많이 내려가면 부마찰이 사라질 수 있습니다.'} 두부 하중과 최대 축력을 구별하세요.</span>`:`현재 Q=${fmt(r.headLoad)} kN에서 두부침하는 <strong>${fmt(r.headSettlement*1000,2)} mm</strong>입니다. 이 중 말뚝 재료의 압축은 ${fmt(r.pileShortening*1000,2)} mm입니다.<span class="hint">Ep·t50·b50를 바꾸어도 지정 극한저항 Qu=${fmt(r.ultimate)} kN는 그대로입니다. 더 작은 변위에 동원되는 저항과 최종 저항의 크기를 구별하세요.</span>`,theory:`<h3>${drag?'상대변위의 부호로 주면마찰이 정해집니다':'저항을 동원하는 변위와 말뚝 압축을 함께 풉니다'}</h3><div class="theory-formula">δ(z)=wp(z)−ws(z) · 아래 방향 (+)<br>τ=τu·δ/(t50+|δ|), t50=${fmt(r.shaft50)} mm<br>Qb=Qb,u·δb/(b50+δb), δb≥0 · b50=${fmt(r.toe50)} mm<br>N=−EA·dwp/dz, dN/dz=−πDτ<br>Q+Qdrag=Qs,+ + Qb<br>${fmt(r.headLoad)}+${fmt(r.dragLoad)}=${fmt(r.shaftPositive)}+${fmt(r.toeForce)} kN</div><p>${drag?`ws(z)=${fmt(r.groundSettlement)}·max(1−z/${fmt(r.settlementDepth)},0) mm. 양의 τ는 말뚝을 위로 받치고, 음의 τ는 아래로 끕니다. 선단 전달은 말뚝 선단과 그 위치의 흙 사이 상대침하를 사용합니다.`:`wp,head=wp,toe+∫N/(EA) dz=${fmt(r.toeSettlement*1000,2)}+${fmt(r.pileShortening*1000,2)}=${fmt(r.headSettlement*1000,2)} mm. 주면·선단 저항이 한꺼번에 극한으로 동원된다고 가정하지 않습니다.`}</p>${r.warnings.length?`<p class="notice">${r.warnings.map(esc).join(' ')}</p>`:''}<p class="theory-meta">가상 전달식의 계산입니다. 실제 재하시험 곡선·시공 효과·장기 압밀을 대신하지 않습니다.</p>`,method:method(r)};}
 },{
  key:'pile-group',meta:{name:'군말뚝의 저항과 침하',sub:'개별합계·블록·침하 구별',group:'기초와 말뚝 / 군효과',navGroup:'foundations',words:'군말뚝 군효과 간격 배열 블록 파괴 지지력 침하 군침하 군말뚝침하 등가기초 압축층 개수 효율',questions:[['group','개별합계와 블록'],['settlement','군의 침하']]},defaults:{...PileGroupSettlement.defaults,su:50,alpha:.7},bounds:{countSide:[2,8,'한 변 말뚝 수','개'],spacingRatio:[1.5,6,'중심간격/직경',''],length:[5,40,'길이','m'],diameter:[.3,1.2,'직경','m'],su:[10,150,'비배수강도','kPa'],alpha:[0,1,'부착계수 α',''],groupLoad:[0,20000,'총군 추가 사용하중','kN'],layerTop:[0,80,'압축층 상면 깊이','m'],layerThickness:[0,30,'압축층 두께','m'],layerModulus:[1000,50000,'압축층 구속계수 M','kPa']},labels:{countSide:['한 변 말뚝 수','개'],spacingRatio:['s/D',''],length:['길이 L','m'],diameter:['직경 D','m'],su:['비배수강도 su','kPa'],alpha:['부착계수 α',''],groupLoad:['총군 추가 사용하중 Q','kN'],layerTop:['압축층 상면 깊이','m'],layerThickness:['압축층 두께 H','m'],layerModulus:['구속계수 M','kPa']},activeFields:(d,q)=>q==='settlement'?groupSettlementKeys:groupResistanceKeys,compute:(d,q)=>q==='settlement'?PileGroupSettlement.solve(d):PileModels.group(Object.fromEntries(groupResistanceKeys.filter(k=>d[k]!==undefined).map(k=>[k,d[k]]))),
  controls:(d,q)=>q==='settlement'?groupSettlementControls(d):`<div class="parameter-grid">${fieldControl('countSide','한 변의 말뚝 수 n',d.countSide,2,8,1,'개','n×n 정방형 배열')}${fieldControl('spacingRatio','중심간격 s/D',d.spacingRatio,1.5,6,.25,'','가까운 배치의 가상 비교이며 시공 권장간격이 아닙니다.')}${fieldControl('length','길이 L',d.length,5,40,1,'m','단일 깊은기초 예제 L/D≥5')}${fieldControl('diameter','직경 D',d.diameter,.3,1.2,.05,'m','원형 중실 말뚝')}${fieldControl('su','균질 점토의 su',d.su,10,150,5,'kPa','단기 비배수 기구 비교')}</div><details class="setting"><summary>단일 말뚝 부착계수</summary>${fieldControl('alpha','지정 부착계수 α',d.alpha,0,1,.05,'','τu=αsu. 토질·공법에서 자동 산정하지 않습니다.')}</details><p class="parameter-note">두 저항 기구를 무계수로 비교합니다. 실제 군효율·침하·시공 권장간격을 판정하는 계산서가 아닙니다.</p>`,
  render({result:r,baseline:b,question:q}){if(q==='settlement')return groupSettlementRender(r,b);return {title:'말뚝을 여러 개 모으면 저항도 항상 개수만큼 늘까요?',conditions:['균질 포화 점토','정방형 n×n 배열','단기 저항 기구 비교'],plotTitle:'개별 말뚝 합계와 흙을 포함한 블록',comparisonPlot:!!b,chart:groupChart(r,b),results:metric('개별합계 n²Q1',r.sum/1000,'MN',b?b.sum/1000:null)+metric('블록 Qblock',r.block/1000,'MN',b?b.block/1000:null)+metric('두 기구의 작은 값',r.minimum/1000,'MN',b?b.minimum/1000:null,true),explanation:`현재 ${r.count}개 배열에서는 <strong>${r.mechanism==='block'?'블록 기구':'개별 말뚝의 단순 합계'}</strong>가 두 계산 중 더 작습니다.<span class="hint">간격을 바꾸면 개별합계는 같지만 블록의 둘레와 면적은 달라집니다. 개별합계가 작다고 군효율 100%나 허용 침하를 보증하지는 않습니다.</span>`,theory:`<h3>블록은 바깥 둘레와 전체 면적으로 저항합니다</h3><div class="theory-formula">B=(n−1)s+D=${fmt(r.width,2)} m<br>Q1=πDL·αsu+(πD²/4)·9su<br>n²Q1=${fmt(r.sum)} kN<br>Qblock=4BL·su+B²Nc·su<br>=${fmt(r.blockShaft)}+${fmt(r.blockToe)}=${fmt(r.block)} kN<br>Nc=min[9,5(1+L/5B)(1+1/5)]=${fmt(r.Nc,2)}</div><p>군 침하는 응력이 더 넓고 깊게 전달되는 효과와 지층의 압축성·말뚝 자체 압축을 함께 검토해야 합니다. 저항이 같거나 말뚝 수가 같다는 사실만으로 단독 말뚝과 같은 침하가 나오지 않습니다.</p><p class="theory-meta">실제 군효율, 말뚝캡 지지, 시공 후 강도 변화, 장기 압밀·약층, 횡방향 군효과는 이 두 기구 계산에 포함되지 않습니다.</p>`,method:`<div><h3>계산의 조건</h3><p>포화 균질 점토, 단기 비배수, 정방형 배열의 개별합계와 블록 기구를 비교합니다. 개별합계는 상호작용 저감계수를 1로 둔 비교값입니다. 단일 말뚝 선단 Nc=9는 L/D≥5인 예제로 제한합니다. 블록은 외곽 말뚝의 바깥면을 연결한 B×B 단면입니다.</p><p>Qblock=2L(B+Z)su+BZ·Nc·su, 여기서는 Z=B입니다. Nc는 깊이/폭에 따라 줄어드는 식을 적용합니다. 예제의 α는 지정값이며 경험식·공법 선정 절차를 대신하지 않습니다.</p></div><div><h3>근거·추가 검토</h3><p>${link(groupSource,'FHWA NHI-06-089 §§9.6.1–9.6.2, Eqs. 9-18–9-19')}의 점토 블록 기구 및 군 침하 구분. 개별합계와 블록 중 작은 값만으로 모든 군효과를 검토한 것으로 표시하지 않습니다.</p><p>‘군의 침하’에서는 등가기초 아래 지정 압축층의 기여를 따로 계산합니다. 전체 장기 군 침하, 시공·재성형에 따른 저항 변화, 군 내 하중배분·연성 말뚝캡, 횡변위·회전 구속·경사말뚝·인발은 후속 별도 범위입니다.</p></div>`};}
 }];
})();
