const ReinforcementLabs=(()=>{
 const fields={embedment:[0,6,.1,'저항영역 정착길이 Le','m'],normalStress:[0,150,5,'유효수직응력 σ′v','kPa'],pulloutFactor:[0,1.5,.05,'지정 인발계수 F*',''],tensileResistance:[0,300,5,'지정 재료 인장저항 T','kN/m']};
 const source='https://www.fhwa.dot.gov/engineering/geotech/pubs/hif24002.pdf';
 function chart(r,b){const xmax=Math.max(5,r.embedment,b?.embedment||0),ymax=Math.max(r.tensileResistance,r.pullout,b?.tensileResistance||0,b?.pullout||0,10)*1.2,x=v=>70+510*v/xmax,y=v=>271-208*v/ymax;let s='<text x="70" y="26">단위 폭당 저항 (kN/m)</text>';
  for(let i=0;i<=4;i++){const v=ymax*i/4;s+=`<line class="grid" x1="70" x2="580" y1="${y(v)}" y2="${y(v)}"/><text x="60" y="${y(v)+4}" text-anchor="end">${fmt(v,0)}</text>`;}
  for(let i=0;i<=5;i++){const v=xmax*i/5;s+=`<text x="${x(v)}" y="294" text-anchor="middle">${fmt(v,1)}</text>`;}
  s+=`<line x1="70" x2="580" y1="${y(r.tensileResistance)}" y2="${y(r.tensileResistance)}" stroke="#7543C5" stroke-dasharray="5 3"/><text x="580" y="${y(r.tensileResistance)-8}" text-anchor="end" fill="#7543C5">재료 인장저항</text>`;
  const path=z=>Array.from({length:61},(_,i)=>{const length=xmax*i/60;return `${i?'L':'M'}${x(length)} ${y(Math.min(z.gradient*length,z.tensileResistance))}`}).join(' ');
  if(b)s+=`<path d="${path(b)}" fill="none" stroke="#777" stroke-dasharray="5 4" stroke-width="2"/>`;
  s+=`<path d="${path(r)}" fill="none" stroke="#0F6FFF" stroke-width="3"/><line x1="${x(r.embedment)}" x2="${x(r.embedment)}" y1="${y(r.resistance)}" y2="271" stroke="#333" stroke-dasharray="3 3"/><circle cx="${x(r.embedment)}" cy="${y(r.resistance)}" r="6" fill="#0F6FFF" stroke="white" stroke-width="2"/><text x="580" y="325" text-anchor="end">저항영역 정착길이 Le (m)</text>`;
  return svgWrap(s,'정착길이에 따른 인발저항과 재료 인장저항 중 작은 값, 현재 길이의 위치');
 }
 return [{key:'reinforcement',meta:{name:'보강재 인발·인장',sub:'정착길이·구속압·지배 저항',group:'조사·개량·연결 / 흙과 보강재',navGroup:'practice',words:'보강토 보강재 지오그리드 인발 인장 정착길이 파단 pullout geosynthetic 저항',questions:[['resistance','길이를 늘리면 저항도 계속 커질까']]},defaults:{embedment:2,normalStress:50,pulloutFactor:.5,tensileResistance:80},bounds:Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,[v[0],v[1],v[3],v[4]]])),labels:Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,[v[3],v[4]]])),compute:d=>Reinforcement.solve(d),
 controls:d=>Object.entries(fields).map(([k,[min,max,step,label,unit]])=>fieldControl(k,label,d[k],min,max,step,unit,k==='embedment'?'가정한 활동면 뒤쪽의 저항길이입니다. 보강재 전체 길이가 아닙니다.':k==='pulloutFactor'?'해당 흙·보강재 시험조건에서 지정한 값. 마찰각과 같은 값이 아닙니다.':k==='tensileResistance'?'동일 단기 비교조건의 단위 폭당 저항. 설계용 장기강도를 자동 산정하지 않습니다.':'같은 응력이 저항영역에 균일하게 작용하는 예제입니다.')).join(''),
 render({result:r,baseline:b}){const name={pullout:'흙에서 뽑히는 인발저항',tensile:'보강재 자체의 인장저항',equal:'인발·인장저항이 같은 경계'}[r.governing];return {title:'보강재를 길게 넣으면 저항도 계속 커질까요?',conditions:['단위 폭 1 m · 양면 C=2','균일 유효응력','단기 지정 저항 비교'],plotTitle:'정착길이와 두 저항의 지배 전환',comparisonPlot:true,chart:chart(r,b),results:metric('인발저항 Pr',r.pullout,'kN/m',b?.pullout??null)+metric('인장저항 T',r.tensileResistance,'kN/m',b?.tensileResistance??null)+metric('두 모드 중 작은 저항',r.resistance,'kN/m',b?.resistance??null,true),explanation:`<strong>현재는 ${name}가 지배합니다.</strong> 길이가 짧을 때는 정착길이를 늘리는 효과가 있지만, 재료 인장저항에 도달하면 길이만 더해도 이 비교 저항은 커지지 않습니다.<span class="hint">${r.transitionLength===null?'현재 F*σ′v=0이므로 길이를 늘려도 이 모형의 인발저항은 0입니다.':`두 저항이 같아지는 Le는 ${fmt(r.transitionLength,2)} m입니다.`} 보강토 구조물 전체의 안정성과 변형은 이 두 값만으로 정해지지 않습니다.</span>`,theory:`<h3>저항면적과 구속압</h3><div class="theory-formula">Pr = F* σ′v Le C<br>= ${fmt(r.pulloutFactor,2)} × ${fmt(r.normalStress,1)} × ${fmt(r.embedment,2)} × 2<br>= ${fmt(r.pullout,2)} kN/m<br>R=min(Pr,T)=${fmt(r.resistance,2)} kN/m</div><p>F*는 마찰·맞물림 등 흙–보강재 상호작용을 반영하는 지정 인발계수입니다. 지오그리드의 격자 맞물림을 단순 tanφ로 자동 대체하지 않습니다. 양면의 저항면적을 쓰는 C=2는 길이·폭과 함께 단위를 맞춥니다.</p>`,method:`<p><a href="${source}" target="_blank" rel="noopener">FHWA-HIF-24-002 (2023), Chapter 3, Eq.(2), p.55–56</a>의 단위 폭 인발저항 관계를 사용합니다. F*는 관련 시험으로 정하는 계수입니다. 이 판본의 식에는 별도 규모보정 α를 곱하지 않으며 이전 판본의 계수를 무조건 섞지 않습니다.</p><p>현재는 1 m 연속 폭에 같은 σ′v가 작용하고 저항영역 길이만 변하는 제한된 관계입니다. 총 길이 중 활동영역 안의 길이를 Le에 넣지 않습니다. 유효응력이 낮아지면 인발저항도 낮아집니다.</p><p>입력 T는 같은 단기 비교조건의 지정 인장저항입니다. 크리프·시공손상·내구성 저감계수, 하중·저항계수, 연결부, 외적/복합/전체안정, 실제 변형과 여러 보강층의 상호작용은 계산하지 않습니다. R은 두 지정 저항의 비교값이며 추천 설계강도·안전율·허용하중이 아닙니다.</p>`};}
 }];
})();
