/** Saturated flow learning views. Every plotted line comes from Seepage outputs. */
const SeepageLabs = (() => {
  const usace='https://www.publications.usace.army.mil/Portals/76/Publications/EngineerManuals/EM_1110-2-1901.pdf';
  const usbr='https://www.usbr.gov/tsc/techreferences/research/R03.pdf';
  const fhwa='https://www.fhwa.dot.gov/engineering/geotech/pubs/nhi06088.pdf';
  const link=(url,label)=>`<a href="${url}" target="_blank" rel="noopener">${label}</a>`;
  const sci=n=>Number.isFinite(n)?n.toExponential(2):'—';
  const path=(points,x,y)=>points.map((p,i)=>`${i?'L':'M'}${x(p).toFixed(2)} ${y(p).toFixed(2)}`).join(' ');
  const line=(points,x,y,color='var(--color-action-primary)',dash='')=>`<path d="${path(points,x,y)}" fill="none" stroke="${color}" stroke-width="2.4" ${dash?`stroke-dasharray="${dash}"`:''}/>`;
  const headLegend='<span class="legend-item"><i></i>수두</span>';
  const darcyDiagram=(r,b)=>{
    const x=z=>65+65*z,y=h=>260-27*h;let a='<text x="65" y="22">전수두 h (m) · 수평 시료의 기준고 = 0</text>';
    for(let h=0;h<=8;h+=2)a+=`<line class="grid" x1="65" x2="585" y1="${y(h)}" y2="${y(h)}"/><text x="52" y="${y(h)+4}" text-anchor="end">${h}</text>`;
    for(let z=0;z<=8;z+=2)a+=`<text x="${x(z)}" y="315" text-anchor="middle">${z}</text>`;
    if(b)a+=line([{z:0,h:b.headDifference},{z:b.length,h:0}],p=>x(p.z),p=>y(p.h),'var(--color-text-muted)','6 4');
    a+=`<rect x="65" y="266" width="${65*r.length}" height="24" rx="3" fill="var(--color-bg-surface-alt-2)" stroke="var(--color-border-strong)"/>`;
    for(let f=0;f<=1.001;f+=.25){const z=r.length*f,h=r.headDifference*(1-f);a+=`<line x1="${x(z)}" x2="${x(z)}" y1="260" y2="${y(h)}" stroke="var(--color-action-primary)" stroke-width="5" opacity=".26"/><circle cx="${x(z)}" cy="${y(h)}" r="3.5" fill="var(--color-action-primary)"/>`;}
    a+=line([{z:0,h:r.headDifference},{z:r.length,h:0}],p=>x(p.z),p=>y(p.h));
    a+=`<text x="${x(r.length/2)}" y="283" text-anchor="middle" style="fill:var(--color-text-primary);font-size:11px">${r.flow>0?'유동 → · ':''}A = ${fmt(r.area,2)} m²</text><text x="603" y="315">x (m)</text>`;
    return svgWrap(a,'수평 포화 시료의 직선 전수두 분포와 피에조미터 수두')+'<div class="chart-caption">세로 파란선은 피에조미터 수두입니다. 시료 두께는 도식이며 x축과 수두축은 각각 표시한 척도를 사용합니다.</div>';
  };
  const upwardDiagram=(r,b)=>{
    const y=z=>52+230*z/8,min=Math.min(0,r.upwardBase.effective,b?.upwardBase.effective??0),max=Math.max(r.upwardBase.total,r.upwardBase.pore,b?.upwardBase.total??0,b?.upwardBase.pore??0),x=s=>310+295*(s-min)/(max-min||1);
    let a=`<rect x="84" y="52" width="123" height="${230*r.length/8}" fill="var(--color-bg-surface-alt-2)" stroke="var(--color-border-strong)"/><text x="145" y="31" text-anchor="middle">지표 h = 0</text><text x="145" y="${y(r.length)+24}" text-anchor="middle">바닥 h = ${fmt(r.headDifference,2)} m</text><text x="145" y="326" text-anchor="middle">층 두께 L = ${fmt(r.length,1)} m</text><text x="458" y="24" text-anchor="middle">자중 응력 (kPa) · 깊이 0~8 m</text>`;
    for(const z of [.25,.5,.75]){const yy=y(r.length*z);if(r.gradient>0)a+=`<path d="M145 ${yy+14}v-28m-7 7l7-7 7 7" fill="none" stroke="var(--color-action-primary)" stroke-width="2.4"/>`;}
    for(let i=0;i<=4;i++){const s=min+(max-min)*i/4;a+=`<line class="grid" x1="${x(s)}" x2="${x(s)}" y1="52" y2="282"/><text x="${x(s)}" y="306" text-anchor="middle">${fmt(s,0)}</text>`;}
    a+=`<line x1="${x(0)}" x2="${x(0)}" y1="52" y2="282" stroke="var(--color-border-strong)"/>`;
    if(b)a+=line(b.profile,p=>x(p.effective),p=>y(p.z),'var(--color-text-muted)','5 4');
    for(const [key,color] of [['total','var(--color-text-primary)'],['pore','var(--color-accent-skyblue)'],['effective','var(--color-action-primary)']])a+=line(r.profile,p=>x(p[key]),p=>y(p.z),color);
    return svgWrap(a,'상향 침투하는 포화층의 총응력, 간극수압 및 유효응력')+'<div class="chart-caption">σ는 검정, u는 하늘색, σ′는 파랑입니다. 한계 이후 음의 σ′는 선형식을 연장한 경고값이며 안정된 흙 상태가 아닙니다.</div>';
  };
  const testDiagram=(r,b,falling)=>{
    const xmax=Math.max(r.time,b?.time||0),ymax=Math.max(falling?r.initialHead:r.volume*1e6,falling?(b?.initialHead||0):(b?.volume||0)*1e6,1e-12),x=t=>65+535*t/xmax,y=v=>273-225*v/ymax,value=p=>falling?p.head:p.volume*1e6;
    let a=`<text x="65" y="25">${falling?'시간에 따른 관내 수두차 h (m)':'시간에 따른 누적 채수량 V (mL)'}</text>`;
    for(let i=0;i<=4;i++){const t=xmax*i/4,v=ymax*i/4;a+=`<line class="grid" x1="65" x2="600" y1="${y(v)}" y2="${y(v)}"/><text x="52" y="${y(v)+4}" text-anchor="end">${fmt(v,falling?2:0)}</text><text x="${x(t)}" y="299" text-anchor="middle">${fmt(t,0)}</text>`;}
    if(b)a+=line(b.curve,p=>x(p.time),p=>y(value(p)),'var(--color-text-muted)','6 4');
    a+=line(r.curve,p=>x(p.time),p=>y(value(p)))+`<circle cx="${x(r.time)}" cy="${y(value(r.curve.at(-1)))}" r="4" fill="var(--color-action-primary)"/><text x="600" y="324" text-anchor="end">시간 t (s)</text>`;
    return svgWrap(a,falling?'변수위 시험 측정 양 끝값에서 역산한 투수계수와 지수 수두곡선':'정수위 시험 채수량과 시간에서 역산한 투수계수')+`<div class="chart-caption">${falling?'양 끝 수두와 시간을 측정값으로 지정하고 일정 k의 지수곡선을 복원합니다. 중간 곡선은 추가 측정값이 아닙니다.':'지정한 최종 채수량·시간과 일정 수두차로 k를 역산합니다. 중간 직선은 일정 유량 가정의 결과입니다.'}</div>`;
  };
  const flowColor=f=>`hsl(${205-38*f} 48% ${93-46*f}%)`;
  const wallDiagram=(r,pressure)=>{
    const scale=21,x=v=>325+scale*v,y=z=>47+scale*z,values=r.cells.map(c=>pressure?c.porePressure:c.head),lo=Math.min(...values),hi=Math.max(...values),range=hi-lo||1;
    let a=`<text x="189" y="24" text-anchor="middle">왼쪽 경계 h = ${fmt(r.headUp,1)} m</text><text x="457" y="24" text-anchor="middle">오른쪽 경계 h = ${fmt(r.headDown,1)} m</text>`;
    a+=r.cells.map((c,i)=>`<rect x="${x(c.x-r.dx/2)}" y="${y(c.z-r.dz/2)}" width="${r.dx*scale+.2}" height="${r.dz*scale+.2}" fill="${flowColor((values[i]-lo)/range)}"/>`).join('');
    if(!pressure){
      a+=r.contours.map(s=>line(s.points,p=>x(p.x),p=>y(p.z),'#ffffff')).join('');
      a+=r.streamlines.map(s=>line(s,p=>x(p.x),p=>y(p.z),'#174d72')).join('');
      for(const s of r.streamlines){const p=s[Math.floor(s.length*.55)],v=Seepage.velocityAt(r,p.x,p.z),speed=Math.hypot(v.vx,v.vz);if(speed>0){const dx=v.vx/speed,dy=v.vz/speed;a+=`<path d="M${x(p.x)-dx*5-dy*3} ${y(p.z)-dy*5+dx*3}L${x(p.x)+dx*2} ${y(p.z)+dy*2}L${x(p.x)-dx*5+dy*3} ${y(p.z)-dy*5-dx*3}" fill="none" stroke="#174d72" stroke-width="1.5"/>`;}}
    }else{
      // Values at actual cell centres beside the wall; no interpolated pressure jump through it.
      for(const z of [1.75,5.75,9.75])for(const col of [r.nx/2-3,r.nx/2+2]){const c=r.cells[Math.floor(z/r.dz)*r.nx+col];a+=`<circle cx="${x(c.x)}" cy="${y(c.z)}" r="2" fill="white"/><text x="${x(c.x)+(c.x<0?-9:9)}" y="${y(c.z)+4}" text-anchor="${c.x<0?'end':'start'}" style="fill:#11384e;font-size:11px;paint-order:stroke;stroke:white;stroke-width:3">${fmt(c.porePressure,1)} kPa</text>`;}
    }
    a+=`<rect x="73" y="47" width="504" height="252" fill="none" stroke="var(--color-border-strong)"/><path d="M325 40V${y(r.wallDepth)}" fill="none" stroke="#303f43" stroke-width="5"/><text x="335" y="${Math.min(285,y(r.wallDepth)+15)}" style="fill:#203f49;paint-order:stroke;stroke:white;stroke-width:3">D = ${fmt(r.wallDepth,1)} m</text><path d="M73 302H577" stroke="var(--color-text-primary)" stroke-width="2"/><text x="325" y="327" text-anchor="middle">24 m × 12 m · 바닥 무유량 · 가로/세로 동일 축척</text><text x="64" y="51" text-anchor="end">0 m</text><text x="64" y="300" text-anchor="end">12 m</text>`;
    const colorKey=`<div class="chart-caption" style="display:flex;align-items:center;justify-content:center;gap:8px;margin-bottom:6px"><span>${pressure?'u (kPa)':'h (m)'} · ${fmt(lo,pressure?1:2)}</span><span aria-hidden="true" style="display:inline-block;width:140px;height:8px;border-radius:3px;background:linear-gradient(90deg,${flowColor(0)},${flowColor(1)})"></span><span>${fmt(hi,pressure?1:2)}</span></div>`;
    return svgWrap(a,pressure?'차수벽 양쪽의 계산된 간극수압 분포':'차수벽 주변의 계산된 유선과 등수두선')+colorKey+`<div class="chart-caption">${pressure?'색 = 간극수압. 표시는 벽 옆 실제 셀 중심값입니다.':'색 = 전수두 · 흰색 = 등수두선 · 남색 = 유선 및 유동 방향.'} 지표·양옆의 수두는 지정값이며 바닥·차수벽은 불투수입니다.</div>`;
  };
  const layeredDiagram=(r,pressure)=>{
    const ymax=r.length,y=z=>52+238*z/ymax,max=pressure?r.gammaW*(r.headDifference+r.length):Math.max(r.headDifference,1),x=v=>315+280*v/max,value=p=>pressure?p.pressure:p.head;
    let a=`<text x="128" y="25" text-anchor="middle">위 → 아래 ${r.order}</text><text x="454" y="25" text-anchor="middle">${pressure?'간극수압 u (kPa)':'전수두 h (m)'}</text>`;
    for(const l of r.layers)a+=`<rect x="80" y="${y(l.startZ)}" width="97" height="${238*l.thickness/r.length}" fill="${l.name==='A'?'var(--color-primary-soft)':'var(--color-bg-surface-alt-2)'}" stroke="var(--color-border-strong)"/><text x="128" y="${y((l.startZ+l.endZ)/2)-5}" text-anchor="middle">${l.name} · ${fmt(l.thickness,1)} m</text><text x="128" y="${y((l.startZ+l.endZ)/2)+14}" text-anchor="middle" style="font-size:10px">k = ${sci(l.k)}</text><line x1="184" x2="607" y1="${y(l.endZ)}" y2="${y(l.endZ)}" stroke="var(--color-border-strong)" stroke-dasharray="2 5"/>`;
    for(let i=0;i<=4;i++){const v=max*i/4;a+=`<line class="grid" x1="${x(v)}" x2="${x(v)}" y1="52" y2="290"/><text x="${x(v)}" y="315" text-anchor="middle">${fmt(v,pressure?0:1)}</text>`;}
    const corners=layers=>[{z:0,head:0,pressure:0},...layers.map(l=>({z:l.endZ,head:l.endHead,pressure:l.endPressure}))];
    a+=line(corners(r.reversedLayers),p=>x(value(p)),p=>y(p.z),'var(--color-text-muted)','6 4')+line(corners(r.layers),p=>x(value(p)),p=>y(p.z));
    a+=`<text x="128" y="315" text-anchor="middle">유동 ↑</text><text x="296" y="56" text-anchor="end">0 m</text><text x="296" y="293" text-anchor="end">${fmt(r.length,1)} m</text>`;
    return svgWrap(a,'두 포화층의 순서를 바꾸었을 때 내부 수두 또는 수압 분포 비교')+'<div class="chart-caption">회색 점선은 현재 A·B의 두께·k를 유지하고 순서만 바꾼 해입니다. 저장한 기준선과 구분합니다.</div>';
  };
  const capillaryDiagram=(r,b)=>{
    const y=z=>46+31*z,x=u=>434+2*u;
    let a=`<rect x="75" y="46" width="133" height="248" fill="var(--color-bg-surface-alt-1)"/><rect x="75" y="${y(r.top)}" width="133" height="${(8-r.top)*31}" fill="var(--color-primary-soft)"/><rect x="75" y="${y(r.waterDepth)}" width="133" height="${(8-r.waterDepth)*31}" fill="var(--color-action-primary)" opacity=".18"/><text x="141" y="25" text-anchor="middle">지표</text><text x="446" y="25" text-anchor="middle">게이지 수압 u (kPa)</text>`;
    for(let z=0;z<=8;z+=2)a+=`<text x="61" y="${y(z)+4}" text-anchor="end">${z} m</text><line class="grid" x1="290" x2="610" y1="${y(z)}" y2="${y(z)}"/>`;
    for(const u of [-40,0,40,80])a+=`<line class="grid" x1="${x(u)}" x2="${x(u)}" y1="46" y2="294"/><text x="${x(u)}" y="318" text-anchor="middle">${u}</text>`;
    a+=`<path d="M75 ${y(r.waterDepth)}H610" stroke="var(--color-accent-skyblue)" stroke-dasharray="5 4"/><text x="215" y="${y(r.waterDepth)-7}" style="font-size:11px">수위 · u=0</text><path d="M75 ${y(r.top)}H208" stroke="var(--color-action-primary)" stroke-dasharray="3 3"/><text x="141" y="${y((r.top+r.waterDepth)/2)+4}" text-anchor="middle" style="font-size:11px">포화 모관대</text>`;
    if(b)a+=line([{z:b.top,pore:b.topPressure},{z:8,pore:b.gammaW*(8-b.waterDepth)}],p=>x(p.pore),p=>y(p.z),'var(--color-text-muted)','5 4');
    a+=line([{z:r.top,pore:r.topPressure},{z:8,pore:r.gammaW*(8-r.waterDepth)}],p=>x(p.pore),p=>y(p.z));
    if(r.observation.pore!==null)a+=`<circle cx="${x(r.observation.pore)}" cy="${y(r.observationDepth)}" r="5" fill="var(--color-action-primary)" stroke="white" stroke-width="2"/>`;
    return svgWrap(a,'지하수위 위의 지정된 포화 모관대에서 음의 정수압')+'<div class="chart-caption">모관대 위는 회색의 미해석 영역입니다. 포화 모관대의 높이는 입력 조건이며 입경으로 예측한 값이 아닙니다.</div>';
  };
  const darcyDefaults={headDifference:2,length:4,area:.2,logK:-4,porosity:.35,gammaSat:20,testLength:.2,testArea:.01,testTime:600,initialHead:1,finalHead:.5,tubeArea:.0001,constantDifference:1,volumeMl:500};
  const darcyBounds={headDifference:[0,8,'수두차','m'],length:[.5,8,'길이','m'],area:[.05,2,'면적','m²'],logK:[-8,-2,'log₁₀k',''],porosity:[.15,.6,'간극률',''],gammaSat:[16,24,'포화단위중량','kN/m³'],testLength:[.05,.5,'시험 시료 길이','m'],testArea:[.002,.02,'시험 시료 면적','m²'],testTime:[10,3600,'시험 시간','s'],initialHead:[.05,3,'시작 수두','m'],finalHead:[.01,2.5,'끝 수두','m'],tubeArea:[.00001,.0005,'관 면적','m²'],constantDifference:[.05,3,'시험 수두차','m'],volumeMl:[0,3000,'채수량','mL']};
  const testControls=(d,falling)=>`<div class="parameter-grid">${falling?fieldControl('initialHead','시작 수두차 h₁',d.initialHead,.05,3,.05,'m')+fieldControl('finalHead','끝 수두차 h₂',d.finalHead,.01,2.5,.01,'m','h₁ > h₂ > 0'):fieldControl('constantDifference','일정 수두차 Δh',d.constantDifference,.05,3,.05,'m')+fieldControl('volumeMl','누적 채수량 V',d.volumeMl,0,3000,10,'mL')}${fieldControl('testTime','측정 시간 t',d.testTime,10,3600,10,'s')}</div><details class="setting"><summary>시험 시료·관 치수</summary>${numericRow('testLength','시료 길이 L',d.testLength,'m',.05,.5,.01)}${numericRow('testArea','시료 면적 A',d.testArea,'m²',.002,.02,.001)}${falling?numericRow('tubeArea','관 면적 a',d.tubeArea,'m²',.00001,.0005,.00001):''}</details>`;
  return [
    {key:'darcy',meta:{name:'투수와 침투력',sub:'수두차·유량·시험',group:'물과 응력 / Darcy 법칙',navGroup:'water',words:'투수 침투 수두 동수경사 유량 Darcy 한계동수경사 보일링 정수위 변수위 투수시험 k',questions:[['flow','유량과 수두'],['upward','상향 침투'],['constant','정수위 시험'],['falling','변수위 시험']]},defaults:darcyDefaults,bounds:darcyBounds,labels:Object.fromEntries(Object.entries(darcyBounds).map(([k,v])=>[k,[v[2],v[3]]])),
      activeFields:(d,q)=>q==='constant'?['constantDifference','testTime','testLength','testArea','volumeMl']:q==='falling'?['initialHead','finalHead','testTime','testLength','testArea','tubeArea']:q==='upward'?['headDifference','length','gammaSat']:['headDifference','length','area','logK','porosity'],
      compute:(d,q)=>q==='constant'?Seepage.constantHead({headDifference:d.constantDifference,time:d.testTime,length:d.testLength,area:d.testArea,volume:d.volumeMl/1e6}):q==='falling'?Seepage.fallingHead({initialHead:d.initialHead,finalHead:d.finalHead,time:d.testTime,length:d.testLength,area:d.testArea,tubeArea:d.tubeArea}):q==='upward'?Seepage.darcy({headDifference:d.headDifference,length:d.length,gammaSat:d.gammaSat}):Seepage.darcy({headDifference:d.headDifference,length:d.length,area:d.area,logK:d.logK,porosity:d.porosity}),
      controls:(d,q)=>q==='falling'||q==='constant'?testControls(d,q==='falling'):`<div class="parameter-grid">${fieldControl('headDifference','전수두 차 Δh',d.headDifference,0,8,.1,'m')}${fieldControl('length','흐름 길이 L',d.length,.5,8,.1,'m')}${q==='upward'?fieldControl('gammaSat','포화단위중량 γsat',d.gammaSat,16,24,.1,'kN/m³','자중과 상향 침투력을 비교합니다.'):fieldControl('area','흐름 단면적 A',d.area,.05,2,.05,'m²')}${q==='upward'?'':fieldControl('logK','투수계수 지수 log₁₀k',d.logK,-8,-2,.2,'','k 단위 m/s · 지수가 1 증가하면 k는 10배입니다.')}</div>${q==='flow'?`<details class="setting"><summary>실제 공극 통과속도</summary>${numericRow('porosity','간극률 n',d.porosity,'',.15,.6,.01)}</details>`:''}`,
      render:({result:r,baseline:b,question:q})=>{
        const source=`${link(usace,'USACE EM 1110-2-1901, §§2-1·4-9')}의 Darcy 법칙 및 침투력. ${link(usbr,'USBR Research Report 3')}의 정수위·변수위 시험식.`;
        if(q==='constant'||q==='falling'){const falling=q==='falling';return {title:falling?'수두가 떨어지는 시간을 재면 k를 구할 수 있을까요?':'일정한 수두차에서 채수량을 재면 k는?',conditions:['포화 시료','일정한 투수계수','교육용 시험 입력'],plotTitle:falling?'변수위 · 수두 감소':'정수위 · 누적 채수량',comparisonPlot:!!b,chart:testDiagram(r,b,falling),results:metric('역산한 k',r.k*1e6,'μm/s',b?b.k*1e6:null,true,3)+metric('측정 시간',r.time,'s',b?.time??null)+metric(falling?'수두비 h₁/h₂':'채수량',falling?r.initialHead/r.finalHead:r.volume*1e6,falling?'':'mL',b?(falling?b.initialHead/b.finalHead:b.volume*1e6):null,false,2),explanation:`<strong>k = ${sci(r.k)} m/s.</strong> ${falling?'같은 수두비를 더 짧은 시간에 통과하면 k가 커집니다. 수두 감소율은 일정하지 않고 지수적으로 작아집니다.':'길이·면적·수두차가 같을 때 같은 시간에 더 많이 모이면 k가 큽니다.'}<span class="hint">시료의 k를 직접 지정하는 유량 탭과 달리, 이 탭은 시험 관측값에서 k를 역산합니다.</span>`,theory:`<h3>${falling?'관의 물수지와 Darcy 법칙':'정수위의 일정 유량'}</h3><div class="theory-formula">${falling?'k = aL/(At) · ln(h₁/h₂)<br>h(t) = h₁ exp[−kAt/(aL)]':'Q = V/t<br>k = VL/(AtΔh)'}<br>k = ${sci(r.k)} m/s</div><p class="theory-meta">μm/s는 결과를 읽기 쉬운 단위입니다. 1 μm/s = 10⁻⁶ m/s. 물의 점성·시험온도 보정과 시료 변형은 제외합니다.</p>`,method:`<div><h3>관측과 곡선</h3><p>${falling?'h₁,h₂,t,a,A,L을 지정합니다. 관 수위 감소에 따른 유출량 a(h₁−h₂)와 Darcy 유량을 적분합니다. 하류 수두는 고정입니다.':'V,t,Δh,A,L을 지정합니다. 채수량 1 mL=10⁻⁶ m³로 환산하며 일정 유량으로 그래프를 그립니다.'}</p></div><div><h3>근거와 한계</h3><p>${source}</p><p>포화·층류·균질 시료입니다. 장치 누수, 끝단 손실, 시료 교란, 탈기, 온도 보정은 별도 시험 관리 항목입니다.</p></div>`};}
        const upward=q==='upward';return {title:upward?'물이 위로 흐르면 흙의 자중을 얼마나 덜어낼까요?':'수두차·길이·면적을 바꾸면 유량은?',conditions:['포화·정상류','균질·Darcy 층류',upward?'지표 h=0 · 바닥 h=Δh':'수평 시료 · 출구 h=0'],plotTitle:upward?'상향 침투 · 자중 유효응력':'전수두 분포 · 피에조미터',comparisonPlot:!!b,legend:upward?'<span class="legend-item"><i class="dark"></i>σ</span><span class="legend-item"><i class="blue"></i>u</span><span class="legend-item"><i></i>σ′</span>':headLegend,chart:upward?upwardDiagram(r,b):darcyDiagram(r,b),results:upward?metric('동수경사 i',r.gradient,'',b?.gradient??null,true,2)+metric('한계 ic',r.criticalGradient,'',b?.criticalGradient??null,false,2)+metric('바닥 σ′',r.upwardBase.effective,'kPa',b?.upwardBase.effective??null):metric('유량 Q',r.flowLitresMinute,'L/min',b?.flowLitresMinute??null,true,3)+metric('동수경사 i',r.gradient,'',b?.gradient??null,false,2)+metric('Darcy 속도 v',r.velocity*1e3,'mm/s',b?b.velocity*1e3:null,false,4),explanation:upward?`${r.stableSkeleton?`현재 i/ic=${fmt(r.gradient/r.criticalGradient,2)}. 상향 침투력이 자중 유효응력을 줄입니다.`:'<strong>i ≥ ic: 이 단순 자중 모형에서는 흙 골격이 유효 압축응력을 유지할 수 없습니다.</strong>'}<span class="hint">한계경사는 균질한 포화토의 1D 자중 평형입니다. 입자 유실·파이핑 개시나 설계 안전율을 직접 판정하지 않습니다.</span>`:`<strong>Q = k · (Δh/L) · A.</strong> k=${sci(r.k)} m/s이며, Q/A인 Darcy 속도와 공극 내부의 평균속도 v/n=${fmt(r.poreVelocity*1e3,4)} mm/s를 구분합니다.<span class="hint">면적을 키우면 총유량은 커지지만 같은 수두경사에서 Darcy 속도는 같습니다.</span>`,theory:`<h3>${upward?'침투력과 수중 자중의 균형':'물은 전수두가 높은 쪽에서 낮은 쪽으로'}</h3><div class="theory-formula">i = Δh/L = ${fmt(r.gradient,3)}<br>${upward?`u(z) = γw(1+i)z<br>σ′(z) = [γsat−γw−iγw]z<br>ic = (γsat−γw)/γw = ${fmt(r.criticalGradient,3)}`:`v = ki · Q = kiA<br>k = ${sci(r.k)} m/s<br>v공극 = v/n = ${sci(r.poreVelocity)} m/s`}</div><p class="theory-meta">${upward?'그림의 음의 σ′는 골격 불안정 조건을 드러내는 수식 연장값입니다. 변형·입자 이동을 예측하지 않습니다.':'피에조미터는 압력수두와 위치수두를 합한 전수두를 보여줍니다. 이 탭에서는 모든 계측 위치의 높이가 같습니다.'}</p>`,method:`<div><h3>정의</h3><p>γw=9.81 kN/m³. 전수두 h=u/γw+위치수두이며 속도수두를 무시합니다. Q는 m³/s, k는 m/s, i는 무차원입니다.</p><p>${upward?'깊이 z는 아래로 양수입니다. 위치수두는 −z이므로 h=iz에서 u=γw(h+z)입니다. 위쪽 흐름의 침투력 크기는 단위체적당 iγw입니다.':'시료 양 끝 전수두를 고정하고 균질 시료의 정상 1D 해인 직선을 그립니다.'}</p></div><div><h3>원출처</h3><p>${source}</p><p>이 예제에는 불포화 흐름·난류·이력·층상 흐름을 포함하지 않습니다. 층상 흐름은 별도 실험에서 다룹니다.</p></div>`};
      }},
    {key:'seepage',meta:{name:'차수벽과 유선',sub:'등수두선·수압·이방성',group:'물과 응력 / 2D 정상 침투',navGroup:'water',words:'침투 유선망 등수두선 차수벽 흙막이 sheet pile cutoff 이방성 수압 유량',questions:[['flow','유선·등수두선'],['pressure','간극수압']]},defaults:{wallDepth:6,headUp:6,headDown:1,logK:-4,logAnisotropy:0},bounds:{wallDepth:[0,12,'벽 깊이','m'],headUp:[0,10,'왼쪽 수두','m'],headDown:[0,10,'오른쪽 수두','m'],logK:[-8,-2,'log₁₀kz',''],logAnisotropy:[-1,1,'log₁₀(kx/kz)','']},labels:{wallDepth:['벽 깊이','m'],headUp:['왼쪽 수두','m'],headDown:['오른쪽 수두','m'],logK:['log₁₀kz',''],logAnisotropy:['log₁₀(kx/kz)','']},compute:d=>Seepage.wall(d),
      controls:d=>`<div class="parameter-grid">${fieldControl('wallDepth','차수벽 관입 D',d.wallDepth,0,12,.5,'m','0.5 m 격자와 일치하는 깊이')}${fieldControl('headUp','왼쪽 경계 전수두',d.headUp,0,10,.25,'m','지표 기준 · 지표 위의 지정 수두')}${fieldControl('headDown','오른쪽 경계 전수두',d.headDown,0,10,.25,'m')}${fieldControl('logK','수직 투수계수 log₁₀kz',d.logK,-8,-2,.2,'','kz 단위 m/s · kx/kz를 유지하며 두 계수 함께 변경')}${fieldControl('logAnisotropy','이방성 log₁₀(kx/kz)',d.logAnisotropy,-1,1,.1,'','−1 → 0.1배 · 0 → 같음 · +1 → 10배')}</div><p class="parameter-note">지표·양옆 수두를 고정한 완전 포화 영역입니다. 굴착면의 자유수면·지하수위 저하를 계산하는 모형은 아닙니다.</p>`,
      render:({result:r,baseline:b,question:q})=>({title:q==='pressure'?'같은 깊이에서도 벽 양쪽 수압이 다를까요?':'벽을 더 깊게 넣거나 이방성을 바꾸면 물길은?',conditions:['포화·정상 2D 흐름','영역 24 m × 12 m','48 × 24 격자','불투수 차수벽'],plotTitle:q==='pressure'?'계산된 간극수압 u':'계산된 전수두와 유선',legend:q==='pressure'?'<span class="legend-item">색: 간극수압</span>':'<span class="legend-item">흰 선: 등수두선</span><span class="legend-item">남색: 유선</span>',chart:wallDiagram(r,q==='pressure'),results:metric('벽 아래 통과유량',Math.abs(r.throughWall)*60000,'L/min/m',b?Math.abs(b.throughWall)*60000:null,true,3)+metric('출구 2 m 평균 경사',r.exitGradient2m,'',b?.exitGradient2m??null,false,3)+metric('투수계수 비 kx/kz',r.ratio,'',b?.ratio??null,false,2),explanation:`<strong>${r.headUp===r.headDown?'양쪽 수두가 같아 흐름이 없습니다.':r.wallDepth===12?'벽이 불투수 바닥까지 닿아 양쪽 사이 통과유량이 0입니다.':`물은 ${r.headUp>r.headDown?'왼쪽에서 오른쪽':'오른쪽에서 왼쪽'}으로 벽 끝을 돌아갑니다.`}</strong> kx=${sci(r.kx)}, kz=${sci(r.kz)} m/s.<span class="hint">두 투수계수를 같은 배율로 바꾸면 이 경계조건의 수두·유선 모양은 같고 유량만 비례합니다. kx/kz를 바꾸면 물길도 변합니다.</span><p class="theory-meta">해석 수렴: ${r.iterations}회 · 최대 수두 잔차 ${sci(r.residual)} m · 유입/유출 차 ${sci(r.massBalance*100)}% · 격자 0.5 m</p>`,theory:`<h3>수두를 먼저 풀고, 유량과 수압을 구합니다</h3><div class="theory-formula">kx ∂²h/∂x² + kz ∂²h/∂z² = 0<br>vx = −kx ∂h/∂x · vz = −kz ∂h/∂z<br>위치수두 = −z · u = γw(h+z)</div><div class="theory-grid"><div><span>전체 유입 / 유출 · 단위 폭</span><strong>${sci(r.totalIn)} / ${sci(r.totalOut)} m²/s</strong><p>모든 외곽 경계에서 셀 면 유량을 합해 보존을 확인합니다.</p></div><div><span>출구 지표 셀의 최대 수직 경사</span><strong>${fmt(r.exitGradientMax,3)}</strong><p>0.5 m 격자의 국부값으로 격자 크기와 경계에 민감합니다. 파이핑 안전율로 사용하지 않습니다.</p></div></div><p class="theory-meta">이방성 토층에서는 유선과 등수두선이 실제 좌표에서 항상 직교하지 않습니다. 회색 벽은 두께 0의 불투수 경계를 화면에서 굵게 표시했습니다.</p>`,method:`<div><h3>경계와 계산</h3><p>x=−12~12 m, 깊이 z=0~12 m. 왼쪽 외곽과 왼쪽 지표는 hL, 오른쪽 외곽과 오른쪽 지표는 hR입니다. 바닥 및 지표에서 D까지의 x=0 면은 무유량입니다. 자유수면을 찾지 않습니다.</p><p>셀 중심 유한체적법으로 각 면의 Darcy 유량을 보존하며 SOR로 풉니다. 정규화 수두 잔차 &lt;10⁻¹⁰에서 종료합니다. 등수두선은 계산된 h의 marching squares, 유선은 면 유속장에서 적분하며 차수벽을 통과시키지 않습니다.</p></div><div><h3>검증·적용 범위</h3><p>${link(usace,'USACE EM 1110-2-1901, Chapter 4')}의 경계조건·Laplace 식·이방성 개념을 사용합니다. ${link('https://pubs.usgs.gov/tm/6a46/tm6-a46.pdf','USGS TM 6-A46')}의 셀 면 conductance 원리와 같은 보존 형태이며 MODFLOW 자체를 실행하는 것은 아닙니다.</p><p>기본값 유량은 24×12: 2.59414×10⁻⁴, 48×24: 2.64909×10⁻⁴, 96×48: 2.67714×10⁻⁴ m²/s. 연속 격자 차이는 약 2.1%, 1.05%로 감소합니다. 이 수치 검증은 현장 설계 검증을 뜻하지 않습니다.</p><p>D=0에서는 지표 중앙의 지정 수두가 불연속이므로 국부 경사는 특이점에 민감합니다. 유량은 화면 밖 폭 1 m 기준이며 내부침식·흙 변형·비정상 흐름은 제외합니다.</p></div>`})},
    {key:'layered-seepage',meta:{name:'층상 지반의 투수',sub:'층 순서·수두 손실',group:'물과 응력 / 층상 1D 침투',navGroup:'water',words:'층상 층순서 직렬 등가 투수계수 수두손실 수압 경계 D04',questions:[['head','수두 손실'],['pressure','간극수압']]},defaults:{thicknessA:2,thicknessB:2,logKA:-4,logKB:-6,headDifference:2,area:1,order:'AB'},bounds:{thicknessA:[.5,5,'A층 두께','m'],thicknessB:[.5,5,'B층 두께','m'],logKA:[-8,-2,'log₁₀kA',''],logKB:[-8,-2,'log₁₀kB',''],headDifference:[0,8,'수두차','m'],area:[.1,5,'단면적','m²']},labels:{thicknessA:['A 두께','m'],thicknessB:['B 두께','m'],logKA:['log₁₀kA',''],logKB:['log₁₀kB',''],headDifference:['수두차','m'],area:['면적','m²'],order:['위→아래 층 순서','']},compute:d=>Seepage.layered(d),
      controls:d=>`<div class="select-row"><label for="layer-order">위 → 아래 층 순서</label><select id="layer-order" data-field="order"><option value="AB" ${d.order==='AB'?'selected':''}>A 위 · B 아래</option><option value="BA" ${d.order==='BA'?'selected':''}>B 위 · A 아래</option></select></div><div class="parameter-grid">${fieldControl('logKA','A층 log₁₀k',d.logKA,-8,-2,.2,'','k 단위 m/s')}${fieldControl('logKB','B층 log₁₀k',d.logKB,-8,-2,.2,'')}${fieldControl('thicknessA','A층 두께',d.thicknessA,.5,5,.1,'m')}${fieldControl('thicknessB','B층 두께',d.thicknessB,.5,5,.1,'m')}${fieldControl('headDifference','바닥→지표 전수두 차',d.headDifference,0,8,.1,'m')}</div><details class="setting"><summary>단면적</summary>${numericRow('area','흐름 단면적 A',d.area,'m²',.1,5,.1)}</details>`,
      render:({result:r,baseline:b,question:q})=>({title:'층의 순서만 바꾸면 유량과 내부 수압이 함께 바뀔까요?',conditions:['포화·정상·상향 1D','같은 단면적의 두 층','지표 h=0 · 바닥 h=Δh'],plotTitle:q==='pressure'?'층 경계와 간극수압':'투수 저항에 따른 수두 손실',legend:'<span class="legend-item"><i></i>선택 순서</span><span class="legend-item"><i class="dashed"></i>순서만 반전</span>',chart:layeredDiagram(r,q==='pressure'),results:metric('유량 Q',r.flow*60000,'L/min',b?b.flow*60000:null,true,4)+metric('수직 등가 kv',r.equivalentK*1e6,'μm/s',b?b.equivalentK*1e6:null,false,3)+metric('전체 깊이 중간점 u',r.midpoint.pressure,'kPa',b?.midpoint.pressure??null,false,2),explanation:`<strong>순서만 바꾸면 Q와 수직 등가 k는 같습니다.</strong> 하지만 같은 중간 깊이 ${fmt(r.length/2,1)} m의 수압은 현재 ${fmt(r.midpoint.pressure,2)} kPa, 반전하면 ${fmt(r.reversedMidpoint.pressure,2)} kPa입니다.<span class="hint">낮은 k층은 같은 유량을 통과시키기 위해 더 큰 수두경사를 사용합니다. 층 경계에서 수두·수압은 연속이고 기울기가 달라집니다.</span>`,theory:`<h3>직렬 흐름: 저항 L/k의 합</h3><div class="theory-formula">v = Δh / Σ(Lj/kj) · Q = Av<br>kv = ΣLj / Σ(Lj/kj) = ${sci(r.equivalentK)} m/s<br>ij = v/kj · Δhj = ijLj<br>u(z) = γw[h(z)+z]</div><div class="theory-grid">${r.layers.map(l=>`<div><span>${l.name}층 · k=${sci(l.k)} m/s</span><strong>i = ${fmt(l.gradient,3)}</strong><p>이 층 수두차 ${fmt(l.endHead-l.startHead,3)} m</p></div>`).join('')}</div><p class="theory-meta">층 평행 흐름의 등가 kh=Σ(kjLj)/ΣLj=${sci(r.parallelK)} m/s와 구분합니다. 현재 그림과 Q는 층에 수직인 직렬 흐름입니다.</p>`,method:`<div><h3>순서 비교의 조건</h3><p>포화된 A·B층의 두께, 투수계수, 면적 및 양 끝 전수두를 유지하며 순서만 바꿉니다. 같은 Darcy 속도가 각 층을 지나므로 Δh=Σ(vLj/kj)이고 이를 풀어 Q를 얻습니다. 층의 위치는 저항 합에 영향을 주지 않지만 내부 h(z)에 영향을 줍니다.</p><p>그림 점선은 저장 기준이 아닌 현재 입력의 반전 해입니다. 중간 깊이 수압을 같은 위치에서 비교합니다. 침투에 따른 변형·유효응력 안정성은 이 그림에서 판정하지 않습니다.</p></div><div><h3>근거</h3><p>${link(usace,'USACE EM 1110-2-1901, §§2-1·4-7')}의 Darcy 법칙과 층상·이방성 투수의 수두 손실·유량 보존 원리. 본 계산은 각 층의 1D 선형해를 위 식으로 직접 결합한 해석해입니다.</p></div>`})},
    {key:'capillary',meta:{name:'모관대와 음의 수압',sub:'수위 위의 정수압',group:'물과 응력 / 모관수압',navGroup:'water',words:'모관 모세관 흡수 suction 음의 간극수압 불포화 정수압',questions:[['profile','모관 수압']]},defaults:{waterDepth:3,capillaryHeight:1,observationDepth:2.5},bounds:{waterDepth:[.5,7,'수위 깊이','m'],capillaryHeight:[0,4,'포화 모관대 높이','m'],observationDepth:[0,8,'관찰 깊이','m']},labels:{waterDepth:['수위 깊이','m'],capillaryHeight:['모관대 높이','m'],observationDepth:['관찰 깊이','m']},compute:d=>Seepage.capillary(d),
      controls:d=>`<div class="parameter-grid">${fieldControl('waterDepth','지하수위 깊이',d.waterDepth,.5,7,.1,'m')}${fieldControl('capillaryHeight','지정 포화 모관대 높이',d.capillaryHeight,0,4,.1,'m','수위 깊이 이하 · 흙의 입경에서 자동 추정하지 않습니다.')}${fieldControl('observationDepth','관찰 깊이',d.observationDepth,0,8,.1,'m')}</div>`,
      render:({result:r,baseline:b})=>({title:'수위 위에서도 물이 포화되어 있으면 수압은?',conditions:['정수압 · 흐름 없음','포화 모관대 높이 지정','대기압 기준 게이지 수압'],plotTitle:'수위 아래 양압 · 포화 모관대 음압',comparisonPlot:!!b,chart:capillaryDiagram(r,b),results:metric('관찰점 u',r.observation.pore??'미해석',r.observation.pore===null?'':'kPa',b?.observation.pore??null,true,2)+metric('모관대 상단 u',r.topPressure,'kPa',b?.topPressure??null,false,2)+metric('모관대 상단 깊이',r.top,'m',b?.top??null,false,1),explanation:r.observation.pore===null?'관찰점은 지정한 포화 모관대보다 위입니다. 이 단순 모형은 불포화 영역의 수압을 계산하지 않으며 0으로 대체하지 않습니다.':`<strong>수위에서 u=0, 수위보다 위의 포화된 물은 음압입니다.</strong> 관찰점 u=${fmt(r.observation.pore,2)} kPa.<span class="hint">물의 압력이 대기압보다 낮다는 뜻입니다. 이 값만으로 불포화토의 강도 증가를 계산하지 않습니다.</span>`,theory:`<h3>정수압은 수위를 기준으로 부호가 바뀝니다</h3><div class="theory-formula">u = γw(z−zw)<br>모관대 상단: u = −γw hc<br>= ${fmt(r.topPressure,2)} kPa</div><p class="theory-meta">z는 지표 아래 깊이, zw는 수위 깊이입니다. 이 예제는 포화된 모관대 내부의 압력만 계산합니다. 실제 모관 높이, 보수곡선(SWCC), 포화도, 불포화 투수계수는 계산하지 않습니다.</p>`,method:`<div><h3>압력의 범위</h3><p>지정 모관대 상단부터 지하수위 아래까지 정수압 관계를 연장합니다. 상단보다 위는 해석하지 않으며 음의 수압을 0으로 잘라내지 않습니다. 기포 유입이나 건조 이력에 따른 수분 분포를 재현하지 않습니다.</p></div><div><h3>근거</h3><p>${link(fhwa,'FHWA NHI-06-088 §2.10')}의 수위 위 모관상승과 음의 간극수압 설명. 압력식은 흐름 없는 물의 정수압 평형이며, 불포화 유효응력·강도 모형과 구분합니다.</p></div>`})}
  ];
})();
