const SlopeLabs=(()=>{
 const source='<a href="https://faculty.washington.edu/kramer/522/ArmySlopeStabilityManual.pdf" target="_blank" rel="noopener">USACE EM 1110-2-1902, Slope Stability</a>';
 const waterSource='<a href="https://www.usbr.gov/tsc/techreferences/designstandards-datacollectionguides/finalds-pdfs/DS13-4.pdf" target="_blank" rel="noopener">USBR Design Standards 13, Chapter 4</a>';
 const rad=x=>x*Math.PI/180,stageNames={initial:'저하 전',slow:'배수된 저하 후',rapid:'수압이 남은 저하 후'};
 const defs={beta:25,depth:2,cohesion:5,phi:30,gammaMoist:18,gammaSat:20,waterFraction:.5,surcharge:0,weakDepth:3,strongDepth:1.5,waterDepth:.4,phiStrong:35,phiWeak:15,gamma:20,wedgeLength:12,faceAngle:30,slipAngle:20,initialWater:3,finalWater:.5,stage:'rapid',"circularHeight":8,"circularBeta":30,"circularEntry":0.6,"circularCenter":1.5,"circularCohesion":0,"circularPhi":28,"circularGamma":19,"circularRu":0,"circularSlices":40,"circularSlicePercent":50};
 const fields={"circularHeight":[2,20,0.5,"사면 높이 H","m"],"circularBeta":[15,50,1,"사면 경사 β","°"],"circularCohesion":[0,40,0.5,"유효점착력 c′","kPa"],"circularPhi":[0,45,1,"유효마찰각 φ′","°"],"circularRu":[0,0.6,0.01,"수압비 rᵤ",""],"circularGamma":[14,24,0.1,"일정 총단위중량 γ","kN/m³"],"circularEntry":[0.15,1.5,0.05,"사면 어깨 뒤 진입 거리 / H",""],"circularCenter":[1.05,2.5,0.05,"원호 중심 높이 / H",""],"circularSlices":[10,80,1,"절편 개수 n","개"],"circularSlicePercent":[0,100,1,"살펴볼 절편 위치","%"],beta:[5,45,1,'사면각 β','°'],depth:[.25,8,.25,'활동면의 수직 깊이 z','m'],cohesion:[0,30,.5,'유효점착력 c′','kPa'],phi:[0,45,1,'유효마찰각 φ′','°'],gammaMoist:[14,24,.1,'습윤 γ','kN/m³'],gammaSat:[16,26,.1,'포화 γsat','kN/m³'],waterFraction:[0,1,.05,'활동면 위 포화 두께 / z',''],surcharge:[0,80,1,'연직 상재 q','kPa'],weakDepth:[.25,8,.25,'약층 후보면 깊이','m'],strongDepth:[.25,8,.25,'모층 후보면 깊이','m'],waterDepth:[0,10,.1,'지표에서 평행 수면까지','m'],phiStrong:[10,45,1,'모층 마찰각','°'],phiWeak:[0,40,1,'약층 마찰각','°'],gamma:[14,26,.1,'일정 총단위중량 γ','kN/m³'],wedgeLength:[6,20,.5,'쐐기 수평 길이 L','m'],faceAngle:[20,55,1,'쐐기 사면각 β','°'],slipAngle:[5,35,1,'쐐기 활동면각 α','°'],initialWater:[0,6,.1,'저하 전 수위 h₀','m'],finalWater:[0,6,.1,'저하 후 수위 h₁','m']};
 const active=q=>q==='circular'?["circularHeight","circularBeta","circularCohesion","circularPhi","circularRu","circularGamma","circularEntry","circularCenter","circularSlices","circularSlicePercent"]:q==='infinite'?['beta','depth','cohesion','phi','gammaMoist','gammaSat','waterFraction','surcharge']:q==='weak-layer'?['beta','weakDepth','strongDepth','waterDepth','cohesion','phiStrong','phiWeak','gamma']:['wedgeLength','faceAngle','slipAngle','gamma','cohesion','phi','initialWater','finalWater'];
 const control=(f,d)=>{const[min,max,step,label,unit]=fields[f];const help={waterFraction:'0은 수위가 활동면, 1은 수위가 지표. 사면과 평행한 침투입니다.',weakDepth:'수직 깊이입니다. 지정한 두 후보면의 최소값만 비교합니다.',waterDepth:'수면도 사면과 평행. 두 후보면의 수압을 각각 계산합니다.',initialWater:'사면 발끝에서 잰 높이. 뒤쪽 활동면 끝보다 낮아야 합니다.',finalWater:'0 ≤ h₁ ≤ h₀. 물 하중과 내부 수압을 따로 비교합니다.'}[f]||'';return fieldControl(f,label,d[f],min,max,step,unit,help);};
 function slopeDiagram(r,weak=false){
  const depth=weak?Math.max(r.strongDepth,r.weakDepth):r.depth,scale=Math.min(34,220/(depth+8*Math.tan(rad(r.beta)))),x=v=>50+v*scale,y=v=>285-(v+depth)*scale,g=v=>v*Math.tan(rad(r.beta)),plane=z=>`M${x(0)} ${y(g(0)-z)}L${x(8)} ${y(g(8)-z)}`;
  let a=`<text x="170" y="25" text-anchor="middle">β=${fmt(r.beta,0)}° · 深さは鉛直</text><path d="${plane(0)}L${x(8)} 300H${x(0)}Z" fill="#EEEAE3"/><path d="${plane(0)}" stroke="#5A5F68" stroke-width="2" fill="none"/>`.replace('深さは鉛直','깊이는 수직 방향');
  const zw=weak?r.waterDepth:depth-r.waterHeight;
  if(zw<=depth)a+=`<path d="${plane(zw)}L${x(8)} 300H${x(0)}Z" fill="#BFEFF6" opacity=".5"/><path d="${plane(zw)}" stroke="#0098AE" stroke-width="2" fill="none" stroke-dasharray="5 4"/>`;
  const planes=weak?[{z:r.strongDepth,label:'모층',f:r.strong.factor,color:'#737373'},{z:r.weakDepth,label:'약층',f:r.weak.factor,color:'#E7883B'}]:[{z:depth,label:'활동면',f:r.factor,color:'#0F6FFF'}];
  planes.forEach(p=>{a+=`<path d="${plane(p.z)}" stroke="${p.color}" stroke-width="3" fill="none"/><text x="${x(4)}" y="${y(g(4)-p.z)-9}" text-anchor="middle" style="fill:${p.color}">${p.label} ${fmt(p.z,2)} m</text>`;});
  if(weak){const max=Math.max(r.strong.factor,r.weak.factor,1);planes.forEach((p,i)=>{const yy=91+i*91;a+=`<text x="380" y="${yy-12}">${p.label} 후보면</text><rect x="380" y="${yy}" width="${p.f/max*220}" height="27" fill="${p.color}"/><text x="380" y="${yy+47}">저항/작용 = ${fmt(p.f,3)}</text>`;});}
  else{const max=Math.max(r.driving,r.resistance,1);[{label:'작용 전단 τ',v:r.driving,c:'#737373'},{label:'마찰 저항',v:r.friction,c:'#0F6FFF'},{label:'점착 저항',v:r.cohesion,c:'#E7883B'}].forEach((p,i)=>{const yy=78+i*69;a+=`<text x="370" y="${yy-9}">${p.label} ${fmt(p.v,2)} kPa</text><rect x="370" y="${yy}" width="${p.v/max*230}" height="22" fill="${p.c}"/>`;});}
  a+='<text x="325" y="327" text-anchor="middle">같은 축척의 평행면 · 파란 점선은 지정한 평행 수면</text>';
  return svgWrap(a,weak?'깊이와 강도가 다른 두 평행 활동면의 저항 비교':'사면과 평행한 침투를 받는 무한사면의 힘 분담');
 }
 function drawdownDiagram(r){
  const scale=Math.min(265/r.length,205/r.crestHeight),x=v=>52+v*scale,y=v=>278-v*scale,c=r.current,a=rad(r.alpha),b=rad(r.beta);
  let s=`<text x="175" y="25" text-anchor="middle">${stageNames[r.stage]}</text><path d="M${x(0)} ${y(0)}L${x(r.length)} ${y(r.crestHeight)}L${x(r.length)} ${y(r.backSlipHeight)}Z" fill="#EEEAE3" stroke="#737373"/><path d="M${x(0)} ${y(0)}L${x(r.length)} ${y(r.backSlipHeight)}" stroke="#E7883B" stroke-width="3"/>`;
  if(c.external>0)s+=`<path d="M32 ${y(c.external)}H${x(c.external/Math.tan(b))}L${x(0)} ${y(0)}H32Z" fill="#BFEFF6" opacity=".7"/><path d="M32 ${y(c.external)}H${x(c.external/Math.tan(b))}" stroke="#0098AE" stroke-width="2"/>`;
  if(c.internal>0)s+=`<path d="M${x(c.internal/Math.tan(b))} ${y(c.internal)}H${x(c.internal/Math.tan(a))}" stroke="#0098AE" stroke-width="2" stroke-dasharray="5 4"/>`;
  s+=`<text x="48" y="309">외부 ${fmt(c.external,1)} m · 내부 수압 기준 ${fmt(c.internal,1)} m</text>`;
  const max=Math.max(...r.cases.map(v=>v.factor||0),1);r.cases.forEach((v,i)=>{const yy=66+i*77;s+=`<text x="370" y="${yy}">${stageNames[v.name]}</text><rect x="370" y="${yy+10}" width="${(v.factor||0)/max*220}" height="24" fill="${v.name===r.stage?'#0F6FFF':'#C6CDD6'}"/><text x="370" y="${yy+51}">저항/작용 ${v.factor===null?'평형 범위 밖':fmt(v.factor,3)}</text>`;});
  return svgWrap(s,'같은 쐐기의 외부 수압과 활동면 수압을 나누어 비교')+'<p class="chart-caption">실선 수면: 외부 물 하중. 점선: 내부 수압을 정한 수두. 급속 저하의 실제 유선·시간해석 결과는 아닙니다.</p>';
 }
 return [{key:'slope',comparisonIgnoredFields:['circularSlicePercent'],meta:{name:'사면과 물의 힘',sub:'원호·해석법·물의 힘',group:'토압·굴착·사면 / 사면 안정',navGroup:'retaining',words:'사면 활동면 경사 마찰각 수압 약층 급속 수위저하 무한사면 안정 원호 Bishop 비숍 비샵 Fellenius Ordinary 절편 분할법 해석법',questions:[['infinite','경사·강도·물'],['weak-layer','약층의 위치'],['drawdown','물이 빠지는 순서'],['circular','원호·해석법 비교']]},defaults:defs,bounds:Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,[v[0],v[1],v[3],v[4]]])),labels:Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,[v[3],v[4]]])),activeFields:(d,q)=>active(q),compute:(d,q)=>q==='circular'?CircularSlope.prescribed(d):q==='infinite'?SlopeModels.infinite(d):q==='weak-layer'?SlopeModels.weakLayer(d):SlopeModels.drawdown({...d,length:d.wedgeLength,beta:d.faceAngle,alpha:d.slipAngle}),
  controls(d,q){if(q==='circular')return CircularSlopeView.controls(d);const primary=q==='infinite'?['beta','phi','cohesion','depth','waterFraction']:q==='weak-layer'?['weakDepth','phiWeak','waterDepth','beta']:['initialWater','finalWater','slipAngle','phi'];return (q==='drawdown'?`<div class="select-row"><label for="slope-stage">비교할 수압 상태</label><select id="slope-stage" data-field="stage">${Object.entries(stageNames).map(([v,t])=>`<option value="${v}" ${d.stage===v?'selected':''}>${t}</option>`).join('')}</select></div>`:'')+primary.map(k=>control(k,d)).join('')+`<details class="setting"><summary>${q==='weak-layer'?'모층 후보면과 공통 물성':'형상·하중·단위중량'}</summary>${active(q).filter(k=>!primary.includes(k)).map(k=>control(k,d)).join('')}</details>`;},
  render({result:r,question:q,baseline:b,data:d}){
   if(q==='circular')return CircularSlopeView.render(r,b,d);
   if(q==='drawdown'){const c=r.current,bc=b?.current;return {title:'외부 물이 먼저 빠지고, 내부 수압이 남으면?',conditions:['지정한 단일 직선 쐐기','내부·외부 수압을 각각 지정','총중량 일정 · 단위 폭 1 m'],plotTitle:'같은 쐐기에서 세 수압 상태 비교',chart:drawdownDiagram(r),legend:'',results:metric('외부 물의 지지력',c.outsideForce,'kN/m',bc?.outsideForce??null)+metric('활동면 수압 합력 U',c.poreForce,'kN/m',bc?.poreForce??null)+metric('저항 / 작용',c.factor??'평형 범위 밖','',bc?.factor??null,true,3),explanation:'<strong>외부 물 하중이 사라지는 효과와 활동면 수압이 남는 효과는 다릅니다.</strong> 느린 저하는 내부 수압도 낮아진 상태, 급속 저하 예제는 초기 활동면 수압을 그대로 남긴 상태입니다.<span class="hint">지정 수압의 힘 비교입니다. 실제 배수속도·비배수강도 변화·시간별 안정성을 예측하지 않습니다.</span>',theory:`<h3>현재 쐐기의 힘 평형</h3><div class="theory-formula">W = γ·½L²(tanβ−tanα) = ${fmt(r.weight,1)} kN/m<br>F외부 = γw h외부²/(2sinβ) = ${fmt(c.outsideForce,2)} kN/m<br>U = γw h내부²/(2sinα) = ${fmt(c.poreForce,2)} kN/m<br>N′ = Wcosα + F외부cos(β−α) − U = ${fmt(c.effectiveNormal,2)} kN/m<br>T = Wsinα − F외부sin(β−α) = ${fmt(c.driving,2)} kN/m<br>R = c′L/cosα + N′tanφ′ = ${fmt(c.resistance,2)} kN/m</div>`,method:`<p>${source}, Appendix G 및 ${waterSource}, Chapter 4는 급속 수위저하에서 수압·강도상태를 구별하는 근거입니다. 화면의 쐐기 식은 직접 힘 평형으로 유도한 제한 모형이며, 문헌의 전체 급속수위저하 절차를 구현한 것이 아닙니다.</p><p>뒤쪽 수직면은 건조한 열린 경계로 두고 초기 수위를 활동면 뒤끝보다 낮게 제한합니다. 미끄럼면을 미리 정하며 자동 최적화하지 않습니다. 수압 변화 효과를 분리하기 위해 총중량을 동일하게 둡니다. N′가 음수이거나 T≤0이면 이 저항비를 표시하지 않습니다.</p>`};}
   const weak=q==='weak-layer',v=weak?(r.critical==='strong'?r.strong:r.weak):r;
   return {title:weak?'약층이 더 깊어지면, 어느 후보면이 지배할까요?':'경사·강도·수압이 사면의 힘 균형을 어떻게 바꿀까요?',conditions:['무한사면 · 평행한 활동면','사면과 평행한 정상 침투',weak?'지정한 두 후보면만 비교':'깊이는 수직 방향'],plotTitle:weak?'후보면의 위치와 최소 저항비':'평행 활동면과 저항의 구성',legend:'',chart:slopeDiagram(r,weak),results:weak?metric('모층 후보면',r.strong.factor,'',b?.strong.factor??null,false,3)+metric('약층 후보면',r.weak.factor,'',b?.weak.factor??null,false,3)+metric('더 작은 저항비',r.minimum,'',b?.minimum??null,true,3):metric('유효 수직응력 σ′n',r.effectiveNormal,'kPa',b?.effectiveNormal??null)+metric('작용 전단 τ',r.driving,'kPa',b?.driving??null)+metric('저항 / 작용',r.factor,'',b?.factor??null,true,3),explanation:weak?`<strong>현재 ${r.critical==='equal'?'두 후보면의 값이 같습니다':r.critical==='weak'?'약층 후보면의 저항비가 더 작습니다':'모층 후보면의 저항비가 더 작습니다'}.</strong> 같은 점착력이라도 깊이가 깊어지면 자중 대비 점착력의 비중이 줄어듭니다.<span class="hint">모든 활동면을 탐색한 결과가 아닙니다. 모층·약층의 지정 깊이와 마찰각만 비교하며, 두 면의 점착력과 총단위중량은 공통입니다.</span>`:'<strong>물은 유효 수직응력을 줄여 마찰 저항을 낮춥니다.</strong> 경사가 커지면 중량의 사면방향 성분도 커집니다.<span class="hint">수압은 사면과 평행한 침투에서 구합니다. 수직 물기둥의 정수압 γw·h와 구별하세요.</span>',theory:`<h3>${weak?'더 작은 저항비의 후보면':'현재 활동면'} · 단위면적의 힘</h3><div class="theory-formula">σv = q + γm(z−hw) + γsat hw = ${fmt(v.verticalStress,2)} kPa<br>σn = σv cos²β = ${fmt(v.normal,2)} kPa<br>u = γw hw cos²β = ${fmt(v.pore,2)} kPa<br>τ = σv sinβ cosβ = ${fmt(v.driving,2)} kPa<br>R = c′ + (σn−u)tanφ′ = ${fmt(v.resistance,2)} kPa<br>F = R/τ = ${fmt(v.factor,3)}</div><p>건조·무점착이면 F=tanφ′/tanβ입니다. 이때 단위중량이나 활동면 깊이를 바꿔도 비율은 같습니다.</p>`,method:`<p>${source}, Appendix C, 식 C-22~C-29 및 Appendix E의 무한사면 관계를 참조합니다. 점착력은 Mohr–Coulomb 저항에 직접 더하고, 상재와 층별 중량은 연직응력에 합산합니다.</p><p>평면변형·무한 연장·사면 평행면의 평형입니다. 원호파괴·유한사면 끝단·보강재·지진·3차원 효과·실제 변위는 계산하지 않습니다. 수압은 지정한 평행 침투 조건이며 급속 수위저하 모델과 혼합하지 않습니다. 수치 1은 이 모형의 저항과 작용이 같은 상태일 뿐, 설계기준상 합격선을 정한 것이 아닙니다.</p>`};
  }
 }];
})();
