/** Standalone learning descriptors; helper functions execute only at render time. */
const StateLabs = (() => {
  const source='https://www.fhwa.dot.gov/engineering/geotech/pubs/05037/05a.cfm';
  const compactionSource='https://www.fhwa.dot.gov/engineering/geotech/pubs/05037/07b.cfm';
  const sourceLink=`<a href="${source}" target="_blank" rel="noopener">FHWA NHI-05-037 §5.3</a>`;
  const phaseDiagram=r=>{
    const h=202,y0=60;
    const block=(x,bottom,height,fill,label)=>`<rect x="${x}" y="${bottom-height}" width="138" height="${height}" fill="${fill}" stroke="white" stroke-width="1.3"/>${height>23?`<text x="${x+69}" y="${bottom-height/2+4}" text-anchor="middle" style="fill:${fill==='var(--color-action-primary)'?'white':'var(--color-text-secondary)'}">${label}</text>`:''}`;
    const hs=h*r.solidVolumeFraction,hw=h*r.waterVolumeFraction,ha=h*r.airVolumeFraction;
    const ws=h*r.solidWeight/r.totalWeight,ww=h*r.waterWeight/r.totalWeight;
    let a=`<text x="156" y="28" text-anchor="middle" style="font-size:15px;fill:var(--color-text-primary)">부피 구성</text><text x="480" y="28" text-anchor="middle" style="font-size:15px;fill:var(--color-text-primary)">중량 구성</text>`;
    a+=block(87,y0+h,hs,'var(--color-bg-surface-alt-2)',`흙입자 ${fmt(100*r.solidVolumeFraction)}%`)+block(87,y0+h-hs,hw,'var(--color-action-primary)',`물 ${fmt(100*r.waterVolumeFraction)}%`)+block(87,y0+ha,ha,'var(--color-bg-surface-alt-1)',`공기 ${fmt(100*r.airVolumeFraction)}%`);
    a+=`<rect x="87" y="${y0}" width="138" height="${h}" fill="none" stroke="var(--color-border-strong)"/>`;
    a+=block(411,y0+h,ws,'var(--color-bg-surface-alt-2)',`입자 ${fmt(r.solidWeight)} kN`)+block(411,y0+ww,ww,'var(--color-action-primary)',`물 ${fmt(r.waterWeight)} kN`);
    a+=`<rect x="411" y="${y0}" width="138" height="${h}" fill="none" stroke="var(--color-border-strong)"/><text x="156" y="286" text-anchor="middle">V = ${fmt(r.totalVolume,3)} m³</text><text x="480" y="286" text-anchor="middle">W = ${fmt(r.totalWeight,2)} kN</text><text x="156" y="308" text-anchor="middle">입자 부피 Vs = 1 m³ 기준</text><text x="480" y="308" text-anchor="middle">공기의 중량 ≈ 0</text><text x="318" y="151" text-anchor="middle" style="font-size:14px">w는 중량비</text><text x="318" y="177" text-anchor="middle" style="font-size:14px">S는 부피비</text>`;
    return svgWrap(a,'간극비·함수비·입자비중에 따른 부피와 중량의 각각의 구성비')+`<div class="chart-caption">각 막대는 해당 총량의 100%입니다. 부피와 중량은 서로 다른 단위·척도입니다.</div>`;
  };
  const relativeDiagram=r=>{
    const scale=204/(1+r.emax),bottom=263;
    let a='<text x="325" y="24" text-anchor="middle">같은 흙입자 부피 Vs = 1 · 모든 기둥에 동일한 부피 척도</text>';
    for(const [x,e,label,current] of [[79,r.emax,'가장 느슨한 상태',false],[268,r.e,'현재 상태',true],[457,r.emin,'가장 조밀한 상태',false]]){
      const top=bottom-(1+e)*scale;
      a+=`<rect x="${x}" y="${bottom-scale}" width="116" height="${scale}" fill="var(--color-bg-surface-alt-2)"/><rect x="${x}" y="${top}" width="116" height="${e*scale}" fill="${current?'var(--color-primary-soft)':'var(--color-bg-surface-alt-1)'}"/><rect x="${x}" y="${top}" width="116" height="${(1+e)*scale}" fill="none" stroke="${current?'var(--color-action-primary)':'var(--color-border-strong)'}" stroke-width="${current?2.5:1}"/><text x="${x+58}" y="${top+e*scale/2+4}" text-anchor="middle">간극 ${fmt(e,2)}</text><text x="${x+58}" y="${bottom-scale/2+4}" text-anchor="middle">입자 1.00</text><text x="${x+58}" y="286" text-anchor="middle" style="fill:var(--color-text-primary)">${label}</text><text x="${x+58}" y="307" text-anchor="middle">${current?'e':e===r.emax?'emax':'emin'} = ${fmt(e,2)}</text>`;
    }
    return svgWrap(a,'동일한 흙입자 부피에 대한 최대·현재·최소 간극비 비교');
  };
  const compactionDiagram=(r,b)=>{
    const xmax=Math.max(r.xMax,b?.xMax||0),ymin=Math.floor(Math.min(14,r.fieldGammaDry,r.referenceMDD,b?.fieldGammaDry??99)-1),ymax=Math.ceil(Math.max(r.Gs*r.gammaW,r.referenceMDD,r.fieldGammaDry,b?.fieldGammaDry||0));
    const xp=w=>64+550*w/xmax,yp=g=>272-(g-ymin)/(ymax-ymin)*218;
    let a='';
    for(let i=0;i<=5;i++){const g=ymin+(ymax-ymin)*i/5;a+=`<line class="grid" x1="64" x2="614" y1="${yp(g)}" y2="${yp(g)}"/><text x="52" y="${yp(g)+4}" text-anchor="end">${fmt(g,1)}</text>`;}
    for(let w=0;w<=xmax;w+=5)a+=`<line class="grid" x1="${xp(w)}" x2="${xp(w)}" y1="54" y2="272"/><text x="${xp(w)}" y="294" text-anchor="middle">${w}</text>`;
    a+='<text x="64" y="28">건조단위중량 γd (kN/m³)</text><text x="614" y="320" text-anchor="end">함수비 w (%)</text><line class="axis" x1="64" x2="614" y1="272" y2="272"/>';
    const path=points=>points.map((p,i)=>`${i?'L':'M'}${xp(p.w).toFixed(2)} ${yp(p.gammaDry).toFixed(2)}`).join(' ');
    const zav=Array.from({length:81},(_,i)=>({w:xmax*i/80,gammaDry:StateModels.zeroAirVoids({w:xmax*i/80,Gs:r.Gs,gammaW:r.gammaW})}));
    a+=`<path d="${path(zav)}" fill="none" stroke="var(--color-text-primary)" stroke-dasharray="5 4" stroke-width="1.8"/><text x="${xp(xmax*.71)}" y="${yp(StateModels.zeroAirVoids({w:xmax*.71,Gs:r.Gs,gammaW:r.gammaW}))-10}" style="fill:var(--color-text-primary)">ZAV · S = 100%</text><path d="${path(r.samples)}" fill="none" stroke="var(--color-text-muted)" stroke-width="2"/>`;
    a+=r.samples.map(p=>`<circle cx="${xp(p.w)}" cy="${yp(p.gammaDry)}" r="3.5" fill="var(--color-text-muted)"/>`).join('');
    a+=`<line x1="64" x2="614" y1="${yp(r.referenceMDD)}" y2="${yp(r.referenceMDD)}" stroke="var(--color-accent-purple)" stroke-dasharray="3 4"/><text x="609" y="${yp(r.referenceMDD)-7}" text-anchor="end" style="fill:var(--color-accent-purple)">기준 MDD ${fmt(r.referenceMDD)}</text><line x1="${xp(r.referenceOMC)}" x2="${xp(r.referenceOMC)}" y1="54" y2="272" stroke="var(--color-border-strong)" stroke-dasharray="3 4"/><text x="${xp(r.referenceOMC)+(r.referenceOMC>xmax*.8?-6:6)}" text-anchor="${r.referenceOMC>xmax*.8?'end':'start'}" y="46">OMC ${fmt(r.referenceOMC)}%</text>`;
    if(b)a+=`<circle cx="${xp(b.fieldW)}" cy="${yp(b.fieldGammaDry)}" r="6.5" fill="white" stroke="var(--color-text-muted)" stroke-width="2"/><path d="M${xp(b.fieldW)} ${yp(b.fieldGammaDry)}L${xp(r.fieldW)} ${yp(r.fieldGammaDry)}" fill="none" stroke="var(--color-text-muted)" stroke-dasharray="4 4"/>`;
    a+=`<circle cx="${xp(r.fieldW)}" cy="${yp(r.fieldGammaDry)}" r="6" fill="var(--color-action-primary)" stroke="white" stroke-width="2"/><text x="${xp(r.fieldW)+(r.fieldW>xmax*.8?-10:10)}" y="${yp(r.fieldGammaDry)+18}" text-anchor="${r.fieldW>xmax*.8?'end':'start'}" style="fill:var(--color-action-primary)">현장점</text>`;
    return svgWrap(a,'합성 다짐자료와 지정 기준 MDD·OMC, 현장점 및 영공기간극선')+'<div class="chart-caption">회색 5점·직선은 교육용 합성 자료입니다. 직선 사이의 값은 시험값이나 예측값이 아닙니다.</div>';
  };
  return [
    {key:'phases',meta:{name:'삼상관계',sub:'입자·물·공기의 비율',group:'흙의 성질 / 삼상관계',navGroup:'properties',words:'삼상관계 함수비 포화도 간극비 간극률 단위중량 비중',questions:[['phases','부피와 중량']]},defaults:{e:.65,Gs:2.65,w:15},bounds:{e:[.2,1.8,'간극비',''],Gs:[2,3,'입자비중',''],w:[0,60,'함수비','%']},labels:{e:['간극비 e',''],Gs:['입자비중 Gs',''],w:['함수비 w','%']},compute:d=>StateModels.phases(d),
      controls:d=>`<div class="parameter-grid">${fieldControl('e','간극비 e',d.e,.2,1.8,.01,'','간극 부피 / 흙입자 부피')}${fieldControl('Gs','입자비중 Gs',d.Gs,2,3,.01,'','같은 부피의 물에 대한 흙입자의 질량비')}${fieldControl('w','함수비 w',d.w,0,60,.5,'%','물 중량 / 건조 흙입자 중량 × 100')}</div><p class="parameter-note">S가 100%를 넘는 조합은 물이 간극에 들어갈 수 없는 상태입니다. 입력을 자동으로 보정하지 않습니다.</p>`,
      render:({result:r,baseline:b})=>({title:'함수비가 같아도 포화도가 다른 이유는 무엇일까요?',conditions:['Vs = 1 m³ 기준','공기 중량 무시','γw = 9.81 kN/m³'],plotTitle:'삼상관계 · 부피와 중량',chart:phaseDiagram(r),results:metric('포화도 S',r.saturation*100,'%',b?b.saturation*100:null,true)+metric('간극률 n',r.porosity*100,'%',b?b.porosity*100:null)+metric('건조 γd',r.gammaDry,'kN/m³',b?.gammaDry??null)+metric('습윤 γ',r.gammaMoist,'kN/m³',b?.gammaMoist??null),explanation:`<strong>물의 양과 물이 들어갈 공간을 함께 보세요.</strong> 현재 간극 ${fmt(r.e,3)} m³ 중 물은 ${fmt(r.waterVolume,3)} m³, 공기는 ${fmt(r.airVolume,3)} m³입니다.<span class="hint">e·Gs가 같으면 w를 바꿔도 γd는 같습니다. 습윤단위중량과 포화도는 달라집니다.</span>`,theory:`<h3>중량비를 부피비로 바꾸는 연결식</h3><div class="theory-formula">wf = w/100 = ${fmt(r.waterFraction,3)}<br>S = wf·Gs/e = ${fmt(r.saturation,3)}<br>n = e/(1+e) = ${fmt(r.porosity,3)}<br>γd = Gs·γw/(1+e) = ${fmt(r.gammaDry,2)} kN/m³<br>γ = γd(1+wf) = ${fmt(r.gammaMoist,2)} kN/m³</div><div class="theory-grid"><div><span>완전히 포화시키면</span><strong>γsat = ${fmt(r.gammaSat,2)} kN/m³</strong><p>현재의 e·Gs를 유지하며 공기를 물로 채운 값입니다.</p></div><div><span>포화 상태의 수중단위중량</span><strong>γ′ = ${fmt(r.gammaSubmerged,2)} kN/m³</strong><p>γsat−γw입니다. 현재 습윤 γ에서 물의 중량을 뺀 값이 아닙니다.</p></div></div>`,method:`<div><h3>정의와 정규화</h3><p>e=Vv/Vs, n=Vv/V, S=Vw/Vv, w=Ww/Ws입니다. 화면 입력 w는 %이며 계산에는 wf=w/100을 사용합니다.</p><p>Vs=1 m³로 놓으면 Vv=e, Vw=wf·Gs, Va=e−Vw, Ws=Gs·γw, Ww=Vw·γw가 됩니다. 두 막대는 각각의 총량으로 정규화한 구성비이며 서로 동일한 수직 단위가 아닙니다.</p></div><div><h3>가정과 근거</h3><p>입자와 물의 체적 변화, 공기 중량을 무시합니다. 흡수·팽윤·하중에 따른 변형을 예측하지 않습니다.</p><p>${sourceLink}, Table 5-8의 중량·부피 관계식. 간극률 정의는 n=Vv/V를 사용합니다.</p></div>`})},
    {key:'relative-density',meta:{name:'상대밀도',sub:'간극비의 양 끝과 현재',group:'흙의 성질 / 상대밀도',navGroup:'properties',words:'상대밀도 Dr 조밀 느슨 최소 최대 간극비 사질토',questions:[['relative','상대밀도']]},defaults:{e:.65,emin:.4,emax:.9,Gs:2.65},bounds:{e:[.2,1.6,'현재 간극비',''],emin:[.1,1.2,'최소 간극비',''],emax:[.3,1.8,'최대 간극비',''],Gs:[2,3,'입자비중','']},labels:{e:['현재 e',''],emin:['최소 emin',''],emax:['최대 emax',''],Gs:['입자비중 Gs','']},compute:d=>StateModels.relativeDensity(d),
      controls:d=>`<div class="parameter-grid">${fieldControl('e','현재 간극비 e',d.e,.2,1.6,.01,'','emin≤e≤emax인 상태를 비교합니다.')}${fieldControl('emin','최소 간극비 emin',d.emin,.1,1.2,.01,'','같은 흙의 가장 조밀한 시험 기준')}${fieldControl('emax','최대 간극비 emax',d.emax,.3,1.8,.01,'','같은 흙의 가장 느슨한 시험 기준')}</div><details class="setting"><summary>입자비중</summary>${numericRow('Gs','입자비중 Gs',d.Gs,'',2,3,.01)}<p class="note">γw = 9.81 kN/m³ · 사질토 등 입상토의 상태 비교</p></details>`,
      render:({result:r,baseline:b})=>({title:'같은 간극비라도 상대밀도는 달라질까요?',conditions:['동일한 흙의 시험 경계','emin ≤ e ≤ emax','체적비·상태지표'],plotTitle:'같은 입자량 · 달라지는 간극',chart:relativeDiagram(r),results:metric('상대밀도 Dr',r.relativeDensity*100,'%',b?b.relativeDensity*100:null,true)+metric('현재 건조 γd',r.gammaDry,'kN/m³',b?.gammaDry??null)+metric('간극률 n',r.porosity*100,'%',b?b.porosity*100:null),explanation:`현재 e=${fmt(r.e,2)}는 가장 느슨한 emax에서 가장 조밀한 emin 쪽으로 <strong>${fmt(r.relativeDensity*100)}%</strong> 이동한 상태입니다.<span class="hint">Dr는 단순한 건조단위중량의 비가 아닙니다. 다짐도와 서로 다른 지표입니다.</span>`,theory:`<h3>분자와 분모가 모두 간극비 차이입니다</h3><div class="theory-formula">Dr = (emax−e)/(emax−emin)<br>= (${fmt(r.emax,2)}−${fmt(r.e,2)}) / (${fmt(r.emax,2)}−${fmt(r.emin,2)})<br>= ${fmt(r.relativeDensity*100)}%</div><div class="theory-grid"><div><span>가장 느슨한 기준의 γd,min</span><strong>${fmt(r.gammaDryMin,2)} kN/m³</strong></div><div><span>가장 조밀한 기준의 γd,max</span><strong>${fmt(r.gammaDryMax,2)} kN/m³</strong></div></div><p class="theory-meta">양 끝 간극비는 같은 흙의 정해진 시험법으로 얻는 값입니다. 입도·입자형태가 다른 흙의 값을 섞지 않습니다.</p>`,method:`<div><h3>정의와 단위</h3><p>Dr=(emax−e)/(emax−emin). 건조단위중량을 쓰면 Dr=[(γd−γd,min)/(γd,max−γd,min)]·(γd,max/γd)입니다. 입력은 무차원, 화면 결과는 %입니다.</p><p>도형은 Vs=1의 동일한 입자부피와 같은 수직 척도로 세 상태를 비교합니다. 다짐시험의 함수비 변화나 시공 에너지를 재현하지 않습니다.</p></div><div><h3>근거와 범위</h3><p>${sourceLink}, Eqs. 5.5–5.6.</p><p>현재 도구는 0≤Dr≤100% 상태 비교에 한정합니다. 현장값이 시험 기준 밖이면 경계 또는 측정조건을 검토해야 하므로 값을 잘라내지 않고 입력 오류로 표시합니다. 강도·침하를 Dr만으로 확정하지 않습니다.</p></div>`})},
    {key:'compaction',meta:{name:'다짐과 함수비',sub:'습윤값·건조값·ZAV',group:'흙의 성질 / 다짐',navGroup:'properties',words:'다짐 함수비 최적 최대 건조 습윤 단위중량 상대다짐도 proctor zav 영공기간극 다짐에너지 USACE 시험자료',questions:[['compaction','다짐 상태']]},defaults:{compactionMode:'synthetic',effort:'55',observeW:15,fieldW:12,fieldGammaWet:20,Gs:2.65,referenceMDD:18.5,referenceOMC:12},bounds:{observeW:[10.1,19.9,'관찰 함수비','%'],fieldW:[0,25,'현장 함수비','%'],fieldGammaWet:[14,24,'습윤단위중량','kN/m³'],Gs:[2.4,3,'입자비중',''],referenceMDD:[14,22,'기준 최대건조단위중량','kN/m³'],referenceOMC:[5,25,'기준 최적함수비','%']},labels:{compactionMode:['살펴볼 자료',''],effort:['원자료 다짐 횟수','회/층'],observeW:['관찰 함수비','%'],fieldW:['현장 함수비','%'],fieldGammaWet:['현장 습윤 γ','kN/m³'],Gs:['입자비중 Gs',''],referenceMDD:['기준 MDD','kN/m³'],referenceOMC:['기준 OMC','%']},activeFields:d=>d.compactionMode==='evidence'?['observeW']:['fieldW','fieldGammaWet','Gs','referenceMDD','referenceOMC'],compute:d=>d.compactionMode==='evidence'?CompactionEvidence.solve(d):(!d.compactionMode||d.compactionMode==='synthetic')?StateModels.compaction(d):{valid:false,errors:['살펴볼 다짐 자료를 선택하세요.']},
      controls:d=>d.compactionMode==='evidence'?CompactionEvidenceView.controls(d):CompactionEvidenceView.modeControl(d)+`<div class="parameter-grid">${fieldControl('fieldW','현장 함수비 w',d.fieldW,0,25,.5,'%','습윤값에서 건조 흙입자의 중량을 구분합니다.')}${fieldControl('fieldGammaWet','현장 습윤단위중량 γ',d.fieldGammaWet,14,24,.1,'kN/m³','현장 상태를 나타내는 관측값입니다.')}${fieldControl('Gs','입자비중 Gs',d.Gs,2.4,3,.01,'','ZAV와 포화도에 영향을 줍니다. 다짐곡선을 예측하지 않습니다.')}</div>${numericRow('referenceMDD','기준 MDD',d.referenceMDD,'kN/m³',14,22,.1)}<details class="setting"><summary>기준시험 값 · 합성 자료</summary>${numericRow('referenceOMC','기준 OMC',d.referenceOMC,'%',5,25,.5)}<p class="note">기준값은 지정된 시험에서 얻는 값입니다. 아래 5점은 실제 측정자료가 아닌 교육용 예제입니다.</p><table class="raw-table"><thead><tr><th>w (%)</th><th>습윤 γ</th><th>건조 γd</th></tr></thead><tbody>${StateModels.sampleData.map(p=>`<tr><td>${fmt(p.w,0)}</td><td>${fmt(p.gammaWet,3)}</td><td>${fmt(p.gammaWet/(1+p.w/100),2)}</td></tr>`).join('')}</tbody></table><p class="note">단위중량 kN/m³ · 입도·다짐에너지 변경을 계산하는 모형이 아닙니다.</p></details>`,
      render:ctx=>{if(ctx.data.compactionMode==='evidence')return CompactionEvidenceView.render(ctx);const r=ctx.result,b=ctx.baseline?.model===r.model?ctx.baseline:null;return ({title:'습윤단위중량이 같으면 다짐도도 같을까요?',conditions:['교육용 합성 5점','현장값과 기준시험 비교','γw = 9.81 kN/m³'],plotTitle:'함수비–건조단위중량 · 현장점과 ZAV',comparisonPlot:!!b,legend:'<span class="legend-item"><i></i>현재 현장점</span><span class="legend-item"><i class="dark"></i>ZAV</span>',chart:compactionDiagram(r,b),results:metric('상대다짐도 Rc',r.relativeCompaction*100,'%',b?b.relativeCompaction*100:null,true)+metric('현장 건조 γd',r.fieldGammaDry,'kN/m³',b?.fieldGammaDry??null)+metric('포화도 S',r.saturation*100,'%',b?b.saturation*100:null),explanation:`현장 습윤 γ=${fmt(r.fieldGammaWet,2)}에서 물의 중량을 분리하면 <strong>γd=${fmt(r.fieldGammaDry,2)} kN/m³</strong>입니다. 기준 MDD <strong>${fmt(r.referenceMDD,2)} kN/m³</strong>와의 비는 ${fmt(r.relativeCompaction*100)}%입니다.<span class="hint">현재 함수비는 기준 OMC보다 ${fmt(Math.abs(r.waterContentDifference))}%p ${r.waterContentDifference>=0?'높습니다':'낮습니다'}. 입력점 이동은 같은 시료의 실제 다짐 경로를 뜻하지 않습니다.</span>${r.warnings.length?`<span class="notice">${esc(r.warnings[0])}</span>`:''}`,theory:`<h3>함수비로 건조값을 구하고 기준시험과 비교합니다</h3><div class="theory-formula">γd = γ/(1+w/100) = ${fmt(r.fieldGammaDry,2)} kN/m³<br>Rc = γd/MDD × 100 = ${fmt(r.relativeCompaction*100)}%<br>γd,ZAV = Gs·γw/(1+Gs·w/100)<br>e = Gs·γw/γd−1 = ${fmt(r.e,3)}</div><div class="theory-grid"><div><span>현재 함수비에서 가능한 상한 · ZAV</span><strong>${fmt(r.zavAtField,2)} kN/m³</strong><p>공기부피가 0인 경계입니다. 이 선보다 높은 건조단위중량은 현재 Gs·w와 양립할 수 없습니다.</p></div><div><span>현재 공기부피 / 전체부피</span><strong>${fmt(r.airVolumeFraction*100)}%</strong><p>다짐은 주로 공극의 공기를 줄이는 과정이고, 포화토의 압밀은 배수와 함께 시간이 걸리는 과정입니다.</p></div></div>${!r.referenceMatchesSamplePeak?'<p class="notice">지정 기준 MDD·OMC가 합성 5점의 최고점과 다릅니다. 보라색 기준선은 별도로 입력한 시험 기준이며 회색 자료를 자동 재맞춤하지 않습니다.</p>':''}<p class="theory-meta">다짐에너지 증가의 일반적 경향을 슬라이더만으로 정량 예측하지 않습니다. 판정 기준을 설정하지 않았으므로 합격·불합격 결과도 만들지 않습니다.</p>`,method:`<div><h3>관측값과 시험 기준</h3><p>표의 5점은 w=[6,9,12,15,18]%에서 γd=[16.3,17.7,18.5,18.2,17.2] kN/m³가 되도록 정한 합성 자료입니다. 입력 저장은 현장값·기준값에 적용되며 합성 자료는 고정입니다.</p><p>각 점의 습윤값에서 γd를 다시 계산하고 점 사이를 직선으로 연결합니다. 곡선의 재료법칙·최적함수비 회귀·다짐에너지에 따른 예측은 구현하지 않습니다. 기본 MDD=18.5, OMC=12는 예제 최고점과 같습니다.</p></div><div><h3>이론 근거와 적용</h3><p>${sourceLink}, Eqs. 5.1–5.4와 ZAV 설명. <a href="${compactionSource}" target="_blank" rel="noopener">FHWA §7.4.1, Compaction</a>의 함수비·다짐에너지 구분.</p><p>γd=γ/(1+w/100), Rc=γd/MDD. 다짐도와 상대밀도는 다른 지표입니다. S=(w/100)Gs/e로 현장점의 물리적 정합성을 검사합니다. 참고 5점과 기준점도 현재 Gs의 ZAV를 넘으면 표시를 중단합니다.</p></div>`});}}
  ];
})();
