/** Introductory soil dynamics. Vs m/s, density kg/m³, H m, strain inputs percent,
 * stresses kPa. No site-response amplification or liquefaction-consequence solver.
 */
export const Dynamics=(()=>{
 const finite=v=>typeof v==='number'&&Number.isFinite(v),object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),bad=errors=>({valid:false,errors,warnings:[]});
 function smallStrain(input={}){if(!object(input))return bad(['전단파속도와 질량밀도를 입력하세요.']);const {velocity=200,density=1800}=input;if(![velocity,density].every(finite)||velocity<=0||density<=0)return bad(['Vs와 질량밀도 ρ는 0보다 큰 유한한 숫자여야 합니다.']);const gmax=density*velocity**2/1000,unitWeight=density*9.80665/1000;if(![gmax,unitWeight].every(finite)||gmax<=0||unitWeight<=0)return bad(['파속·밀도 조합이 계산 범위를 초과했습니다.']);return {valid:true,errors:[],warnings:[],velocity,density,gmax,unitWeight,model:'small-strain-shear-wave-stiffness-v1'};}
 function layer(input={}){const r=smallStrain(input);if(!r.valid)return r;const {thickness=20}=input;if(!finite(thickness)||thickness<=0)return bad(['층두께 H는 0보다 큰 유한한 숫자여야 합니다.']);const travelTime=thickness/r.velocity,period=4*travelTime,frequency=1/period,wavelength=4*thickness;if(![travelTime,period,frequency,wavelength].every(finite)||period<=0)return bad(['층두께·파속 조합이 계산 범위를 초과했습니다.']);const mode=Array.from({length:81},(_,i)=>({depth:thickness*i/80,shape:i===80?0:Math.cos(Math.PI*i/160),gradient:-Math.PI/(2*thickness)*Math.sin(Math.PI*i/160)}));return {...r,thickness,travelTime,period,frequency,wavelength,mode,model:'uniform-fixed-base-free-surface-quarter-wave-v1'};}
 function reduction(input={}){const r=smallStrain(input);if(!r.valid)return r;const {strain=.05,referenceStrain=.05}=input;if(![strain,referenceStrain].every(finite)||strain<0||referenceStrain<=0)return bad(['전단변형률은 0 이상, 기준변형률 γr는 0보다 큰 유한한 숫자여야 합니다.']);const ratio=1/(1+strain/referenceStrain),gsec=r.gmax*ratio,gtangent=r.gmax*ratio**2,shearStress=gsec*(strain/100),asymptote=r.gmax*(referenceStrain/100);if(![ratio,gsec,gtangent,shearStress,asymptote].every(finite)||ratio<=0)return bad(['변형률과 강성 조합이 계산 범위를 초과했습니다.']);const curve=Array.from({length:101},(_,i)=>{const strain=10**(-4+i/25),ratio=1/(1+strain/referenceStrain);return {strain,ratio,gsec:r.gmax*ratio};});return {...r,strain,referenceStrain,ratio,gsec,gtangent,shearStress,asymptote,curve,model:'specified-simple-hyperbolic-modulus-reduction-v1'};}
 function dynamicLayer(input={},question='waves'){if(question==='waves')return layer(input);if(question==='strain')return reduction(input);return bad(['파속·주기 또는 변형수준 질문을 선택하세요.']);}
 function liquefaction(input={}){if(!object(input))return bad(['동일 깊이의 응력과 지정 지진·저항 조건을 입력하세요.']);const d={acceleration:.25,total:180,effective:100,rd:.9,crr:.18,msf:1,ksigma:1,...input},errors=[];for(const k of ['acceleration','total','effective','rd','crr','msf','ksigma'])if(!finite(d[k]))errors.push(`${k}: 유한한 숫자를 입력하세요.`);if(errors.length)return bad(errors);
  if(d.acceleration<0||d.crr<0)errors.push('amax/g 및 지정 기준 CRR은 0 이상이어야 합니다.');if(d.total<=0||d.effective<=0||d.effective>d.total)errors.push('포화 지반 비교에서는 0 < σv′ ≤ σv 조건을 확인하세요.');if(d.rd<=0||d.rd>1)errors.push('지정 rd는 0보다 크고 1 이하여야 합니다.');if(d.msf<=0||d.ksigma<=0)errors.push('MSF와 Kσ는 0보다 커야 합니다.');if(errors.length)return bad(errors);
  const pore=d.total-d.effective,stressRatio=d.total/d.effective,averageShear=.65*d.acceleration*d.total*d.rd,csr=averageShear/d.effective,adjustedCrr=d.crr*d.msf*d.ksigma,factor=csr===0?null:adjustedCrr/csr,margin=adjustedCrr-csr;
  if(![pore,stressRatio,averageShear,csr,adjustedCrr,margin,...(factor===null?[]:[factor])].every(finite))return bad(['입력 조합이 계산 가능한 비율 범위를 초과했습니다.']);
  const tolerance=1e-10*Math.max(1,csr,adjustedCrr),state=csr===0?'no-demand':margin>tolerance?'resistance-larger':margin< -tolerance?'demand-larger':'equal';
  const sensitivity=Array.from({length:41},(_,i)=>{const acceleration=i/40;return {acceleration,csr:.65*acceleration*stressRatio*d.rd};});
  return {valid:true,errors:[],warnings:[],...d,pore,stressRatio,averageShear,csr,adjustedCrr,factor,margin,state,sensitivity,model:'specified-crr-msf-ksigma-over-simplified-csr-v1'};
 }
 return Object.freeze({smallStrain,layer,reduction,dynamicLayer,liquefaction});
})();
