function syncExtendedRanges(){const d=state.data[state.active];for(const range of $('controls').querySelectorAll('input[type=range][data-field]')){const f=range.dataset.field,v=d[f]/Number(range.dataset.mult||1);if(range.dataset.expand&&Number.isFinite(v)&&v>Number(range.max))range.max=String(Math.ceil(v/20)*20);range.disabled=d[f]===null||!Number.isFinite(v)||v<Number(range.min)||v>Number(range.max);if(!range.disabled)range.value=String(v);range.setAttribute('aria-valuetext',`${fmt(v,3)} ${range.dataset.unit||''}`);}}
function renderExtendedCompare(){const k=state.active,lab=labRegistry[k],a=state.baselines[k],d=state.data[k];const custom=lab.comparisonSummary?.(d,a,state.baselineNames[k]);if(custom!==null&&custom!==undefined){$('compare-summary').innerHTML=custom;return;}const names={footingLoadMode:{force:'총하중 Q 유지',pressure:'재하압 q 유지'},readingSource:{example:'교육용 지정점',usgs:'USGS 실제 기록'},evidenceBranch:{loading:'처음 재하',reloading:'짧은 제하 후 재재하',continued:'이전 최대를 넘어 추가 재하',unloading:'마지막 제하'},testBranch:{loading:'재하',unloading:'제하'},rectMode:{single:'한 재하면',double:'두 재하면'}};const display=(v,f)=>names[f]?.[v]??(v===null||v===undefined?'미입력':typeof v==='number'?fmt(v,3):typeof v==='boolean'?(v?'예':'아니오'):String(v));const question=state.question[k],active=lab.activeFields?new Set([...lab.activeFields(d,question),...lab.activeFields(a,question)]):null;const controlFields=new Set([...$('controls').querySelectorAll('[data-field]')].map(node=>node.dataset.field));const changes=Object.entries(lab.labels||{}).filter(([f])=>!lab.comparisonIgnoredFields?.includes(f)).filter(([f])=>!active||active.has(f)||controlFields.has(f)).filter(([f])=>JSON.stringify(a[f])!==JSON.stringify(d[f])).map(([f,[label,unit]])=>`${label}: ${display(a[f],f)} → ${display(d[f],f)} ${unit||''}`);$('compare-summary').innerHTML=`기준: ${esc(state.baselineNames[k])}<br>${changes.length?changes.map(esc).join('<br>'):'현재와 같은 입력입니다.'}`;}
function renderExtendedOutputs(){
 const k=state.active,lab=labRegistry[k],d=state.data[k],q=state.question[k],r=compute(k),br=state.compare[k]?compute(k,lab.baselineInput?.(d,state.baselines[k])??state.baselines[k]):null,b=br?.valid?br:null;
 renderExtendedCompare();syncExtendedRanges();renderPlotViews();$('chart').dataset.view=k;
 if(k==='excavation'&&br&&!br.valid)$('compare-summary').innerHTML+='<br><span class="hint">기준안은 현재 관찰 깊이에서 계산되지 않았습니다: '+(br.errors||[]).map(esc).join(' ')+'</span>';
 const failureDetail=k==='excavation'&&r.status==='nonconverged'&&Number.isFinite(r.depth)?` 요청 H ${fmt(r.requestedDepth,2)} m · 마지막 수렴 ${r.phase==='backfill'?'되메움':'굴착'} H ${fmt(r.depth,2)} m (${({before:'사건 전',installed:'설치 후·긴장 전',after:'사건 후'})[r.eventSide]||'수렴 상태'}).`:'';
 if(!r.valid){$('intro').innerHTML=`<div class="breadcrumb">${esc(lab.meta.group)}</div><h1>${esc(lab.meta.name)}</h1>`;$('plot-title').textContent='입력 조건 확인';$('legend').innerHTML='';$('chart').innerHTML='<div class="error-box">현재 입력의 평형 결과를 확정하지 못했습니다.'+esc(failureDetail)+'</div>';$('results').innerHTML='<div class="error-box">'+(r.errors||['입력값을 확인하세요.']).map(esc).join('<br>')+'</div>';$('explanation').textContent='입력값을 수정하면 그림과 결과를 다시 계산합니다.';$('theory').innerHTML='';$('method-content').innerHTML='<p>입력 조건이 유효하면 해당 계산과 적용 범위를 표시합니다.</p>';$('undo').disabled=histories[k].length===0&&!pendingEdit;return;}
 const v=lab.render({data:d,result:r,baseline:b,baselineData:state.baselines[k],question:q});
 $('intro').innerHTML=`<div class="breadcrumb">${esc(lab.meta.group)}</div><h1>${esc(v.title)}</h1><div class="conditions">${(v.conditions||[]).map(t=>`<span class="condition">${esc(t)}</span>`).join('')}</div>`;
 $('plot-title').textContent=v.plotTitle||lab.meta.name;$('legend').innerHTML=v.legend===undefined?'<span class="legend-item"><i></i>현재</span>':v.legend;
 if(b&&v.comparisonPlot===true)$('legend').innerHTML+='<span class="legend-item"><i class="dashed"></i>기준</span>';
 $('chart').innerHTML=v.chart;$('results').innerHTML=v.results;$('explanation').innerHTML=v.explanation||'';$('theory').innerHTML=v.theory||'';$('method-content').innerHTML=v.method||'';renderReferenceGuide();renderLearningContext();
 $('undo').disabled=histories[k].length===0&&!pendingEdit;
}
