function soilMassData(d){
 if(d.mode==='mass'){const r=SoilInputs.retainedToPassing(d.massRows);return {...r,inputRows:d.massRows};}
 try{const r=SoilInputs.sieveMassFromPassing(getPoints(d),1000);return {...r,inputRows:r.rows||[]};}catch(error){return {valid:false,errors:error.inputErrors||['입도 자료를 먼저 수정하세요.'],inputRows:[]};}
}
function soilMassConversionNotes(r){return `${r.boundaryInterpolated?'<p class="note" data-sieve-interpolation>0.075 mm 통과율은 양쪽 입경 자료를 로그 보간한 환산값입니다. 해당 체의 실측값이 아닙니다.</p>':''}${r.discardedFinePointCount?'<p class="note" data-sieve-fine-detail>0.075 mm 미만 입도 세부는 팬에 합쳐집니다. 그 구간의 D값·입도계수는 질량 모드에서 정보가 부족해질 수 있습니다. 전환은 되돌리기로 복구할 수 있습니다.</p>':''}`;}
function soilMassControls(d){const r=soilMassData(d),panOpening=r.panOpening,panLabel=Number.isFinite(panOpening)?'팬 (<'+inputNumber(panOpening)+' mm)':'팬';return `<p class="parameter-note">${d.mode==='mass'?'체별 잔류질량을 직접 입력하고 있습니다.':'현재 입도곡선을 총 1,000 g 시료의 잔류질량으로 환산했습니다. 값을 편집하면 질량 입력 모드로 전환됩니다.'}</p>${soilMassConversionNotes(r)}<p class="note">${Number.isFinite(panOpening)?'이 표의 팬은 '+inputNumber(panOpening)+' mm보다 작은 흙입니다.':'팬은 이 표의 최소 체눈을 통과한 흙입니다.'} 세립분은 별도로 0.075 mm 통과율에서 읽습니다.</p>${r.inputRows.length?`<table class="raw-table mass-table"><thead><tr><th>체 눈금 mm</th><th>잔류질량 g</th></tr></thead><tbody>${r.inputRows.map((row,i)=>`<tr><td>${row.size===null?esc(panLabel):esc(row.size)}</td><td><input type="number" min="0" step="any" data-mass-index="${i}" value="${esc(inputNumber(row.mass))}" aria-label="${row.size===null?'팬':row.size+' mm 체'} 잔류질량"></td></tr>`).join('')}</tbody></table>`:`<p class="error-box">${(r.errors||[]).map(esc).join('<br>')}</p><button type="button" data-soil-view="gradation">입도 입력으로</button>`}<details class="setting"><summary>분류용 소성 정보</summary>${numericRow('ll','액성한계 LL',d.ll,'%')}${numericRow('pl','소성한계 PL',d.pl,'%')}<label class="check"><input type="checkbox" data-field="np" ${d.np?'checked':''}>비소성(NP)</label></details><button class="data-link" type="button" data-soil-view="gradation">입도곡선과 분류 보기</button>`;}
function updateSoilMass(index,value){const d=state.data.soil;if(d.mode!=='mass'){const r=soilMassData(d);if(!r.valid)throw new Error('유효한 입도 자료가 필요합니다.');d.massRows=r.rows.map(({size,mass})=>({size,mass}));d.mode='mass';}d.massRows[index].mass=value;}
function chartSieveMass(d){const r=soilMassData(d);if(!r.valid)return '<div class="error-box">잔류질량을 확인하세요.</div>';const rows=r.rows,max=Math.max(1,...rows.map(x=>x.retainedPercent)),dx=550/rows.length,y=v=>260-v/Math.max(40,max)*195;let s='<text x="60" y="27">체별 잔류율 (%)</text>';for(let i=0;i<=4;i++){const v=Math.max(40,max)*i/4;s+=`<line x1="60" x2="610" y1="${y(v)}" y2="${y(v)}" class="grid"/><text x="48" y="${y(v)+4}" text-anchor="end">${fmt(v,0)}</text>`;}rows.forEach((row,i)=>{const x=60+i*dx,w=Math.max(6,dx-10);s+=`<rect x="${x+5}" y="${y(row.retainedPercent)}" width="${w}" height="${260-y(row.retainedPercent)}" rx="3" fill="${row.size===null?'#B357FF':'#0F6FFF'}"/><text x="${x+dx/2}" y="${y(row.retainedPercent)-8}" text-anchor="middle">${fmt(row.retainedPercent,1)}</text><text x="${x+dx/2}" y="283" text-anchor="middle" transform="rotate(-35 ${x+dx/2} 283)">${row.size===null?'팬':row.size}</text>`;});s+='<text x="610" y="328" text-anchor="end">큰 체 → 작은 체 → 팬</text>';return svgWrap(s,`체별 잔류질량에서 구한 잔류율 막대. 팬은 ${inputNumber(r.panOpening)} mm 통과분입니다.`);}
function renderSieveMassOutput(d,r){const m=soilMassData(d);$('chart').innerHTML=chartSieveMass(d);$('results').innerHTML=metric('총 건조질량',m.totalMass,'g',null,true)+metric('0.075 mm 통과 세립분',r.fines,'%',null)+metric('전체 흙의 분류',r.symbol||'정보 부족','',null);$('explanation').innerHTML='<strong>통과율은 그 체보다 작은 입자의 질량 비율입니다.</strong><br>잔류질량을 전체 질량으로 나눈 뒤, 큰 체부터 누적한 잔류율을 100%에서 빼면 통과율이 됩니다.';$('legend').innerHTML='<span class="legend-item"><i></i>체별 잔류율</span>';}
function renderSieveMassTheory(d){const m=soilMassData(d);if(!m.valid)return '';return `<h3>질량에서 입도곡선까지</h3><div class="theory-formula">잔류율 = 체별 잔류질량 / 총 건조질량 × 100<br>누적 통과율 = 100 − 누적 잔류율</div><table class="raw-table"><thead><tr><th>체 mm</th><th>잔류 g</th><th>잔류 %</th><th>누적잔류 %</th><th>통과 %</th></tr></thead><tbody>${m.rows.map(row=>`<tr><td>${row.size===null?'팬':row.size}</td><td>${fmt(row.mass,1)}</td><td>${fmt(row.retainedPercent,1)}</td><td>${fmt(row.cumulativeRetained,1)}</td><td>${row.size===null?'—':fmt(row.passing,1)}</td></tr>`).join('')}</tbody></table><p class="theory-meta">모든 체와 팬의 건조질량을 포함합니다. 팬의 질량을 빼면 전체 질량과 세립분 비율이 잘못됩니다. 질량을 같은 배수로 늘려도 입도곡선과 분류는 같습니다.</p>`;}
