function installCloudWorkspace(adapter){
 const el=(tag,text)=>{const item=document.createElement(tag);if(text)item.textContent=text;return item;};
 const entry=el('button','저장·동기화');entry.type='button';entry.id='cloud-workspace-open';entry.className='cloud-workspace-open';document.querySelector('.app-header').append(entry);
 const dialog=el('dialog');dialog.id='cloud-workspace-dialog';dialog.className='cloud-workspace-dialog';const heading=el('h2','내 자료'),close=el('button','닫기');close.type='button';close.className='cloud-close';const top=el('div');top.className='cloud-heading';top.append(heading,close);const status=el('p','연결 확인 중');status.id='cloud-status';status.setAttribute('role','status');
 const info=el('p','실험 입력·비교 기준, 내 예제·복습 기록, 계산서를 함께 보관합니다.');info.className='note';const actions=el('div');actions.className='cloud-actions';const exportButton=el('button','전체 자료 내보내기'),importButton=el('button','전체 자료 가져오기'),refreshButton=el('button','연결 다시 확인');actions.append(exportButton,importButton,refreshButton);
 const choices=el('div');choices.className='cloud-choice';choices.hidden=true;const choiceNote=el('p'),localButton=el('button','이 기기 자료 사용'),remoteButton=el('button','서버 자료 사용'),remoteExport=el('button','서버 자료 내보내기'),pauseButton=el('button','지금은 기기에만 저장');choices.append(choiceNote,localButton,remoteButton,remoteExport,pauseButton);
 const file=el('input');file.type='file';file.accept='.json,application/json';file.hidden=true;const preview=el('div');preview.className='cloud-choice';preview.hidden=true;const previewText=el('p'),applyButton=el('button','현재 자료를 백업하고 적용'),cancelButton=el('button','취소');preview.append(previewText,applyButton,cancelButton);const error=el('p');error.className='cloud-error';error.setAttribute('role','alert');dialog.append(top,status,info,actions,choices,preview,file,error);document.body.append(dialog);
 let candidate=null,restoring=false,externalTabChange=false;
 function download(records,suffix=''){const blob=new Blob([WorkspaceFiles.serialize(records)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='soil-sense-workspace'+suffix+'-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
 const safe=fn=>async()=>{error.textContent='';try{await fn();}catch(e){error.textContent=e.message||'자료를 확인하세요.';}};
 const request=async(method,body,owner)=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch('/api/workspace',{method,credentials:'same-origin',cache:'no-store',redirect:'error',signal:controller.signal,headers:{'Content-Type':'application/json','X-Geotech-Client':'workspace-v1',...(owner?{'X-Geotech-Account':owner}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!response.ok)throw Object.assign(new Error('연결 오류'),{status:response.status});if(!response.headers.get('content-type')?.includes('application/json'))throw Object.assign(new Error('로그인이 필요합니다'),{status:403});return await response.json();}finally{clearTimeout(timer);}};
 const linkKey='soil-sense-cloud-link-v1';
 const sync=createCloudWorkspaceSync({capture:adapter.capture,apply:records=>{restoring=true;try{adapter.apply(records);}finally{restoring=false;}},request,readLink:()=>{try{return JSON.parse(localStorage.getItem(linkKey)||'null');}catch{return null;}},persistLink:link=>localStorage.setItem(linkKey,JSON.stringify(link)),onStatus:value=>{
  status.textContent=value.message;entry.dataset.phase=value.phase;entry.title=value.message;entry.textContent=['choice','conflict','auth','local-error','too-large'].includes(value.phase)?'저장·동기화 !':'저장·동기화';choices.hidden=!['choice','conflict'].includes(value.phase);remoteButton.disabled=remoteExport.disabled=!value.remote?.records;
  choiceNote.textContent=value.phase==='conflict'?'자동으로 덮어쓰지 않았습니다. 양쪽 자료를 내보낸 뒤 사용할 전체 자료를 선택하세요. 선택한 쪽으로 실험·학습함·계산서 전체가 바뀝니다.':'처음 연결할 때 자료를 자동으로 올리지 않습니다. 사용할 전체 자료를 선택하세요. 이 기기 자료를 선택하면 서버의 기존 자료가 교체됩니다.';
  refreshButton.textContent=value.phase==='auth'?'다시 로그인':'연결 다시 확인';
 }});
 globalThis.geotechCloud={assertWritable:()=>{if(externalTabChange)throw new Error('다른 탭에서 자료가 바뀌었습니다. 전체 자료를 내보낸 뒤 새로고침하세요.');},changed:()=>{if(!restoring)sync.changed();}};
 entry.addEventListener('click',()=>{dialog.showModal();});close.addEventListener('click',()=>dialog.close());exportButton.addEventListener('click',safe(()=>download(adapter.capture())));remoteExport.addEventListener('click',safe(()=>download(sync.remoteRecords(),'-server')));
 importButton.addEventListener('click',()=>{file.value='';file.click();});file.addEventListener('change',safe(async()=>{const selected=file.files?.[0];if(!selected)return;if(selected.size>WorkspaceFiles.maxBytes)throw new Error('6 MiB 이하의 파일을 선택하세요.');candidate=adapter.validate(WorkspaceFiles.parse(await selected.text()));previewText.textContent='실험 전체·학습함·계산서를 이 파일의 자료로 교체합니다. 적용 전에 현재 자료가 JSON 파일로 내려받아집니다.';preview.hidden=false;}));
 cancelButton.addEventListener('click',()=>{candidate=null;preview.hidden=true;});applyButton.addEventListener('click',safe(()=>{if(!candidate)return;download(adapter.capture(),'-before-import');restoring=true;try{adapter.apply(candidate);}finally{restoring=false;}candidate=null;preview.hidden=true;sync.changed();}));
 localButton.addEventListener('click',safe(async()=>{if(sync.remoteRecords())download(sync.remoteRecords(),'-server-before-replace');await sync.choose('local');}));remoteButton.addEventListener('click',safe(async()=>{download(adapter.capture(),'-before-cloud');await sync.choose('remote');}));pauseButton.addEventListener('click',()=>sync.localOnly());refreshButton.addEventListener('click',safe(()=>sync.getStatus().phase==='auth'||externalTabChange?location.reload():sync.connect()));
 const autoConnect=()=>{if(!externalTabChange&&sync.getStatus().phase!=='local'&&!document.hidden)void sync.connect();};window.addEventListener('online',autoConnect);window.addEventListener('focus',autoConnect);window.addEventListener('storage',event=>{if(Object.values(WorkspaceFiles.keys).includes(event.key)){externalTabChange=true;sync.localOnly();status.textContent='다른 탭에서 자료가 바뀌었습니다. 현재 자료를 내보낸 뒤 새로고침하세요.';}});
 setInterval(()=>{if(navigator.onLine)autoConnect();},60000);
 if(location.protocol==='file:')sync.localOnly();else void sync.connect();
 return {sync,adapter};
}
